Link sections on `throw` and handling exceptions
dotnet/csharpstandard pull request #1005
Opened 2023-11-22 20:38 UTC by BillWagner

Fixes #776

Links are added in both directions between §21.4 and §13.10.6.

2023-11-22 22:17 UTC, RexJaeschke requested changes
Bill, these links look like hard-coded numbers rather than md [...](...) links.

2023-11-23 08:22 UTC, jskeet reviewed
Looks good to me other than Rex's comments about the form of the links.

2023-11-23 10:35 UTC, KalleOlaviNiemitalo commented on standard/exceptions.md
> +When an exception is thrown (§13.10.6), the system searches for the nearest catch clause that can handle the exception, as determined by the run-time type of the exception. First, the current method
I'd prefer linking from here to [21.2 Causes of exceptions](https://github.com/dotnet/csharpstandard/blob/1b8e8c35345d9cbb3838de7cd40c23da1070c215/standard/exceptions.md#212-causes-of-exceptions), which already includes a link to [13.10.6 The throw statement](https://github.com/dotnet/csharpstandard/blob/1b8e8c35345d9cbb3838de7cd40c23da1070c215/standard/statements.md#13106-the-throw-statement).  This would make it clearer that the paragraph also applies to NullReferenceException etc. when thrown by the runtime without a `throw` statement.

2023-11-27 15:49 UTC, BillWagner commented
> Bill, these links look like hard-coded numbers rather than md `[...](...)` links.

@RexJaeschke The tool should fix those once we merge this PR.

2023-11-29 21:02 UTC, BillWagner commented on standard/exceptions.md
> +When an exception is thrown (§13.10.6), the system searches for the nearest catch clause that can handle the exception, as determined by the run-time type of the exception. First, the current method
Making the comment into a suggestion:

```suggestion
When an exception is thrown (§21.2), the system searches for the nearest catch clause that can handle the exception, as determined by the run-time type of the exception. First, the current method is searched for a lexically enclosing `try` statement, and the associated `catch` clauses of the `try` statement are considered in order. If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method. This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown. A `catch` clause that doesn’t name an exception class can handle any exception.
```

2023-11-29 21:03 UTC, MadsTorgersen approved these changes

2023-11-29 21:04 UTC, Nigel-Ecma approved these changes

2023-11-29 21:04 UTC, gafter commented on standard/exceptions.md
> +When an exception is thrown (§13.10.6), the system searches for the nearest catch clause that can handle the exception, as determined by the run-time type of the exception. First, the current method
```suggestion
When an exception is thrown (§21.2), the system searches for the nearest catch clause that can handle the exception, as determined by the run-time type of the exception. First, the current method is searched for a lexically enclosing `try` statement, and the associated `catch` clauses of the `try` statement are considered in order. If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method. This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown. A `catch` clause that doesn’t name an exception class can handle any exception.
```

2023-11-29 21:05 UTC, gafter approved these changes

2023-11-29 21:06 UTC, RexJaeschke approved these changes

2023-11-29 21:06 UTC, merged