Small tweaks to "Local variable declarations"
dotnet/csharpstandard pull request #1208
Opened 2024-11-14 18:02 UTC by RexJaeschke

[This proposal is the result of a private conversation I had with Nigel, and is intended to reflect our final agreement.]

I’m working on the spec for a future feature that involves changes to [§13.6.2.1 General](statements.md#13621-general), in the grammar that starts with rule *local_variable_declaration*. However, once I started reading the draft V8 spec of that section, I got confused. **I think some text, a grammar rule name, and a section name are misleading**, and I’d like to change them before I continue with the other task.

In V6 (prior to the addition of ref/ref-readonly on locals), this section was simple, but as the grammar allowed all kinds of invalid constructs w.r.t implicitly typed local variable declarations, there was a non-trivial bullet list of constraints expressed in text. My original proposal for the V7 feature ref/ref-readonly locals involved light edits to that section. However, it appears that during TG2’s integration of that feature, the grammar was completely rewritten to incorporate all the previous text constraints, and broken into 3 subparts, each of which got its own new section (along with a General intro), as follows: 

- 13.6.2 Local variable declarations 
  - 13.6.2.1 General 
  - 13.6.2.2 Implicitly typed local variable declarations 
  - 13.6.2.3 Explicitly typed local variable declarations 
  - 13.6.2.4 Ref local variable declarations

§13.6.2.1 General starts by saying

> Local variable declarations fall into one of the three categories: implicitly typed, explicitly typed, and ref local. 

My interpretation was that this implied the three categories are mutually exclusive, when they are not! (A ref local could be implicit or explicit.) In any event, Nigel and I agreed to disagree on that interpretation, but we agreed this para adds no value and should be removed.

We agreed to rename rule *ref_local_variable_declaration* to *explicitly_typed_ref_local_variable_declaration*, which requires Section “13.6.2.4 Ref local variable declarations” to be renamed “13.6.2.4 Explicitly typed ref local variable declarations” with any links to that section being updated.
 
The grammar in “13.6.2.2 Implicitly typed local variable declarations” contains *ref_kind*, but doesn’t explain that, so a pointer to “13.6.2.4 Ref local variable declarations,” which does explain that, should be added.

2024-11-15 02:41 UTC, Nigel-Ecma requested changes
Revert *explicitly_typed_ref_local_variable_declarators*. The rest looks good and I approve in advance once the reversion is done.

2024-11-15 02:41 UTC, Nigel-Ecma commented on standard/statements.md
> +    : ref_kind type explicitly_typed_ref_local_variable_declarators
```suggestion
    : ref_kind type ref_local_variable_declarators
```

See next comment for reason

2024-11-15 02:41 UTC, Nigel-Ecma commented on standard/statements.md
> +explicitly_typed_ref_local_variable_declarators
```suggestion
ref_local_variable_declarators
```

This rule is a list of *ref_local_variable_declarator* so should be named at it, there is no explicit type in the declarator. Note *implicitly_typed_local_variable_declaration* also uses *ref_local_variable_declarator*.

2024-11-17 08:13 UTC, Nigel-Ecma approved these changes

2024-11-17 09:13 UTC, KalleOlaviNiemitalo commented on standard/statements.md
> +An *implicity_typed_local_variable_declaration* introduces a single local variable, *identifier*. The *expression* or *variable_reference* shall have a compile-time type, `T`. The first alternative d
Shouldn't that be

* *implicit<ins>l</ins>y_typed_local_variable_declaration* rather than "implicity"
* *ref_kind* not in code font

2024-11-17 12:28 UTC, KalleOlaviNiemitalo commented on standard/statements.md
> +An *implicity_typed_local_variable_declaration* introduces a single local variable, *identifier*. The *expression* or *variable_reference* shall have a compile-time type, `T`. The first alternative d
```suggestion
An *implicitly_typed_local_variable_declaration* introduces a single local variable, *identifier*. The *expression* or *variable_reference* shall have a compile-time type, `T`. The first alternative declares a variable with an initial value of *expression*; its type is `T?` when `T` is a non-nullable reference type, otherwise its type is `T`. The second alternative declares a ref variable with an initial value of `ref` *variable_reference*; its type is `ref T?` when `T` is a non-nullable reference type, otherwise its type is `ref T`. (*ref_kind* is described in [§15.6.1](classes.md#1561-general).)
```

2024-11-17 17:34 UTC, merged