Add more NRT examples
dotnet/csharpstandard pull request #1225
Opened 2024-12-02 18:31 UTC by BillWagner

Fixes #1214

Add examples as noted in the referenced comments.

2024-12-02 22:30 UTC, Nigel-Ecma requested changes
There is a left-over para, or one that was going to be replaced.

I think “The compiler” here should probably always be ”A compiler” – there are a few of the latter already.

2024-12-02 22:30 UTC, Nigel-Ecma commented on standard/types.md
> +> ```
Should the next line (964) markdownlint-disable be deleted? It isn't paired with an enable.

2024-12-02 22:30 UTC, Nigel-Ecma commented on standard/types.md
> +> In the previous example, the backing field for the `DisappearingProperty` is set to null when it is read. However, a compiler may assume that reading a property doesn’t change the null state of tha
Example above has been replaced, this para describes the old version.

2024-12-03 15:31 UTC, BillWagner commented
@Nigel-Ecma @RexJaeschke 

> I think “The compiler” here should probably always be ”A compiler” – there are a few of the latter already.

I did replace instances of "the compiler" as it relates to this PR with "a compiler".  A search in the standard uncovers 68 other instances of "the compiler". Some should not be changed. They are part of a longer phrase like "the compiler generated backing field" for properties and field like events.

Should I change others where the language is similar to those Nigel mentioned in this PR? Should I add it to this PR, or create a separate smaller PR?

2024-12-03 16:04 UTC, RexJaeschke commented
@BillWagner Yes, please change them, as appropriate. If there are occurrences in other topics then I think a separate PR would be best, making it a general editorial fix.

2024-12-03 21:59 UTC, Nigel-Ecma commented
@BillWagner & @RexJaeschke – I agree with Rex to change the ones you see.

It is easy to go down a rabbit hole here; I started as Bill did and saw each “the” needs to be examined – e.g. as in the backing field example “the” refers to the field and not the compiler. From there I started looking into “automatically” – as in “the compiler automatically…” – and these often should at least be something like “a compiler shall/must/may” – this is a spec not a description after all. Once we get to these we need to decide what is being *required* etc. Rabbit hole! This language I expect in many cases dates from the descriptive material from which the 1st edition was written, it will be a long road and incremental is the way to go.

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +>     _ = s = null; // Null check by testing equality. The null state of o is maybe null
Is this meant to be `s == null`? At the moment this is an assignment...

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +>     _ = s = null; // Null check by testing equality. The null state of o is maybe null
(And what is "o" referred to in the comment? I'm guessing s used to be o - needs to be changed below in multiple places.)

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +>        _ = s?[4]; //is a null check and changes the null state of o to maybe null
We're missing a noun at the start of the sentence, and a space after `//`

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +Both auto-property and field like event declarations make use of a compiler generated backing field. Null state may assume that assignment to the event or property as assignment to a compiler generat
```suggestion
Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state may assume that assignment to the event or property as assignment to a compiler generated backing field.
```

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +> *Example*: A compiler can determine that writing an auto-property or field like event writes the corresponding compiler generated backing field. The null state of the property matches that of the b
```suggestion
> *Example*: A compiler can determine that writing an auto-property or field-like event writes the corresponding compiler generated backing field. The null state of the property matches that of the backing field.
```

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +Both auto-property and field like event declarations make use of a compiler generated backing field. Null state may assume that assignment to the event or property as assignment to a compiler generat
(I'd personally prefer to hyphenate compiler-generated everywhere as well, but I'm not doing that now. Field-like events are hyphenated consistently though, I believe.)

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +>     length = s.Length; // warning, and changes the null state of o to not null
```suggestion
>     length = s.Length; // Warning, and changes the null state of o to not null
```

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +>         int len = t.P.Length; // No warning. null state is not null
```suggestion
>         int len = t.P.Length; // No warning. Null state is not null.
```

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +> In the previous example, the constructor doesn't set `P` to a not null value, and a compiler issues a warning. There's no warning when the `P` property is accessed, because the type of the property
> and a compiler issues a warning

Issues, or may issue?

2024-12-04 09:09 UTC, jskeet commented on standard/types.md
> +A compiler may use any expression that dereferences a variable, property, or event to set the null state to not null. If it were null, the dereference expression would have thrown a `NullReferenceExc
Do we want to add a note about extension methods, where calling an extension method *looks* like it dereferences a variable, but doesn't actually do so?

2024-12-04 13:58 UTC, BillWagner commented on standard/types.md
> +>     _ = s = null; // Null check by testing equality. The null state of o is maybe null
```suggestion
>     _ = s == null; // Null check by testing equality. The null state of s is maybe null
```

2024-12-04 15:06 UTC, BillWagner commented
> Yes, please change them, as appropriate. If there are occurrences in other topics then I think a separate PR would be best, making it a general editorial fix.

Added in #1126

2024-12-10 12:10 UTC, jskeet commented on standard/types.md
> +Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state may assume that assignment to the event or property as assignment to a compiler generat
```suggestion
Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state analysis may assume that assignment to the event or property is an assignment to a compiler generated backing field.
```

2024-12-10 12:10 UTC, jskeet commented on standard/types.md
> +Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state may assume that assignment to the event or property as assignment to a compiler generat
(Or change "assume that" to "treat".)

2024-12-10 12:10 UTC, jskeet commented on standard/types.md
> +>             int len = t.DisappearingProperty.Length; // No warning. A compiler can assume state
I suspect the second sentence *is* as intended, but sounds incomplete to me.

2024-12-10 12:10 UTC, jskeet commented on standard/types.md
> +>
Remove blank line?

2024-12-10 16:06 UTC, BillWagner commented on standard/types.md
> +>             int len = t.DisappearingProperty.Length; // No warning. A compiler can assume state
reworded that sentence.

2024-12-11 19:47 UTC, jnm2 commented on standard/types.md
> +Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state analysis may infer that assignment to the event or property is an assignment to a compi
Uber nitpick :D
```suggestion
Both auto-property and field-like event declarations make use of a compiler-generated backing field. Null state analysis may infer that assignment to the event or property is an assignment to a compiler generated backing field.
```

2024-12-11 19:49 UTC, jnm2 commented on standard/types.md
> +Both auto-property and field-like event declarations make use of a compiler generated backing field. Null state analysis may infer that assignment to the event or property is an assignment to a compi
Also "auto-property" vs "auto property" but that one is likely a separate item if it's even palatable to consider.

2024-12-11 19:50 UTC, jnm2 approved these changes

2024-12-11 20:06 UTC, jskeet approved these changes

2024-12-11 20:07 UTC, Nigel-Ecma approved these changes

2024-12-11 20:07 UTC, MadsTorgersen approved these changes

2024-12-11 20:07 UTC, jskeet commented
Approved 2024-12-11 call.

2024-12-11 20:08 UTC, gafter approved these changes

2024-12-11 20:15 UTC, merged