Treat stackalloc like array creation.
dotnet/csharpstandard pull request #1237
Opened 2024-12-15 01:00 UTC by gafter

Fixes #1232

2024-12-15 03:02 UTC, Nigel-Ecma requested changes
Note: I have not reviewed the PR *per se*, just why it is failing grammar validation.

This PR will fail grammar validation as it changes a production that the validator itself alters to resolve MLR.

Before this PR can be committed a manual grammar validation will be required **and** the grammar validator updated (if the later is not done all future PRs will fail validation).

I’ll take responsibility for doing these, till then I'll block merging by checking “Request changes”.

2025-01-22 21:22 UTC, jskeet approved these changes
I believe this is a good change, in terms of the grammar giving the right *feeling* for the difference. As Nigel has said, in a parallel universe we might have picked an entirely different approach, but I think this is the best change for where we are today.

2025-01-22 21:25 UTC, jskeet commented
(It sounds like @gafter has found more issues though...)

2025-03-19 23:02 UTC, gafter commented
No, not more issues. It is just the grammar validation.

2025-03-20 07:33 UTC, jskeet commented
Okay, so just to check, is the ball now in @Nigel-Ecma's court to validate the grammar and update the validator?

2025-03-20 08:49 UTC, Nigel-Ecma commented
> Okay, so just to check, is the ball now in @Nigel-Ecma's court to validate the grammar and update the validator?

@jskeet – Essentially yes, my [earlier comment](https://github.com/dotnet/csharpstandard/pull/1237#pullrequestreview-2504288404) provides details.

2025-05-08 22:07 UTC, Nigel-Ecma commented
This PR is subsumed by *Grammar – Consistency & Cleanup 5* #1322. If #1322 is approved this PR should be closed.

2025-06-03 18:16 UTC, closed without merging

2025-06-03 18:16 UTC, RexJaeschke commented
Closing this based on Comment https://github.com/dotnet/csharpstandard/pull/1237#issuecomment-2864542420.

2025-07-02 19:17 UTC, jskeet commented
We need to see whether #1322 solved this. We're not sure.