C# 6.0 feature: Exception Filters
dotnet/csharpstandard pull request #2
Opened 2020-10-23 18:32 UTC by BillWagner

Add "when" as a contextual keyword.
Update grammar for exception filters
Add description of exception filters.

2020-12-12 19:11 UTC, RexJaeschke commented
I originally created this proposal in the conversion-to-markdown repo as [PR107](https://github.com/ECMA-TC49-TG2/conversion-to-markdown/pull/107). It had two commits, to update statements.md and lexical-structure.md. Later, @BillWagner force-pushed that work over here, but as best as I can tell, the front part of the statements.md commit got lost, and needs to be put back. (Bill, being a novice GitHub user, rather than trying to figure our how to salvage that missing text from the commit, I'm showing it [the complete/replacement *try_statement* grammar] here, so Nigel can continue his review.)

```antlr
try_statement
    : 'try' block catch_clause+
    | 'try' block finally_clause
    | 'try' block catch_clause+ finally_clause
    ;
catch_clause
    : 'catch' exception_specifier? exception_filter?  block
    ;
exception_specifier
    : '(' type identifier? ')'
    ;
exception_filter
    : 'when' '(' expression ')'
    ;
finally_clause
    : 'finally' block
    ;
```

@BillWagner  - I updated this PR with the above grammar on 2021/07/15

2020-12-13 22:22 UTC, Nigel-Ecma commented
Thanks for the proposed grammar Rex, makes it easier :-) 

An observation on the grammar, I'll decide later whether it is more than that (i.e. this is my note pad!)

For comparison this is the current grammar in ANTLR:

```ANTLR
try_statement
    : 'try' block catch_clauses
    | 'try' block catch_clauses* finally_clause
    ;
catch_clauses
    : specific_catch_clause+
    | specific_catch_clause* general_catch_clause
    ;
specific_catch_clause
    : 'catch' '(' type identifier? ')'  block
    ;
general_catch_clause
    : 'catch' block
    ;
finally_clause
    : 'finally' block
    ;
```

Notes:

- In the original grammar *try_statement* syntactically enforces that there must be at least one `catch` or `finally` in a `try`, and `finally` must be last if there is one.
- Similarly *catch_clauses* syntactically enforces that a *general_catch_clause* must be last
- In the proposed grammar *try_statement* is expanded to three alternatives (the syntax is equivalent to the original), maybe to match the text’s “There are three possible forms...”?, and continues to syntactically enforce the same conditions as the original grammar
- However that a catch clause without any *exception_specifier* or *exception_filter* (the original’s *general_catch_clause*) must be last is no longer enforced syntactically and moves to the text as a semantic rule.

Conclusion? None, for now just an observation...

2020-12-14 02:43 UTC, Nigel-Ecma commented on standard/statements.md
>  - A `try` block followed by one or more `catch` blocks followed by a `finally` block.
This original para & bullet list are redundant, the forms are not referenced elsewhere and it simply a prose description of the `try_statement` production. In the original that production only has two alternatives:

```
try_statement
    : 'try' block catch_clauses
    | 'try' block catch_clauses* finally_clause
    ;
```

while the proposal expands this to three, maybe just to match this (original) bullet list, though the described syntax is identical.

The descriptions of other statements do not generally start with a prose description of the statement structure, so there is not a pattern being followed here, however the switch statement does.

Option 1: 😄 Remove this para & bullet list

Option 2: 🚀 Follow the model of the switch statement and replaced with a more succinct description which doesn't introduce "forms". Something like:

> A *try_statement* consists of the keyword `try` followed by a *block*, then zero or more *catch_clauses*, then an optional *finally_clause*. There must be at least one *catch_clause* or a *finally_clause*.

Option 3: 👀 Leave as is

If Option 1 or 2 is chosen then the grammar for *try_statement* can revert to the two alternative original version, of option 3 is chosen then there is a small argument for the proposed three alternative version.

2021-07-15 13:40 UTC, BillWagner commented on standard/statements.md
> +When a `catch` clause specifies an *exception_specifier*, the type shall be `System.Exception` or a type that derives from `System.Exception`.
Done.

2021-07-15 13:44 UTC, BillWagner commented on standard/statements.md
> +In order to locate a handler for an exception, `catch` clauses are examined in lexical order. If a `catch` clause specifies a type but no exception filter, it is a compile-time error for a later `cat
Line numbers moved. The above comment references 1122 and 1116 now instead of 1116 and 1112, respectively.  I made the edit.

2021-07-15 13:58 UTC, BillWagner commented
Status update:

Most of the comments above have been addressed.  The following are still unresolved:

- Changes arising from https://github.com/dotnet/csharpstandard/pull/2#issuecomment-744665141.  I don't see a parallel PR, so we could discuss Nigel's suggested bullets or add a prose description to this PR.
- Nigel's set of proposals in https://github.com/dotnet/csharpstandard/pull/2#discussion_r542074435.  (My own preference is option 2).

2021-07-28 00:32 UTC, gafter requested changes, later dismissed
Some mall changes suggested.

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +In order to locate a handler for an exception, `catch` clauses are examined in lexical order. If a `catch` clause specifies a type but no exception filter, it is a compile-time error for a later `cat
```suggestion
In order to locate a handler for an exception, `catch` clauses are examined in lexical order. If a `catch` clause specifies a type but no exception filter, it is a compile-time error for a later `catch` clause of the same `try` statement to specify a type that is the same as, or is derived from, that type.
```

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +  - The `catch` clauses, if any, are examined in order of appearance to locate a suitable handler for the exception. If a `catch` clause does not specify a type, or specifies the exception type or a
```suggestion
  - The `catch` clauses, if any, are examined in order of appearance to locate a suitable handler for the exception. Each `catch` clause that does not specify a type, or specifies the exception type or a base type of the exception type, is considered a match. If a matching `catch` clause is located:
```

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +    - If the `catch` clause declares an exception filter, the filter is evaluated. If it evaluates to `false`, the catch clause is not a match, and the search continues through any subsequent `catch`
```suggestion
    - If the `catch` clause declares an exception filter, the filter is evaluated. If it evaluates to `false`, the search continues through any subsequent `catch` clauses for a suitable handler.    
```

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +    - Otherwise, the `catch` clause is considered a match, and control is transferred to the matching `catch` block.
```suggestion
    - Otherwise control is transferred to the corresponding `catch` block.
```

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +  - The `catch` clauses, if any, are examined in order of appearance to locate a suitable handler for the exception. If a `catch` clause does not specify a type, or specifies the exception type or a
Remove duplicate description of general catch clause.

2021-07-28 00:32 UTC, gafter commented on standard/statements.md
> +    - If the `catch` clause declares an exception filter, the filter is evaluated. If it evaluates to `false`, the catch clause is not a match, and the search continues through any subsequent `catch`
Remove text that asserts that a catch clause that is a match is not a match.

2021-07-28 07:35 UTC, KalleOlaviNiemitalo commented on standard/statements.md
> +When a `catch` clause specifies both a *class_type* and an *Identifier*, an ***exception variable*** of the given name and type is declared. The exception variable corresponds to a local variable wit
It seems odd that the exception is already "being handled" during execution of the *exception_filter* even though an "exception handler" has not been located yet.

2021-09-20 03:01 UTC, Nigel-Ecma commented
Back in the mists of time (Dec 20) I remarked that the revised grammar which adds exception filters (`when`) also *removed* the syntactic requirement that a *general_catch_clause* if present must be the last one; leaving it as an in-text requirement only.

Being of the view that a *reference* grammar should be as precise as reasonable (while a compiler may use a more lenient grammar to avoid error messages and recovery) here is a version of the grammar which maintains the syntactic restriction:

```ANTLR
try_statement
    : 'try' block catch_clauses
    | 'try' block catch_clauses* finally_clause
    ;
catch_clauses
    : specific_catch_clause+
    | specific_catch_clause* general_catch_clause
    ;
specific_catch_clause
    : 'catch' exception_specifier exception_filter? block
    : 'catch' exception_filter block
    ;
exception_specifier
    : '(' type identifier? ')'
    ;
exception_filter
    : 'when' '(' boolean_expression ')'
    ;
general_catch_clause
    : 'catch' block
    ;
finally_clause
    : 'finally' block
    ;
```

Notes:

1. I left the origianal 2-alternative version of *try_statement* rather than replace the the equivalent 3-alternative version
2. I changed *expression* to *boolean_expression* in *exception_filter* as that matches the purpose of *boolean_expression*. A matching change to the list of places *boolean_expression* occurs would be needed to *§12.21 Boolean expressions*.


I’ll argue this version of the grammar is better as a reference grammar as it embodies all of the syntactic requirements.

(And if case someone asks, sorry I haven't come up with a series of short paras to replace the nested bullets, over to a wordsmith ;-))

2021-10-20 20:32 UTC, jskeet commented
Recording my vote here for option 2 described above - a succinct description.

2021-10-20 20:37 UTC, jskeet commented
Further actions:

- Grammar as per https://github.com/dotnet/csharpstandard/pull/2#issuecomment-922606602
- Option 2 as per https://github.com/dotnet/csharpstandard/pull/2#discussion_r542074435
- Raise issue to potentially change nested bullet list to paragraphs, as per https://github.com/dotnet/csharpstandard/pull/2#issuecomment-744665141

2021-10-20 20:41 UTC, jskeet approved these changes
Approved after the grammar and "option 2" changes have been applied.

2021-10-21 20:06 UTC, merged