Update v7 feature tracker
dotnet/csharpstandard pull request #448
Opened 2022-01-24 18:07 UTC by RexJaeschke

2022-01-24 18:35 UTC, KalleOlaviNiemitalo requested changes

2022-01-24 18:35 UTC, KalleOlaviNiemitalo commented on admin/v7-feature-tracker.md
> +Unlike with the V6 work, where we had separate and divergent V5 Ecma and MS specs, for V7, we started with a set of [MS proposals](https://github.com/dotnet/csharplang/tree/main/proposals), some of w
"branch", not "brach"

2022-01-28 21:15 UTC, BillWagner commented on admin/v7-feature-tracker.md
> +Unlike with the V6 work, where we had separate and divergent V5 Ecma and MS specs, for V7, we started with a set of [MS proposals](https://github.com/dotnet/csharplang/tree/main/proposals), some of w
```suggestion
Unlike with the V6 work, where we had separate and divergent V5 Ecma and MS specs, for V7, we started with a set of [MS proposals](https://github.com/dotnet/csharplang/tree/main/proposals), some of which were placeholders **for which text was never provided**. Where they existed, Rex took these proposals, wrote tests, looked at MS (and other) tutorial pages, and created a branch, and for most features, a corresponding (Draft) PR, with the edits he thought were needed. **It is quite possible that not everything in any given MS proposal was in fact implemented in that version, and it is also possible that things implemented in a version later on were not spec'd back into the proposal.** 
```

2022-01-28 21:15 UTC, BillWagner approved these changes
LGTM

2022-01-28 21:15 UTC, merged