Allow unsafe code in examples
dotnet/csharpstandard pull request #650
Opened 2022-10-26 14:11 UTC by jskeet

Towards #646.

2022-10-26 21:38 UTC, RexJaeschke requested changes
That's a nice, simple solution, Jon! However, now that we have template "code-in-main", we should enable unsafe mode there as well, no? I'm not sure we have any unsafe top-level examples, but I see no reason to preclude them.

2022-10-27 05:21 UTC, jskeet commented
Yes - didn't do it before as they were independent PRs, but I'll do it today.

2022-10-27 07:04 UTC, jskeet commented
Added now - PTAL and merge if you're happy.

2022-10-27 10:12 UTC, RexJaeschke approved these changes

2022-10-27 10:13 UTC, merged