Add support for using declarations and async using
dotnet/csharpstandard pull request #672
Opened 2022-11-24 15:47 UTC by RexJaeschke

There is some overlap between this PR and PR #606 in 12.14, "The using statement" that will require reconciliation when the second of these two PRs is merged. (PR 606 was spec'd first.)

2023-01-22 14:29 UTC, RexJaeschke commented
While adding example annotation, I discovered that the new example in statements.md involving `goto` does not compile:

> CS8649: A goto cannot jump to a location before a using declaration within the same block.

As this example was taken directly from the MS proposal, I've reported this to MS as issue  https://github.com/dotnet/docs/issues/33669.

Once I get a ruling on that, this example can be removed or tweaked, as appropriate.

2023-01-22 14:38 UTC, RexJaeschke commented
An example added by this PR needs SupportLocalVarDecl.cs to be added to additional-files, which can't be done until draft-v8 has been rebased.

```csharp
// SupportLocalVarDecl.cs
partial class Class1
{
    static void Main()
    {
        M();
    }
}
```

2023-09-26 14:21 UTC, BillWagner commented
rebased on 09/26/2023

2025-05-09 15:38 UTC, BillWagner commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
Copied from https://github.com/dotnet/csharpstandard/pull/606/files#r940394361

> Needs similar lowering rules for await using, particularly that the result of DisposeAsync is awaited rather than discarded.

2025-06-04 14:58 UTC, BillWagner commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
Added in latest commit.

2025-06-04 15:05 UTC, BillWagner commented
@jskeet @RexJaeschke I've reviewd this and made the additonal change discussed at our last meeting. Let's add it to the agenda for next week.

2025-06-08 21:28 UTC, Nigel-Ecma commented on standard/statements.md
> +A `goto` cannot jump to a location before a `using` declaration within the same block.
I think this is incorrect, the point is you cannot jump over using in either direction. Basing wording from the [LDM notes](https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/meetings/2018/LDM-2018-12-03.md#goto-and-using-declarations) I’ll offer:

```suggestion
When jumping to a label in a statement list which contains *local_variable_declaration*s involving `using`, there must not be any such declaration between the `goto` statement and the label.```

Apart from wordsmithing this needs x-ref to goto, and goto probably needs this restriction listed in its description as well.

Also surely this is an echo of a similar statement for `using (…) {…}`, so is it needed here at all given the equivalency defined above – this is just a shorthand.

2025-06-09 03:04 UTC, Nigel-Ecma requested changes
I think the approach here can be improved, in summary my concerns are:

1. Adding `using` into declarations (§13.6.2) has complicated that clause unnecessarily and introduced inconsistencies between “using declarations” and using statements (§13.14)
2. In §13.6.2 *explicitly_typed_ref_local_variable_declaration* are not included in “using declarations” but §13.14 does not exclude them – I suspect it should
3. §13.6.2 comments on the validity of goto jumps (incorrectly I believe as covered in a previous comment/suggestion) while §13.14 does not. However as “using declarations” are defined in terms of using statements the goto restrictions apply to both. That §13.14 omits goto is possibly because it is defined in terms of the try statement (§13.11) which does cover interaction with goto – but a Note in §13.14 would be helpful if that is the case.

I suggest the approach should be:

1. Remove all changes made to §13.6.2 (and children)
2. Introduce “using declarations” in §13.14 as a variant syntactic form of the using statement (which it is) defined by a direct mapping into one along with all the usual “equivalent to” usual wording. This could be covered in a sub cause (so the current §13.14 becomes §13.14.1 and the “using declarations” a short (as the the semantics are all ready covered) §13.14.2.
3. Modify §13.14(.1) to exclude *explicitly_typed_ref_local_variable_declaration* if it is indeed excluded
4. Modify §13.14(.1) to cover the usage of goto, possibly as just an x-ref to try (§13.11) or goto (§13.10.4)
5. Include any restrictions on using being in a case block as required.

I suggest this is a more logical approach, will remove the current inconsistencies, and remove the possibility of future inconsistencies in this area.

There is an obvious question of what are the grammar rules for the two kinds of using, first if *explicitly_typed_ref_local_variable_declaration* is indeed excluded we could introduce a convenience *non_ref_local_variable_declaration*

```ANTLR
non_ref_local_variable_declaration
    : implicitly_typed_local_variable_declaration
    | explicitly_typed_local_variable_declaration
    ;
```

Then the using statement’s *resource_acquisition* becomes:

```ANTLR
resource_acquisition
    : non_ref_local_variable_declaration
    | expression
    ;
```

Now a bit more speculative as I haven't checked the grammar properly, §13.14.2 would introduce *using_declaration*:

```ANTLR
using_declaration
    : await? 'using' non_ref_local_variable_declaration ';' statement_list
    ;
```

with this defined by mapping directly to the using statement:

```csharp
«await?» using ( «non_ref_local_variable_declaration» ) { «statement_list» }
```

The trailing *statement_list* should[*] “hoover up” the statements following the declaration, which could of course include another *using_declaration*… 

[*] Reminder: I haven't confirmed the grammar.

2025-06-09 17:53 UTC, jskeet commented
> The trailing statement_list should[*] “hoover up” the statements following the declaration, which could of course include another using_declaration…

One minor tweak - I think we'd want to make the statement list optional, as it's fine for a using declaration to be the last thing in a method, e.g.

```csharp
using System.IO;

class Test
{
    static void Main()
    {
        using var stream = new MemoryStream();
    }
}
```

2025-06-11 19:39 UTC, jnm2 commented on standard/statements.md
> +A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally
```suggestion
A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally` clause disposes of the resource. If a `null` resource is acquired, then no call to `Dispose` (or `DisposeAsync`) is made, and no exception is thrown. If the resource is of type `dynamic` it is dynamically converted through an implicit dynamic conversion ([§10.2.10](conversions.md#10210-implicit-dynamic-conversions)) to `IDisposable` (or `IAsyncDisposable`) during acquisition in order to ensure that the conversion is successful before the usage and disposal.
```

2025-06-11 19:40 UTC, BillWagner commented
Before merging this (and after merging #606), also review to include any normative language for `CancellationToken` usage and `ConfigureAwait`.

2025-06-11 19:42 UTC, jnm2 commented
`CancellationToken` would only apply to `await foreach`, and not `await using`.

2025-06-26 20:49 UTC, BillWagner commented
@jskeet @Nigel-Ecma @jnm2 @gafter @ericlippert 

I've made all the updates noted in our last meeting. This one is ready.

2025-07-01 21:24 UTC, Nigel-Ecma requested changes
I have not reviewed all the changes in this PR, as the couple of comments I’ve made state this is either missing a chunk of required information or I missing something…

2025-07-01 21:24 UTC, Nigel-Ecma commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. One parameter must be of the type `System.Threading.Tasks.CancellationToken` and be marked with the `System.Runtime.Co
This PR appears to have quite a chunk missing, and possibly excess baggage, or I'm missing something…

`CancellationToken` is introduced, and in an example for `EnumeratorCancellation` a value of this type is shown being used by calling `IsCancellationRequested`. The description of this type added to standard-library.md by #606 shows a type which is constructed from a boolean *constant* and I’ve found nothing in the Standard to cover how the value of `IsCancellationRequested` ever changes from this boolean constant supplied at construction – surely something is misisng here?

The description of `CancellationToken` in §C also includes a slew of members using the types `CancellationTokenRegistration` and `WaitHandle` which do not appear anywhere else in the Standard – excess baggage? Or are these methods fundamental to the value of `IsCancellationRequested` changing and so need to be described?

2025-07-01 21:24 UTC, Nigel-Ecma commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
The `MoveNextAsync` iterator specified in §C.3 has no optional parameter…

2025-07-02 07:39 UTC, jskeet reviewed
This is definitely getting there - please don't take my comments as a suggestion that we're not making progress :)

I suspect we won't get as far as having this ready to actually merge by the end of today's meeting, but we should probably focus on making sure we have clear remaining work items, with any contentious aspects resolved. (i.e. let's focus on semantics and anything that's missing rather spending time wordsmithing.)

2025-07-02 07:39 UTC, jskeet commented on standard/attributes.md
> +> static async IAsyncEnumerable<object> GetStringsAsync([EnumeratorCancellation]CancellationToken token)
```suggestion
> static async IAsyncEnumerable<object> GetStringsAsync([EnumeratorCancellation] CancellationToken token)
```

(I think there's usually a space before the type conventionally. I've only checked with the NotNullWhen example above though...)

2025-07-02 07:39 UTC, jskeet commented on standard/attributes.md
> +> *Example*: The method `GetStringsAsync()` is an asynchronous iterator. Before doing any work to retrieve the next value, it checks the cancellation token to determine if the iteration should be can
```suggestion
> *Example*: The method `GetStringsAsync()` is an asynchronous iterator. Before doing any work to retrieve the next value, it checks the cancellation token to determine if the iteration should be cancelled. If cancellation is requested, no further action is taken.
```

2025-07-02 07:39 UTC, jskeet commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
At the moment it's not obvious to me why an attribute is needed. The description of the example says "Before doing any work to retrieve the next value, it checks the cancellation token to determine if the iteration should be cancelled" - that's part of the code in the method itself, but are we saying the compiler injects a check as well?

It may well be that reading 15.15 again will make this obvious, but I think we should expand the example anyway.

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +An async function ([§15.14](classes.md#1514-async-functions)) implemented using an iterator block ([§13.3](statements.md#133-blocks)) is called an ***asynchronous iterator***. An asynchronous iterato
```suggestion
An async function ([§15.14](classes.md#1514-async-functions)) implemented using an iterator block ([§13.3](statements.md#133-blocks)) is called an ***asynchronous iterator***. An asynchronous iterator block may be used as the body of a function as long as the return type of the corresponding function is the asynchronous enumerator interface ([§15.15.2](classes.md#15152-enumerator-interfaces)) or the asynchronous enumerable interface ([§15.15.3](classes.md#15153-enumerable-interfaces)).
```

There's only one interface in for each of enumerator/enumerable when it comes to async, right? I guess generics make this trickier... an alternative would "is an asynchronous enumerator interface or an asynchronous enumerable interface"...

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. One parameter must be of the type `System.Threading.Tasks.CancellationToken` and be marked with the `System.Runtime.Co
Definitely worth discussing - I haven't looked at annex C yet, but I think more description about the cancellation token would be useful here. (It's not clear why the attribute is needed - if I have a parameter *without* that attribute, what difference would that make?)

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +An async function ([§15.14](classes.md#1514-async-functions)) implemented using an iterator block ([§13.3](statements.md#133-blocks)) is called an ***asynchronous iterator***. An asynchronous iterato
(I see later we refer to "the asynchronous enumerable interface" so I think my original suggestion is approprpiate.)

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +> *Note*: `MoveNextAsync` can be suspended if it contains an `await` expression that awaits a task type that hasn't completed. *end note*
Should this be "is suspended"? And should it be normative? (It feels to me like without this, the behavior isn't fully described.)

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +A synchronous enumerable object implements `IEnumerable` and `IEnumerable<T>` or `IAsyncEnumerable<T>`, where `T` is the yield type of the iterator. Its `GetEnumerator` returns an enumerator object (
```suggestion
A synchronous enumerable object implements `IEnumerable` and `IEnumerable<T>` or `IAsyncEnumerable<T>`, where `T` is the yield type of the iterator. Its `GetEnumerator` method returns an enumerator object (§15.15.5). An async enumerable object implements `IAsyncEnumerable<T>` where `T` is the yield type of the iterator. Its `GetAsyncEnumerator` method returns an asynchronous enumerator object  (§15.15.5).
```

2025-07-02 07:39 UTC, jskeet commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
Indeed - not quite sure how we ended up in that state.

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +The determination is similar for the synchronous and asynchronous versions. Different interfaces with different methods and return types distinguish the synchronous and asynchronous versions. The gen
I think we possibly need a sentence or two to explain what the identifiers within chevrons mean. (I get the drift, but we should probably be explicit.)

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +The determination is similar for the synchronous and asynchronous versions. Different interfaces with different methods and return types distinguish the synchronous and asynchronous versions. The gen
(Referring forward to 13.9.5.2 and 13.9.5.3 and saying those specify the actual names for each case would probably be sufficient.)

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +- If the type `X` of *expression* is an array type then there is an implicit reference conversion from X to the `IEnumerable` interface (since `System.Array` implements this interface). The collectio
```suggestion
- If the type `X` of *expression* is an array type then there is an implicit reference conversion from `X` to the `IEnumerable` interface (since `System.Array` implements this interface). The collection type is the `IEnumerable` interface, the enumerator type is the `IEnumerator` interface and the iteration type is the element type of the array type `X`. (sync)
```

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +- If the type `X` of *expression* is an array type then there is an implicit reference conversion from X to the `IEnumerable` interface (since `System.Array` implements this interface). The collectio
Are the "sync" and "sync only" bits in brackets still needed? This is already in a sync-only section. I suspect they're vestigial from when we were trying to unify things.

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +It is an error for the ***iteration type*** of an `await foreach` to be a reference variable (§9.7).
```suggestion
It is an error for the ***iteration type*** of an `await foreach` statement to be a reference variable (§9.7).
```

(This feels better to me, and is consistent with the next line. It's not consistent with the first line of the section, admittedly.)

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +An `await foreach` statement of the form
In the equivalent code below, a cancellation token is never passed to MoveNextAsync. I can't remember the details (is this where the attribute comes in - is it passed in automatically?) but I'm pretty sure a change is needed here.

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +A ***resource*** is either a class or non-ref struct that implements either or both of the `System.IDisposable` or `System.`IAsync`Disposable` interfaces, which includes a single parameterless method
```suggestion
A ***resource*** is either a class or non-ref struct that implements either or both of the `System.IDisposable` or `System.IAsyncDisposable` interfaces, which includes a single parameterless method named `Dispose` and/or `DisposeAsync`; or a ref struct that includes a method named `Dispose` having the same signature as that declared by `System.IDisposable`. Code that is using a resource can call `Dispose` or `DisposeAsync` to indicate that the resource is no longer needed.
```

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally
```suggestion
A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally` clause disposes of the resource. If a `null` resource is acquired, then no call to `Dispose` (or `DisposeAsync`) is made, and no exception is thrown. If the resource is of type `dynamic` it is dynamically converted through an implicit dynamic conversion ([§10.2.10](conversions.md#10210-implicit-dynamic-conversions)) to `IDisposable` (or `IAsyncDisposable`) during acquisition in order to ensure that the conversion is successful before the usage and disposal.
```

2025-07-02 07:39 UTC, jskeet commented on standard/statements.md
> +has the same possible expansions. In this case `ResourceType` is implicitly the compile-time type of the *expression*, if it has one. Otherwise, the interface `IDisposable` itself is used as the `Res
Surely the expression *must* have a compile-time type, otherwise it can't conform with the earlier requirement of:

> If the form of *resource_acquisition* is *expression* then this expression shall have a resource type. If `await` is present, the resource type shall implement `System.IAsyncDisposable`.

2025-07-02 18:59 UTC, BillWagner reviewed
Add comments where I've made later updates.

2025-07-02 18:59 UTC, BillWagner commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
Good catch. I misread the section of the speclet on [cancellation](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-streams.md#cancellation). The agreed solution is to pass the cancellation token to `GetEnumeratorAsync`, and not add it to `MoveNextAsync`.

I did add the default parameter to the `GetEnumeratorAsync()` method.

2025-07-02 18:59 UTC, BillWagner commented on standard/classes.md
> +> *Note*: `MoveNextAsync` can be suspended if it contains an `await` expression that awaits a task type that hasn't completed. *end note*
I didn't think it needed to be normative here. The reason is that `MoveNextAsync` has a return type that is a task type. Therefore, the method can have the `async` modifier. Therefore, it can have `await` expressions, and can be suspended. The returned task would be in the "running" state, as with any async method.

2025-07-02 18:59 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
Added a couple clarifying sentences. Probably still more work needed.

(For example, what if the attribute is applied to a type that isn't a cancellation token?

2025-07-02 18:59 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. One parameter must be of the type `System.Threading.Tasks.CancellationToken` and be marked with the `System.Runtime.Co
We should discuss this. The conventional approach is to use the [`CancellationTokenSource`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource?view=net-9.0) type to create the token, and the client code modifies the state through its `Cancel*` methods.

From a language perspective, the `CanellationTokenSource` isn't special, it's just one way to manage a cancellation token. Does it need to be normative? Should we add an example to show this convention as informative?

2025-07-02 18:59 UTC, BillWagner commented on standard/statements.md
> +The determination is similar for the synchronous and asynchronous versions. Different interfaces with different methods and return types distinguish the synchronous and asynchronous versions. The gen
Added in the upcoming commit.

2025-07-02 18:59 UTC, BillWagner commented on standard/statements.md
> +An `await foreach` statement of the form
I won't get to it before the meeting, but I'll add a second code sample following the meeting.

2025-07-02 20:33 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. One parameter must be of the type `System.Threading.Tasks.CancellationToken` and be marked with the `System.Runtime.Co
Decision from the meeting:

Add one (or more) informative example that shows end to end how an async iterator supports cancel.

There should be some normative text on *how* the struct value for the `CancellationToken` changes in the operations.

2025-07-02 20:35 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
The attribute is used for the `.WithCancellation` extension method. 

The compiler must wrap the original async iterator in a generated class that does enables the cancellation in the wrapper, not the wrapped state machine.

2025-07-02 20:36 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. One parameter must be of the type `System.Threading.Tasks.CancellationToken` and be marked with the `System.Runtime.Co
Discussed. We'd like some normative text to introduce the concept, and then an example with CancellationTokenSource, but leaving "how cancellation tokens are cancelled" as implementation defined/specific. (We don't want to standardize CancellationTokenSource.)

2025-07-02 20:40 UTC, jskeet commented on standard/classes.md
> +> *Note*: `MoveNextAsync` can be suspended if it contains an `await` expression that awaits a task type that hasn't completed. *end note*
```suggestion
> *Note*: `MoveNextAsync` is suspended if it evaluates an `await` expression that awaits a task type that hasn't completed. *end note*
```

2025-07-02 20:40 UTC, jskeet commented on standard/classes.md
> +> *Note*: `MoveNextAsync` can be suspended if it contains an `await` expression that awaits a task type that hasn't completed. *end note*
Added a suggestion for the "is" part, resolving for the normative side.

2025-07-02 21:10 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
The attribute causes the body of the method to receive a cancellation token that is not necessarily the one passed to the method by the method caller. Instead, the body of the method receives two cancellation tokens [stitched together](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.createlinkedtokensource): one, the one actually passed by the caller of the async iterator method; two, the one passed to GetAsyncEnumerator.

```cs
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static CancellationTokenSource cancellationTokenSource1 = new CancellationTokenSource();
    static CancellationTokenSource cancellationTokenSource2 = new CancellationTokenSource();

    public static async Task Main()
    {
        await using var enumerator = IterateAsync(cancellationTokenSource1.Token).GetAsyncEnumerator(cancellationTokenSource2.Token);

        while (await enumerator.MoveNextAsync()) { }
    }

    public static async IAsyncEnumerable<int> IterateAsync([EnumeratorCancellation] CancellationToken cancellationToken)
    {
        Console.WriteLine(cancellationToken.Equals(cancellationTokenSource1.Token)); // False
        Console.WriteLine(cancellationToken.Equals(cancellationTokenSource2.Token)); // False
        yield break;
    }
}
```

The `WithCancellation` extension method returns a wrapper that passes a cancellation token to GetAsyncEnumerator. This example shows the more likely consumption pattern that results in a linked cancellation token:

```cs
    public static async Task Main()
    {
        // Notice what happens if you pass CancellationToken.None for either one of these!
        await foreach (var _ in IterateAsync(cancellationTokenSource1.Token).WithCancellation(cancellationTokenSource2.Token))
        {
        }
    }
```

See [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRhQG4BYAKGz3wDoAlAVwDsAXASwFsZqBhCdgB1YAbGFADKogG6swMAM6kKuAtQAqAC1gBDACatGAc0WUCAVkXkMAZjwAmHNxwBvcjjd4bBJHgAcOAJIAgnIAnoxgAKKM9JxQWsAiADz6zAB8OACywWFgABSu7oUA2lExolrM0Nxa4TBCQhWsEIwAug41svWNzaoQANYwjDhgHXUNbD39g/gANAWFbtW1XROMvQNDI8vjTWtTjLYAlPPOJ4UYAJx4SNQAInVaIbn4WDPDoyu769OHigvul2udweTxeby2nR2kw2Rz+/yo+BwwG0fThbgAvuR0UA)'s decompilation of the `GetAsyncEnumerator` method for the logic.

> (For example, what if the attribute is applied to a type that isn't a cancellation token?)

Only a warning:

> warning CS8424: The EnumeratorCancellationAttribute applied to parameter 'cancellationToken' will have no effect. The attribute is only effective on a parameter of type CancellationToken in an async-iterator method returning IAsyncEnumerable

2025-07-02 21:14 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
We also have:

> error CS8426: The attribute [EnumeratorCancellation] cannot be used on multiple parameters

2025-07-02 21:24 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
It's the other way around. The compiler-generated iterator actually _receives_ one of the inputs to is parameter by someone calling its implementation of `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)`.

Also, the iterator does not respect the token's state in MoveNextAsync. The token is only respected if the user explicitly uses the token in the body of their iterator method. (Verified both by example and by looking at generated code.)

```suggestion
Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). When the body of async iterator method accesses this parameter, it will receive a combination of two cancellation tokens: the token which was actually passed to the method, and the token passed to the `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)` implementation on the generated iterator. The combined token will be canceled if either of the two source tokens are canceled.
```

2025-07-02 21:24 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
It's the other way around. The compiler-generated iterator actually _receives_ one of the inputs to is parameter by someone calling its implementation of `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)`.

Also, the iterator does not respect the token's state in MoveNextAsync. The token is only respected if the user explicitly uses the token in the body of their iterator method. (Verified both by example and by looking at generated code.)

```suggestion
Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). When the body of async iterator method accesses this parameter, it will receive a combination of two cancellation tokens: the token which was actually passed to the method, and the token passed to the `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)` implementation on the generated iterator. The combined token will be canceled if either of the two source tokens are canceled.
```

2025-07-02 21:29 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
Yes, without calling either .WithCancellation (and explaining what it is?) or calling .GetAsyncEnumerator, the example doesn't demonstrate `[EnumeratorCancellation]`.

2025-07-02 21:38 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
And I bet @Nigel-Ecma is going to really love me throwing out the terms "token" and "canceled" without defining them 😁
But I do feel it's important to explain the behavior of the combined token, since that is the reason a user would want to depend on the feature.

2025-07-09 15:26 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
I'll take the suggestion because it's a good starting point. I'll continue editing and clarify terms, or use terms already defined.

2025-07-09 17:48 UTC, BillWagner commented on standard/statements.md
> +has the same possible expansions. In this case `ResourceType` is implicitly the compile-time type of the *expression*, if it has one. Otherwise, the interface `IDisposable` itself is used as the `Res
updated in next commit.

2025-07-09 17:48 UTC, BillWagner commented on standard/statements.md
> +An `await foreach` statement of the form
I'd had this wrong. The cancellation token (or combined token) is passed to `GetAsyncEnumerator`. Adding a second sample that includes the `WithCancellation` extension method.

2025-07-09 17:48 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
@jnm2 Can you post the example, or a link to a lab.razor.fyi example?

2025-07-09 18:27 UTC, jnm2 commented on standard/statements.md
> +An `await foreach` statement of the form
A combined token isn't passed *to* GetAsyncEnumerator, but rather a second token is passed to it, and GetAsyncEnumerator then performs the combining between that one and the one that was passed to the async iterator method.

2025-07-10 18:01 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
This should be addressed in an upcoming commit.

2025-07-10 19:46 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15).
I did add an additional example, and some explanations. I'm concerned that the additions (especially the examples) are more "documenting an implementation" than should be in the standard. 

I'd like to mark this discussion for the meeting later this month.

2025-07-10 21:43 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The compiler generated iterator passes the argument for this parameter to the `IAsyncEnumerable<T>.
Sure thing! A runnable demo is at <https://github.com/dotnet/csharpstandard/pull/672#discussion_r2180979017> with a SharpLab link. I simplified it and moved it to lab.razor.fyi: [link](https://lab.razor.fyi/#dY_BSsRADIaxeNA5iU-Q4woy6LkiSBVREMTtSRFMs6GGTmeWyVQpss_lxZNP4sG7byDS3UV00f8S8vH_4Y_5yIy5jKGO2FrS7besU_E1jHtN3NoiOMeUJHi1p-w5CuXml-Oq80latkVop-I4jjk-CLGu2Mr7yDgRX__HbYnaaG7MtKucEJBDVSjgyQAALKEmTEKA2nuCs6NhnPiu5YiV4wPx6RAu5nQ0Tw26WRpSiAV6YudweOcWfm5laNgDrZKd-ZVFg0H4iJJgKGqP2WE_2t_b_SOVfwd6YTeBKjI2Czgzs_OM9Hpz4-X59f2Tt9bv1r4A)

You can see how the state machine implements GetAsyncEnumerator. GetAsyncEnumerator receives a second token, and then combines the two tokens if both are not `CancellationToken.None`:

<details>

```cs
[DebuggerHidden]
IAsyncEnumerator<int> IAsyncEnumerable<int>.GetAsyncEnumerator(CancellationToken cancellationToken = default(CancellationToken))
{
    <MAsync>d__0 <MAsync>d__;
    if (<>1__state == -2 && <>l__initialThreadId == Environment.CurrentManagedThreadId)
    {
        <>1__state = -3;
        <>t__builder = AsyncIteratorMethodBuilder.Create();
        <>w__disposeMode = false;
        <MAsync>d__ = this;
    }
    else
    {
        <MAsync>d__ = new <MAsync>d__0(-3);
    }
    if (<>3__cancellationToken.Equals(default(CancellationToken)))
    {
        <MAsync>d__.cancellationToken = cancellationToken;
    }
    else if (cancellationToken.Equals(<>3__cancellationToken) || cancellationToken.Equals(default(CancellationToken)))
    {
        <MAsync>d__.cancellationToken = <>3__cancellationToken;
    }
    else
    {
        <>x__combinedTokens = CancellationTokenSource.CreateLinkedTokenSource(<>3__cancellationToken, cancellationToken);
        <MAsync>d__.cancellationToken = <>x__combinedTokens.Token;
    }
    return <MAsync>d__;
}
```

</details>

2025-07-16 20:59 UTC, BillWagner commented
@jskeet @Nigel-Ecma @RexJaeschke @ericlippert @gafter @jnm2 

This is ready for discussion. I admit I stopped a bit short of the full details on cancellation. The more I dug into it (with @jnm2 's examples) the more it was becoming a description of the implementation, not rules and requirements. Any suggestion on wording to require the correct rules without specifying one specific implementation are welcome.

2025-07-17 10:57 UTC, RexJaeschke commented on standard/attributes.md
> +### §enumerator-cancellation The EnumeratorCancellation attribute
Once we've merged this, I'll do the following:

1. Add a pointer to this attribute to the bullet list in 22.5.1, "General," where we provide a summary of Reserved attributes.
2. Convert the hard-coded links to relative ones.

2025-07-17 16:07 UTC, RexJaeschke commented on standard/standard-library.md
> +    public class CancellationTokenSource : IDisposable
This type is only used in an (informative) example (in attributes.md), and in the following normative sentence (in classes.md):

>One way to implement this is to use the `CreateLinkedTokenSource` method of the `CancellationTokenSource` class.

As such, the large member set in this type declaration seems overkill.

I see the following possibilities:

1. We declare this type and *only* that one member mentioned in the normative text. (The rest is implementation detail.)
2. We remove the whole type, remove the normative "suggestion" sentence, and change the example.

2025-07-29 10:14 UTC, jskeet reviewed
Lots of comments - not sure whether we'll get to "ready to merge" in the meeting, but getting much closer - thanks for all your work on this, @BillWagner.

2025-07-29 10:14 UTC, jskeet commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). When the body of async iterator method accesses this parameter, it will receive a combination of tw
```suggestion
Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). When the body of async iterator method accesses this parameter, it will receive a combination of two cancellation tokens: the token which was actually passed to the method, and the token passed to the `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)` implementation on the generated iterator. The combined token will be canceled if either of the two source tokens are canceled.
```

(Or go in the other direction, but let's be consistent.)

2025-07-29 10:14 UTC, jskeet commented on standard/attributes.md
> +> *Example*: The method `GetStringsAsync()` is an asynchronous iterator. Before doing any work to retrieve the next value, it checks the cancellation token to determine if the iteration should be can
```suggestion
> *Example*: The method `GetStringsAsync()` is an asynchronous iterator. Before doing any work to retrieve the next value, it checks the cancellation token to determine if the iteration should be canceled. If cancellation is requested, no further action is taken.
```

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use the `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has
```suggestion
An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use the `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has a parameter of the type `System.Threading.Tasks.CancellationToken` that is marked with the `System.Runtime.CompilerServices.EnumeratorCancellation` attribute (§enumerator-cancellation), the compiler may create an aggregate token that signals a canceled request when any of the tokens indicates that cancel is requested.
```

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +An asynchronous enumerable object provides an implementation of the `GetAsyncEnumerator` method of the `IAsyncEnumerable<T>` interface. This method returns an available asynchronous enumerator object
```suggestion
An asynchronous enumerable object provides an implementation of the `GetAsyncEnumerator` method of the `IAsyncEnumerable<T>` interface. This method returns an available asynchronous enumerator object. The enumerator object is initialized with the argument values and instance value saved when the enumerable object was initialized, including the optional cancellation token, but otherwise the enumerator object functions as described in [§15.15.5](classes.md#15155-enumerator-objects). An asynchronous iterator method can mark one parameter as the cancellation token using the `EnumeratorCancellation` attribute (§enumerator-cancellation). An implementation shall provide a mechanism to combine cancellation tokens such that an asynchronous iterator is canceled when either cancellation token (the argument to `GetAsyncEnumerator` or the argument attributed with `EnumeratorCancellation`) requests cancellation. One way to implement this is to use the `CreateLinkedTokenSource` method of the `CancellationTokenSource` class.
```

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use the `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has
```suggestion
An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has such a parameter, and that parameter is marked with the `System.Runtime.CompilerServices.EnumeratorCancellation` attribute (§enumerator-cancellation), the compiler may create an aggregate token that signals a canceled request when any of the tokens indicates that cancellation is requested.
```

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use the `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has
The "may" here is interesting... can a conformant compiler ignore EnumeratorCancellation?

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
Unresolved, as I think we need to change this text. (I'm currently too sleepy to determine whether we just need to remove the paragraph, or move it to where we talk about GetEnumeratorAsync.)

2025-07-29 10:14 UTC, jskeet commented on standard/attributes.md
> +> await foreach (string number in GetStringsAsync(sourceOne.Token).WithCancellation(sourceTwo.Token))
This may become obvious later but in case I forget: are we standardizing `WithCancellation`?

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +An asynchronous enumerable object provides an implementation of the `GetAsyncEnumerator` method of the `IAsyncEnumerable<T>` interface. This method returns an available asynchronous enumerator object
The "**shall** [...] such that an asyncronous iterator **is** cancelled" here seems to conflict with the "may" I mentioned earlier.

2025-07-29 10:14 UTC, jskeet commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
I *think* we just remove it, as new line 5639 seems to cover it.

2025-07-29 10:14 UTC, jskeet commented on standard/standard-library.md
> +        IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken token=default);
Nit - do we not want spaces around the `=`?

2025-07-29 10:14 UTC, jskeet commented on standard/standard-library.md
> +    public class CancellationTokenSource : IDisposable
My vote is to remove it entirely from normative text, but keep it in the example with a fairly general comment to explain it.

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +- If the type `X` of *expression* is an array type then there is an implicit reference conversion from `X` to the `IEnumerable` interface (since `System.Array` implements this interface). The collect
In 17.2.3 we already say:

> A single-dimensional array `T[]` implements the interface `System.Collections.Generic.IList<T>` and its base interfaces.

So can't we say the collection type is `IEnumerable<A>` and the interface type is `IEnumerator<A>` where `A` is the element type of the array type `X`?

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +If the process in §13.9.5.1 completes without produce a single collection type, enumerator type, and iteration type, the following steps are taken:
```suggestion
If the process in §13.9.5.1 completes without producing a single collection type, enumerator type, and iteration type, the following steps are taken:
```

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +- Otherwise, if there is an implicit conversion from `X` to the `System.Collections.IEnumerable` interface, then the collection type is this interface, the enumerator type is the interface `System.Co
```suggestion
- If there is an implicit conversion from `X` to the `System.Collections.IEnumerable` interface, then the collection type is this interface, the enumerator type is the interface `System.Collections.IEnumerator`, and the iteration type is `object`.
```

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +- Otherwise, if there is an implicit conversion from `X` to the `System.Collections.IEnumerable` interface, then the collection type is this interface, the enumerator type is the interface `System.Co
("Otherwise" at the start of a list is weird, and this is already in a sync-only section.)

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +TODO:  Add second example that includes `.WithCancellation`
Adding a comment here to highlight that we still have a TODO.

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally
Not sure about "a null resource" - perhaps "if the result of the acquisition expression is a null reference"? (Further wordsmithing required, but I didn't want to spend too much time on it if everyone else is happy as it's already in the PR...)

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +    ResourceType resource = «expression»;
I wonder whether `ResourceType` ought to be in chevrons here and above? (It's a bit of a third case - it's not "something from the original code" nor is it "fixed text"...)

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +```csharp
This duplication feels odd to me. Can we not just amend the previous paragraph to end with "The corresponding expansion is"

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +When `ResourceType` is a reference type that implements `IAsyncDisposable`. Other expansions for `await using` perform similar substitutions from the synchronous `Dispose` method to the asynchronous
If this is meant to be a condition of the expansion, I think it would definitely be better *before* the expansion. (At the moment it's written as if it's a standalone sentence, but it doesn't really work like that.)

2025-07-29 10:14 UTC, jskeet commented on standard/statements.md
> +The lifetime of the variables declared in a *local_variable_declaration* extends to the end of the scope in which they are declared. Those variables are then disposed in the reverse order in which th
Should *local_variable_declaration* here be *non_ref_local_variable_declaration*?

2025-07-30 07:05 UTC, Nigel-Ecma requested changes
I haven’t had time to review all the changes but something did jump out. We seemed to have followed the suggestion in this [comment](https://github.com/dotnet/csharpstandard/pull/672#pullrequestreview-2908818087) apart from the first bullet – remove the changes made to §13.6.2 & siblings. This has resulted in “using declarations” being defined in both §13.6.2 and §using-declarations (subclause of §13.14). That needs to be fixed.

I can’t comment on the other changes yet.

2025-07-30 17:58 UTC, BillWagner commented
> I haven’t had time to review all the changes but something did jump out. We seemed to have followed the suggestion in this [comment](https://github.com/dotnet/csharpstandard/pull/672#pullrequestreview-2908818087) apart from the first bullet – remove the changes made to §13.6.2 & siblings. This has resulted in “using declarations” being defined in both §13.6.2 and §using-declarations (subclause of §13.14). That needs to be fixed.
> 
> I can’t comment on the other changes yet.

Updated in the most recent commit.

2025-07-30 19:40 UTC, jskeet commented
Discussion around cancellation:

- Keep EnumeratorCancellationAttribute; describe it in terms of "the cancellation token provided by the caller and the one provided in GetAsyncEnumerator" and that if either is cancelled, the result is cancelled
- Make both WithCancellation and CancellationTokenSource informative-only

@BillWagner to implement these, @Nigel-Ecma and @jskeet to review, potentially merge between meetings.

2025-08-08 18:44 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use the `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has
edited following suggestion.

2025-08-08 20:18 UTC, BillWagner reviewed
Finished post-meeting edits.

2025-08-08 20:18 UTC, BillWagner commented on standard/attributes.md
> +> await foreach (string number in GetStringsAsync(sourceOne.Token).WithCancellation(sourceTwo.Token))
Decision from July 30 meeting: We'll use `WithCancellation` in examples, but not in normative text.

2025-08-08 20:18 UTC, BillWagner commented on standard/classes.md
> +The `MoveNextAsync` method includes an optional `CancellationToken` parameter. The argument is the token marked with the `EnumeratorCancellation` attribute of the iterator (§15.15.1).
removed after verifying that line 5639 does cover it. (now 5637).

2025-08-08 20:18 UTC, BillWagner commented on standard/standard-library.md
> +    public class CancellationTokenSource : IDisposable
Removed and trimmed CancellationToken to the members referenced in normative text.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +- If the type `X` of *expression* is an array type then there is an implicit reference conversion from `X` to the `IEnumerable` interface (since `System.Array` implements this interface). The collect
Updated per comment.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +When `ResourceType` is a reference type that implements `IAsyncDisposable`. Other expansions for `await using` perform similar substitutions from the synchronous `Dispose` method to the asynchronous
Moved above the expansions.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +    ResourceType resource = «expression»;
updated.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +A `using` statement is translated into three parts: acquisition, usage, and disposal. Usage of the resource is implicitly enclosed in a `try` statement that includes a `finally` clause. This `finally
Updated and a bit of wordsmithing.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +TODO:  Add second example that includes `.WithCancellation`
My notes indicate that we aren't adding this expansion.

2025-08-08 20:18 UTC, BillWagner commented on standard/statements.md
> +In either expansion, an implementation may determine that a `CancellationToken` should be passed to the `GetAsyncEnumerator` method. This may include a combined token as shown in the example in §enum
Note for @jskeet and @Nigel-Ecma 

This still feels a bit hand-wavy to me. Any suggestions are welcome.

2025-08-08 20:18 UTC, BillWagner commented on standard/attributes.md
> +### §enumerator-cancellation The EnumeratorCancellation attribute
@RexJaeschke I think this has all been addressed? Or do these still need to be updated after merging this PR?

2025-08-08 20:20 UTC, BillWagner commented
@Nigel-Ecma @jskeet This is now ready for another review. I addressed all the comments from the last meeting and resolved conversations where I've addressed the comment. I added one review comment for both of you to look at. I'd like this to be better, but I'm not sure how far to keep it "standard", and not "document one known implementation".

2025-08-15 01:51 UTC, Nigel-Ecma requested changes
Various comments; mainly regarding presentation, typos, etc.; across the PR.

The big issue is raised in this [comment](https://github.com/dotnet/csharpstandard/pull/672#issuecomment-3169190784):

> @Nigel-Ecma @jskeet This is now ready for another review. I addressed all the comments from the last meeting and resolved conversations where I've addressed the comment. I added one review comment for both of you to look at. I'd like this to be better, but I'm not sure how far to keep it "standard", and not "document one known implementation".

This PR adds `CancellationToken` to the required types, defining it as:

> ```csharp
> public readonly struct CancellationToken : IEquatable<System.Threading.CancellationToken>
> {
> }
> ```

and adds `EnumeratorCancellationAttribute` in §enumerator-cancellation (`attributes..md`). It’s declaration is missing in §C.3, it would be:

> ```csharp
> [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited=false)]
> public sealed class EnumeratorCancellationAttribute : Attribute
> ```

All the other types, constructors, properties and methods mentioned (e.g. `IsCancellationRequested`, `Cancel`) are all informative. 

*This leaves the cancellation mechanism without __normative__ definition*.

We need 

To define it normatively we need the types and members:

> ```csharp
> public class System.Threading.CancellationTokenSource : IDisposable
> {
>    public CancellationTokenSource();
>    public System.Threading.CancellationToken Token { get; }
>    public void Cancel();
>    // optional, see below
>    public static CancellationTokenSource CreateLinkedTokenSource
>                                          (System.Threading.CancellationToken token1,
>                                           System.Threading.CancellationToken token2
>                                          );
> }
>
> public readonly struct System.Threading.CancellationToken : IEquatable<System.Threading.CancellationToken>
> {
>    public bool IsCancellationRequested { get; }
> }
>
> [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited=false)]
> public sealed class EnumeratorCancellationAttribute : Attribute
> ```

This is the minimum set to describe the mechanism based on polling (testing `IsCancellationRequested`):

- Constructor `CancellationTokenSource()` to create a token source
- `Token` to obtain the token to pass to `GetAsyncEnumerator` *et al*
- `Cancel` to request cancellation
- `IsCancellationRequested` to check for requested cancellation
- `EnumeratorCancellationAttribute` to mark which parameter should receive the “combined” cancellation token

How to describe cancelling?

> Just using `yeild break` fits well enough with the polling model. There is no need to include the option of throwing `OperationCanceledException`, but no real harm either as it is already in §C.3

How to describe token combination?

> The choice here is between a bit of hand-waving “the implementation will combine”, or
going a bit further:
>
> - Include `CreateLinkedTokenSource` as a required method; and
> - Say something like “The tokens shall be combined into a single token as if by `CreateLinkedTokenSource` and its `Token` property”
>
> I would probably go with the latter, including `CreateLinkedTokenSource` is easy enough and “as if by” prevents requiring an implementation to use the method.

Things that **don’t** need to be included:

- Why the design uses two types, `CancellationTokenSource` & `CancellationToken`
- Why one is a class and the other a struct
- How tokens are combined – down to the implementation
- Timed cancellation, observers,  waiting for cancellation, *et al* – all implementation specific extras.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +The determination is similar for the synchronous and asynchronous versions. Different interfaces with different methods and return types distinguish the synchronous and asynchronous versions. The gen
"The text with «…” sounds wrong to me, maybe something along the lines of:

```suggestion
The determination is similar for the synchronous and asynchronous versions. Different interfaces with different methods and return types distinguish the synchronous and asynchronous versions. The general process proceeds as follows. Names within '«' and '»' are placeholders for the actual names for synchronous and asynchronous iterators; these are given in §13.9.5.2 and §13.9.5.3 for synchronous and asynchronous iterators respectively.
```

I think I’d prefer a table of substitutions here rather than later, but maybe that is just me!

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +  - Member lookup is performed on `E` with the identifier `Current` and no type arguments. If the member lookup produces no match, the result is an error, or the result is anything except a public in
The tense changes here, earlier bullets “Perform…” (a command), from here “… is performed” (descriptive); better to be consistent.

*(This error originated with some of the source material)*

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +  - Perform member lookup on the type `X` with identifier «GetEnumerator» and no type arguments. If the member lookup does not produce a match, or it produces an ambiguity, or produces a match that i
I think using numbered rather than bulleted points could help here, so “check for an enumerable interface as described below” could be something like “continue at step 2” (the current step is 1.1).

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +An implementation is permitted to implement a given *foreach_statement* differently; e.g., for performance reasons, as long as the behavior is consistent with this expansion.
This is now out of place, the expansions come in the following clauses

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +The types allowed for «GetEnumerator», «MoveNext», «IEnumerable»\<T>, «IEnumerator»\<T>, and any other distinctions are detailed in [§13.9.5.2](statements.md#13952-synchronous-foreach) for a synchron
This is a small variation of the text before the above steps, better to combine both into the one above and drop this one.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +  - Overload resolution is performed on the method group with an empty argument list. If overload resolution results in no applicable methods, results in an ambiguity, or results in a single best met
An editing snafu here, we all (well I do as well) suffer from these ;-( I’ll offer:

```suggestion
  - Overload resolution is performed on the method group with an empty argument list. If overload resolution results in: no applicable methods; an ambiguity; or a single best method but that method is either static, or not public, or its return type is not an allowed return type; then an error shall be produced and no further steps taken.
```

The tense may be wrong (shall be)?

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +In either expansion, an implementation may determine that a `CancellationToken` should be passed to the `GetAsyncEnumerator` method. This may include a combined token as shown in the example in §enum
If the “In either expansion” is referring to the sync & async versions then the names (`GetAsyncEnumerator` *et al*)in this para are wrong.

It is certainly “hand-wavy” with “an implementation may determine”, TODO – come back here before submitting review!

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +> *Note:* A `ref struct` type cannot be the resource type for a `using` statement with the `await` modifier because `ref struct` types cannot implement interfaces. *end note*
This seems an odd note to me. In the synchronous case we have “a ref struct that includes a method named `Dispose` having the same signature as that declared by `System.IDisposable`” – the inability to implement an interface is no impediment in this case, so stating it is in the asynchronous case just seems, I’ll say “odd”.

Is this more a specific implementation limitation that should not be Standardised? Or is there a semantic reason for the limitation, and if so should that not be documented?

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +For ref struct resources, the only possible expansion is
The first expansion “is semantically equivalent to” (1926), the second (1944) and this one are just “is” and then on 2002 we have “An implementation is permitted to implement a given *using_statement* differently” – which is the point of saying “semantically equivalent to”.

Repeating “semantically equivalent to” on 1944 & here, and dropping 2002, would be more consistent – if desired a *Note* could replace 2002 to emphasise the purpose of “semantically equivalent to” and even include the example suggestion of why an implementation might do it differently.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
>  An implementation is permitted to implement a given *using_statement* differently, e.g., for performance reasons, as long as the behavior is consistent with the above expansion.
See comment on 1984 above

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
*(I’ve come back here, earlier comments below still use “expansion” – read them in the light of this comment)*

These are not “expansions” *per se* if the expression is “semantically equivalent to”. But what do we call them? *Meanings* maybe? If that is chosen we would here have:

```suggestion
has one of three possible meanings. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5](classes.md#1525-type-parameter-constraints)), the statement is semantically equivalent to
```

and similar changes on the following lines.

There might be something better than “meanings”, but they are not “expansions” as they can be implemented differently.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +has the same possible expansions. `ResourceType` is implicitly the compile-time type of the *expression*, which must be a resource type.
This is echoing the statement on 1912, not sure if this repetition is good or bad…

Also see the comment on “expansions” above (1926)

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +A ***resource*** is either a class or non-ref struct that implements either or both of the `System.IDisposable` or `System.IAsyncDisposable` interfaces, which includes a single parameterless method n
The terms *resource* and *resource type* seem to be getting used somewhat interchangeably in this PR to mean the latter – a type, and *resource* is also being use to mean the acquired resource – a thing. The definition here of *resource* defines it as a type, not a thing. It can be a bit confusing.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +corresponds to the expansions shown below with `IAsyncDisposable` instead of `IDisposable`, `DisposeAsync` instead of `Dispose`, and the `Task` returned from `DisposeAsync` is `await`ed:
“corresponds to” -> semantically equivalent to? And below.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/statements.md
> +is equivalent to
(a self-critique – I know I am the source of this and 2124 :-))

Given other uses around here maybe “is semantically equivalent to” or “is equivalent in meaning to” or something similar?

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). When the body of async iterator method accesses this parameter, it will receive a combination of tw
> When the body of async iterator method accesses this parameter, it will receive a combination of two cancellation tokens

An unusual was to say “The value of the parameter will be…”.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
And if it is not applied to any parameter? The token passed to `GetAsyncEnumerator` is discarded, should that be Standardised?

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
> Other cancellation tokens should be composed into a single aggregate token and substituted for the argument to this parameter.

Unclear what *other* is here, there is one possibly passed to `GetAsyncEnumerator` are there others?

Note sure this example should be here, see the overall review comment.

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If
“The convention is…” seems wrong here, the type `CancellationToken` is required by the Standard and baked into various type signatures. The para also repeats material in §enumerator-cancellation (in `attributes.md`)

2025-08-15 01:51 UTC, Nigel-Ecma commented on standard/standard-library.md
> +        IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken token = default);
See review opening comment

2025-08-15 20:58 UTC, BillWagner reviewed
Thanks @Nigel-Ecma I've now addressed all but the summary (and related) comments.

2025-08-15 20:58 UTC, BillWagner commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
More or less. It's not "discarded", in that the enumerator may use it. The iterator code won't have access to it. Added a clarifying sentence.

2025-08-15 20:58 UTC, BillWagner commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
One edit: update this example. Will address the overall review comment separatedly.

2025-08-15 20:58 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If
Replaced with a single sentence referring to the *attributes* clause.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +  - Perform member lookup on the type `X` with identifier «GetEnumerator» and no type arguments. If the member lookup does not produce a match, or it produces an ambiguity, or produces a match that i
tagging @jskeet I did this on the next commit. However, I don't know how the word converter will display nested numbered lists, and if that is consistent with any ECMA requirement. @RexJaeschke please add a comment if ECMA has a rule for this.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +> *Note:* A `ref struct` type cannot be the resource type for a `using` statement with the `await` modifier because `ref struct` types cannot implement interfaces. *end note*
Edited. I made this normative, and removed the "because..." clause. The grammar would allow `await using ...` with a `ref struct`, but the earlier paragraphs note that `DisposeAsync` must be a member of `IAsyncDisposable` (not pattern based.)

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +is equivalent to
"semantically equivalent" was already used often in the standard. I chose that option.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +corresponds to the expansions shown below with `IAsyncDisposable` instead of `IDisposable`, `DisposeAsync` instead of `Dispose`, and the `Task` returned from `DisposeAsync` is `await`ed:
semantically equivalent.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +has the same possible expansions. `ResourceType` is implicitly the compile-time type of the *expression*, which must be a resource type.
I'm all for removing duplication.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
>  An implementation is permitted to implement a given *using_statement* differently, e.g., for performance reasons, as long as the behavior is consistent with the above expansion.
Deleted this paragraph.

2025-08-15 20:58 UTC, BillWagner commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
With the help of a thesaurus, I chose "formulation". I welcome alternatives. 

Note: I rejected "form" because we use it in a related way in many places.

2025-08-20 18:13 UTC, BillWagner commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
For the overall comment, this example did stay to show an example of when tokens would be combined.

2025-08-22 22:13 UTC, jnm2 commented
@jskeet @BillWagner 💭 I realized WithCancellation isn't likely the most common scenario for the cancellation token merging. It's actually more like these operations, which send/merge the cancellation token to the [EnumeratorCancellation] parameter using the exact same mechanism:

```cs
var list = await SomeAsyncEnumerable().ToListAsync(cancellationToken);
var first = await SomeAsyncEnumerable().FirstAsync(cancellationToken);
```

Why pass the cancellation token to the terminating call (ToListAsync/FirstAsync) and not directly to the generating enumerable? It's not just that you might be using an enumerable that already exists. Even if you're not, the benefit of handling cancellation from the end is things like this:

```cs
var first = await SomeAsyncEnumerable()
    .SelectMany(async (item, cancellationToken) => await TransformItemAsync(item, cancellationToken))
    .FirstAsync();
```

(Depending on the impl:) When FirstAsync finds its first item, it can cancel all the way back up through the SelectMany, stopping its in-flight operations, and all the way into SomeAsyncEnumerable.

This turns out to be a foundational piece for composing larger queries.

2025-08-22 22:21 UTC, jnm2 commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
> It's not "discarded", in that the enumerator may use it.

It's not clear to me how the enumerator could use it besides to do the only thing it currently does with it, which is to pass it to the async method body. Perhaps, to skip calling the async method body entirely if the token is canceled before the first call to MoveNextAsync happens. But once the async method body starts running, what can the enumerator do in response to the token if the token hasn't been passed to the async method body? Inject the equivalent of ThrowIfCancellationRequested around every yield? I think that would be too surprising for the author of the async method to understand, and that enumerators really don't have an opportunity to do anything with the token besides pass it to the async method.

2025-08-22 22:25 UTC, jnm2 commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
"Combined" and "aggregate" were competing synonyms. "Combined" goes along with the .NET API call that you make to do the combining.

```suggestion
> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single combined token and substituted for the argument to this parameter. In the following example, one token is passed to the `GetStringsAsync` method, and another is passed to the `WithCancellation` extension method. The compiler can create a combined token that requests cancellation when either token has requested cancellation. The async iterator then cancels the operation based on the state of the combined token.
```

2025-08-22 22:27 UTC, jnm2 commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
Can we say "A cancellation token passed to GetAsyncEnumerator" so that readers have a definitive pointer to what this is talking about?

2025-08-22 22:30 UTC, jnm2 commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. Other cancellation tokens should be composed into a single aggregate token and
~~Possibly also, can we clarify that EnumeratorCancellation only has an effect when the method's return type is `IAsyncEnumerable<T>` (thus, GetAsyncEnumerator exists) and not when the method's return type is `IAsyncEnumerator<T>`?~~

Moving this comment above.

2025-08-22 22:33 UTC, jnm2 commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
```suggestion
It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter of a different type than `CancellationToken` or on a method that isn't an asynchronous iterator (§15.15) which returns an asynchronous enumerable interface ([§15.15.3](classes.md#15153-enumerable-interfaces)) rather than an asynchronous enumerator interface ([§15.15.2](classes.md#15152-enumerator-interfaces)).
```

2025-08-22 22:41 UTC, jnm2 commented on standard/classes.md
> +An async function ([§15.14](classes.md#1514-async-functions)) implemented using an iterator block ([§13.3](statements.md#133-blocks)) is called an ***asynchronous iterator***. An asynchronous iterato
Can the `member ([§12.6](expressions.md#126-function-members)) or local function ([§13.6.4](statements.md#1364-local-function-declarations))` language be placed here?

Without it, it sounds like it's implying that an async function defined per `#1514-async-functions` may be implemented using an iterator block, but this not allowed for all async functions defined per `#1514-async-functions`, because that section defines async functions to include async anonymous functions. Anonymous functions may not be iterators.

2025-08-22 22:49 UTC, jnm2 commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If
I feel uncomfortable defining what looks like a type name without the full type name. Taking a page from https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/classes.md#15141-general:

```suggestion
An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If an iterator has such a parameter, and that parameter is marked with the attribute `System.Runtime.CompilerServices.EnumeratorCancellationAttribute` (§enumerator-cancellation), the compiler creates an aggregate token from the cancellation token provided by the caller and the one provided in `GetAsyncEnumerator`. This aggregate token signals a canceled request when either of the aggregated tokens indicates that cancellation is requested.
```

2025-08-22 22:55 UTC, jnm2 commented on standard/classes.md
> +A synchronous enumerable object implements `IEnumerable` and `IEnumerable<T>` or `IAsyncEnumerable<T>`, where `T` is the yield type of the iterator. Its `GetEnumerator` method returns an enumerator o
```suggestion
A synchronous enumerable object implements `IEnumerable` and `IEnumerable<T>`, where `T` is the yield type of the iterator. Its `GetEnumerator` method returns an enumerator object (§15.15.5). An async enumerable object implements `IAsyncEnumerable<T>` where `T` is the yield type of the iterator. Its `GetAsyncEnumerator` method returns an asynchronous enumerator object  (§15.15.5).
```

2025-08-26 15:28 UTC, BillWagner commented
@jnm2 

This sample: 

> ```cs
> var list = await SomeAsyncEnumerable().ToListAsync(cancellationToken);
> var first = await SomeAsyncEnumerable().FirstAsync(cancellationToken);
> ```

Did you mean this instead:

```cs
var list = await SomeAsyncEnumerable().ToListAsync(cancellationToken);
var first = await first.FirstAsync(cancellationToken);
```

Otherwise, I'm a bit confused.

2025-08-26 15:36 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. The convention is to use a parameter of type `System.Threading.Tasks.CancellationToken` to check for cancellation. If
This edit is moot, as most of this paragraph was moved. I made a global change to be sure I caught all of them.

2025-08-27 01:29 UTC, jnm2 commented
> Did you mean this instead:
> 
> ```cs
> var list = await SomeAsyncEnumerable().ToListAsync(cancellationToken);
> var first = await first.FirstAsync(cancellationToken);
> ```

@BillWagner I did mean `var first = await SomeAsyncEnumerable().FirstAsync(cancellationToken);`, just as a second example (not necessarily part of the same code block). The point was my realization that the method that receives the cancellation token might much more commonly be `ToListAsync` or `FirstAsync` (and others) rather than `WithCancellation`.

2025-08-27 02:55 UTC, jnm2 requested changes

2025-08-27 02:55 UTC, jnm2 commented on standard/attributes.md
> +>     if (number == "5") sourceTwo.Cancel(); q
```suggestion
>     if (number == "5") sourceTwo.Cancel();
```

2025-08-27 02:55 UTC, jnm2 commented on standard/classes.md
> +An asynchronous enumerable object provides an implementation of the `GetAsyncEnumerator` method of the `IAsyncEnumerable<T>` interface. This method returns an available asynchronous enumerator object
Maybe? Should these match?
```suggestion
An asynchronous enumerable object provides an implementation of the `GetAsyncEnumerator` method of the `IAsyncEnumerable<T>` interface. This method returns an available asynchronous enumerator object. The enumerator object is initialized with the argument values and instance value saved when the enumerable object was initialized, including the optional cancellation token, but otherwise the enumerator object functions as described in [§15.15.5](classes.md#15155-enumerator-objects). An asynchronous iterator method can mark one parameter as the cancellation token using `System.Runtime.CompilerServices.EnumeratorCancellationAttribute` (§enumerator-cancellation). An implementation shall provide a mechanism to combine cancellation tokens such that an asynchronous iterator is canceled when either cancellation token (the argument to `GetAsyncEnumerator` or the argument attributed with the attribute `System.Runtime.CompilerServices.EnumeratorCancellationAttribute`) requests cancellation.
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +   1. Perform member on `E` with the identifier `Current` and no type arguments. If the member lookup produces no match, the result is an error, or the result is anything except a public instance pro
```suggestion
   1. Perform member lookup on `E` with the identifier `Current` and no type arguments. If the member lookup produces no match, the result is an error, or the result is anything except a public instance property that permits reading, produce an error and take no further steps.
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +   1. Otherwise, if there is more than one such type `T`, then produce an error and take no further steps.
This just reminds me of the open bug about these lines: https://github.com/dotnet/csharpstandard/issues/1188.

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
The spec uses 'expansions' ~19 times, for instance to define the `as` operator (https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#121213-the-as-operator):

> If the compile-time type of `E` is not `dynamic`, the operation `E as T` produces the same result as
> 
> ```csharp
> E is T ? (T)(E) : (T)null
> ```
> 
> except that `E` is only evaluated once. A compiler can be expected to optimize `E as T` to perform at most one runtime type check as opposed to the two runtime type checks implied by the expansion above.
> 
> If the compile-time type of `E` is `dynamic`, unlike the cast operator the `as` operator is not dynamically bound ([§12.3.3](expressions.md#1233-dynamic-binding)). Therefore the expansion in this case is:
> 
> ```csharp
> E is T ? (T)(object)(E) : (T)null
> ```

Are these not examples of spec using "expansion" to describe semantic equivalence?

Depending on the outcome here: foreach statement 'expansions' are discussed in some of the edited text in this file.

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +- If the type `X` of *expression* is an array type then there is an implicit reference conversion from `X` to the `IEnumerable<T>` interface where `T` is the is the element type of the array `X` (§17
```suggestion
- If the type `X` of *expression* is an array type then there is an implicit reference conversion from `X` to the `IEnumerable<T>` interface where `T` is the element type of the array `X` (§17.2.3).
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +A `foreach` statement of the form
```suggestion
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +- «MoveNext» is a `MoveNextAsync` method has an awaitable return type ([§12.9.8.2](expressions.md#12982-awaitable-expressions)) where the *await_expression* is classified as a `bool` ([§12.9.8.3](exp
```suggestion
- «MoveNext» is a `MoveNextAsync` method that has an awaitable return type ([§12.9.8.2](expressions.md#12982-awaitable-expressions)) where the *await_expression* is classified as a `bool` ([§12.9.8.3](expressions.md#12983-classification-of-await-expressions)).
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +- «GetEnumerator» is a `GetEnumeratorAsync` method.
```suggestion
- «GetEnumerator» is a `GetEnumeratorAsync` method that has an awaitable return type (§12.9.8.2).
```

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +In the case where the expression `enumerable` represents a method call expression and one of the parameters is marked with the `EnumeratorCancellationAttribute` (§enumerator-cancellation) the a `Canc
I'm very happy with this language. Thank you @BillWagner for the large amount of effort you put into this.

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> -```
I think we need the expansion to be defined for the async case too. It looks like we're losing that.

The async case is distinct from the expansion shown under "synchronous foreach" because it involves an `await` and then has some interesting rules for how disposal works.

Observations from my testing:
- `await using` will not dispose the enumerator in a synchronous fashion regardless of whether it implements `IDisposable` or has a `public void Dispose()` method. (edit: true, but `await foreach` is the same)
- ~~`await using`~~ `await foreach` will call `DisposeAsync()` whether or not the enumerator implements the `IAsyncDisposable` interface, so long as the return type is awaitable. (The awaited result type doesn't even have to be void!) It also doesn't have to be public, so long as it's accessible at the `await foreach` location. If accessible, it is preferred over an implicit implementation of `IAsyncDisposable.DisposeAsync`.
  - In all of these points, it differs from the synchronous version.
  - This means that `await foreach` disposes entirely differently from how `await using` disposes.

~~Not sure how much of that is spec material vs compiler quirks.~~ or me setting up my tests incorrectly 😅

2025-08-27 02:55 UTC, jnm2 commented on standard/statements.md
> +A using declaration shall not appear directly inside a `case` label, but, instead, may be within a block inside a `case` label.
To cover `default` labels as well:
```suggestion
A using declaration shall not appear directly inside a *switch_label*, but, instead, may be within a block inside a *switch_label*.
```

2025-08-28 15:51 UTC, BillWagner commented on standard/statements.md
> +A `foreach` statement of the form
I think this is needed. Deferring to @RexJaeschke

2025-08-28 18:46 UTC, BillWagner commented on standard/statements.md
> -```
See commit 2a7718554e96ae52a143b576c3370778b212f4fd, the 37th in this PR.

2025-08-29 01:15 UTC, jnm2 commented on standard/statements.md
> -```
Oh! That is a good addition. What I see _here_ though that I still think is lacking that was being deleted was the expansion for `await foreach`.

2025-08-29 15:57 UTC, BillWagner commented on standard/statements.md
> -```
It was added in an earlier PR. See lines 1353-1368

2025-09-01 12:45 UTC, jskeet approved these changes
I've only carefully reviewed the bits that I know have changed since the last meeting. @BillWagner shout if there's anything you'd like me to double check.

2025-09-01 12:45 UTC, jskeet commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
The second half of this sentence is a bit hard to read - the "or on a method that isn't an asynchronous iterator which returns an asynchronous enumerable interface rather than an asynchronous enumerator interface" part.

I think it would be easier to read if we just removed "rather than an asynchronous enumerator interface".

Alternatively, we could change it to a set of bullet points, for situations of:

- The attribute is applied to the wrong type of parameter
- The attribute is applied on a method which isn't an asynchronous iterator
- The attribute is applied on a method which returns an asynchronous enumerator instead of an asynchronous enumerable interface

(But I'd prefer just deleting the "rather than an asynchonrous enumerator interface" part.)

2025-09-01 12:45 UTC, jskeet commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. The cancellation token passed to `GetAsyncEnumerator` is combined with `source
```suggestion
> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another is passed to the `ToListAsync` extension method. The cancellation token passed to `GetAsyncEnumerator` is combined with `sourceOne.Token` into a single combined token and substituted for the argument to this parameter. The compiler can create a combined token that requests cancellation when either token has requested cancellation. The async iterator then cancels the operation based on the state of the combined token.
```

(Just reordering the sentences, otherwise we're referring to `sourceOne.Token` without introducing the example code that contains it.)

2025-09-01 12:45 UTC, jskeet commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The value of this parameter is a combination of two cancellation tokens: the token which was actual
"will be" suggests we're requiring that the compiler observes this attribute - but later we have "The compiler can create a combined token" - let's decide whether or not a C# 8 compiler *must* implement this.

2025-09-01 12:45 UTC, jskeet commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. This is described in §enumerator-cancellation.
"can support" feels a bit ambiguous here - it's unclear (as per my earlier comment) whether an implementation is required to support it. I understand that any given concrete asynchronous iterator may not specify a cancellation token, of course, but I think "Asynchronous iterators support cancellation [...]" would be clearer, assuming we *are* requiring that it's supported.

2025-09-01 12:45 UTC, jskeet commented on standard/statements.md
> +In the case where the expression `enumerable` represents a method call expression and one of the parameters is marked with the `EnumeratorCancellationAttribute` (§enumerator-cancellation) the a `Canc
```suggestion
In the case where the expression `enumerable` represents a method call expression and one of the parameters is marked with the `EnumeratorCancellationAttribute` (§enumerator-cancellation) the `CancellationToken` is passed to the `GetAsyncEnumerator` method. Other library methods may require a `CancellationToken` is passed to `GetAsyncEnumerator`. When those methods are part of the expression `enumerable`, the tokens shall be combined into a single token as if by `CreateLinkedTokenSource` and its `Token` property.
```

2025-09-01 12:45 UTC, jskeet commented on standard/statements.md
> +In the case where the expression `enumerable` represents a method call expression and one of the parameters is marked with the `EnumeratorCancellationAttribute` (§enumerator-cancellation) the a `Canc
Nit: `enumerable` could be a method call expression, but not specify an argument for a cancellation token due to the parameter being optional. I'd suggest that if we agree that *is* a problem, we address it in a separate PR.

2025-09-01 23:43 UTC, Nigel-Ecma commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The value of this parameter is a combination of two cancellation tokens: the token which was actual
@jskeet – I think we need to cover combining tokens, see [this comment](https://github.com/dotnet/csharpstandard/pull/672#pullrequestreview-3108512762) for choices what to include.

“the token which was actually passed to the method” is not clear to me, which is the method”? Not the one with a parameter with this annotation on it, as that would be circular, so which one is it?

2025-09-02 01:51 UTC, Nigel-Ecma commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
Agree with @jskeet some wordsmithing needed. Also is not “If no attributes have this parameter” the wrong way round?

2025-09-02 01:56 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. The cancellation token passed to `GetAsyncEnumerator` is combined with `source
This is in an example so maybe this is a quibble, but “The compiler can” is surely wrong. If token combination is in the Standard, as I expect it is, then in normative text the implementation *must*/*shall* combine the tokens, in informative descriptive text maybe the implementation *will* combine?

2025-09-02 01:59 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. The cancellation token passed to `GetAsyncEnumerator` is combined with `source
This is in an example so maybe this is a quibble, but “The compiler can” is surely wrong. If token combination is in the Standard, as I expect it is, then in normative text the implementation *must*/*shall* combine the tokens, in informative descriptive text maybe the implementation *will* combine?

2025-09-02 06:53 UTC, jskeet commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The value of this parameter is a combination of two cancellation tokens: the token which was actual
It *is* "the method with the parameter with this annotation on it" - which I understand is surprising. (It's quite odd to pass an argument, and end up with a different value for the parameter... but that's what's happening here.)

2025-09-02 15:35 UTC, BillWagner commented on standard/attributes.md
> +It is an error if the `EnumeratorCancellation` attribute is applied to more than one parameter. The compiler may produce a warning if the `EnumeratorCancellation` attribute is applied to a parameter
Wordsmithed in upcoming commit.

I did retain all the potential warnings. The committee should discuss if we want those to be normative.

2025-09-02 19:29 UTC, BillWagner commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The value of this parameter is a combination of two cancellation tokens: the token which was actual
Reworded to try and make this more clear.

2025-09-02 19:30 UTC, BillWagner commented on standard/classes.md
> +An asynchronous iterator can support cancellation of the asynchronous operation. This is described in §enumerator-cancellation.
Reworded to use "shall support"

2025-09-02 23:49 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute instructs the compiler that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method,
I first thought “instructs the compiler” could be replaced with “informs the compiler”, but that still talks about the compiler when this is surely just part of the language, so I ended up with:

```suggestion
> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another is passed to the `ToListAsync` extension method. The cancellation token passed to `GetAsyncEnumerator` is combined with `sourceOne.Token` into a single combined token and substituted for the argument to this parameter. The compiler can create a combined token that requests cancellation when either token has requested cancellation. The async iterator then cancels the operation based on the state of the combined token.
```

2025-09-03 14:50 UTC, jnm2 commented on standard/statements.md
> +A `foreach` statement of the form
This was my misunderstanding the diff, sorry!

2025-09-03 14:51 UTC, jnm2 commented on standard/statements.md
> -```
Ah, thank you, I was misunderstanding diffs again.

2025-09-03 14:55 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The argument for this parameter shall be combined with the argument passed to `IAsyncEnumerable<T>.
From what I saw when I decompiled the compiler-generated code, there is no requirement that GetAsyncEnumerator polls the cancellation token. If the async method body ignores the cancellation token, then it is never observed.
```suggestion
Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The argument for this parameter shall be combined with the argument passed to `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)`. The tokens shall be combined into a single token as if by `CancellationToken.CreateLinkedTokenSource` and its `Token` property. The combined token will be canceled if either of the two source tokens are canceled. The combined token is seen as the argument to the asynchronous iterator method (§15.15) in the body of that method.
```

2025-09-03 14:58 UTC, jnm2 commented on standard/attributes.md
> +Specifies the parameter representing the `CancellationToken` for an asynchronous iterator (§15.15). The argument for this parameter shall be combined with the argument passed to `IAsyncEnumerable<T>.
In other words, [EnumeratorCancellation] is simply about making a merged token available to the method body, and is not about having the generated implementation of IAsyncEnumerable respond to any token.

2025-09-03 15:05 UTC, jnm2 approved these changes

2025-09-03 15:05 UTC, jnm2 commented on standard/statements.md
> +        System.IDisposable d = e as System.IAsyncDisposable;
```suggestion
        System.IAsyncDisposable d = e as System.IAsyncDisposable;
```

2025-09-03 15:05 UTC, jnm2 commented on standard/statements.md
> +    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to `System.IAsyncDisposable` shall not cause boxing to occur.
Since it may be System.IDisposable as well:
```suggestion
    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to an interface shall not cause boxing to occur.
```

2025-09-03 15:05 UTC, jnm2 commented on standard/statements.md
> +    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to `System.IAsyncDisposable` shall not cause boxing to occur.
Also, should this message appear underneath the final expansion showing an interface cast?

2025-09-03 19:55 UTC, jskeet commented on standard/statements.md
> +- Otherwise, if `E` is a sealed type, the `finally` clause is expanded to an empty block:
Assuming I've understood the meeting properly, we need another bullet point about IDisposable

2025-09-03 19:57 UTC, RexJaeschke commented on standard/attributes.md
> +### §enumerator-cancellation The EnumeratorCancellation attribute
1. Still need to add a pointer. Can ignore 2.

2025-09-03 19:59 UTC, jnm2 approved these changes

2025-09-04 18:18 UTC, BillWagner commented on standard/statements.md
> +corresponds to one of three possible expansions. For class and non-ref struct resources, when `ResourceType` is a non-nullable value type or a type parameter with the value type constraint ([§15.2.5]
Decision in 9/3 meeting: We agree that "semantic equivalent" is better. Captured in #1409

2025-09-04 18:29 UTC, BillWagner commented on standard/statements.md
> +- Otherwise, if `E` is a sealed type, the `finally` clause is expanded to an empty block:
Added in final commit.

2025-09-04 22:48 UTC, jnm2 commented on standard/statements.md
> -```
I had erroneously concluded that `await foreach` had a fallback to a synchronous dispose, but that was incorrect. The rules are as specified at <https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-01-16.md#pattern-based-disposal-in-await-foreach> which @BillWagner found.

2025-09-04 22:51 UTC, jnm2 commented on standard/statements.md
> +    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to `System.IAsyncDisposable` shall not cause boxing to occur.
I had erroneously concluded that `await foreach` had a fallback to a synchronous dispose, but that was my mistake in testing. The rules are as specified at <https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-01-16.md#pattern-based-disposal-in-await-foreach> which @BillWagner found.

2025-09-05 14:20 UTC, BillWagner commented
@jskeet @RexJaeschke @Nigel-Ecma This is now ready for a final post-meeting review.

2025-09-08 10:31 UTC, jskeet reviewed
One deletion which I'm sure is needed - beyond that, I have a few points of confusion.

2025-09-08 10:31 UTC, jskeet commented on standard/statements.md
> +    // enumerator.Dispose() if enumerator is a `ref struct` type and supports synchronous disposal
Leaving a comment here as the closest change - line 1345 needs to be removed.

2025-09-08 10:31 UTC, jskeet commented on standard/statements.md
> +    // omitted, along with the try/finally,
The order of these comments is confusing me. I think it would be worth rewriting these two slightly as "The try/finally is omitted entirely (including the finally body) if the enumerator doesn't expose a dispose method" and *then* have the method calls.

But it may just be me - see what other people think.

2025-09-08 10:31 UTC, jskeet commented on standard/statements.md
> +  - Otherwise the `finally` clause is expanded to the semantic equivalent of:
This otherwise is nested, but I'm unclear why. If it's meant to be "E is a ref struct type without an accessible Dispose() method" then I think we should restructure the preceding part to be a peer, e.g.

```
- Otherwise, if `E` is a `ref struct` type:
  - If `E` has an accessible `Dispose()` method, the `finally` clause is expanded [...]
  - Otherwise, the `finally` clause is expanded to the semantic equivalent of...
```

2025-09-08 10:31 UTC, jskeet commented on standard/statements.md
> +    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to `System.IAsyncDisposable` shall not cause boxing to occur.
So does the bullet below need to be removed entirely? I'm confused now...

2025-09-08 16:03 UTC, jnm2 commented on standard/statements.md
> +    except that if `E` is a value type, or a type parameter instantiated to a value type, then the conversion of `e` to `System.IAsyncDisposable` shall not cause boxing to occur.
I think so. A ref struct cannot be used as the enumerator of `await foreach` because a ref struct cannot be stored on the heap to enable access to it across an `await` or `yield` boundary.

2025-09-08 20:40 UTC, BillWagner commented on standard/statements.md
> +    // omitted, along with the try/finally,
The combination of your comments made me do a bit of spec refactoring. I think it reads better and is simpler now.

2025-09-08 23:31 UTC, jnm2 approved these changes

2025-09-09 09:09 UTC, jskeet approved these changes
I *think* I now understand, although I'm getting confused by the intermediate changes etc. Nothing concrete to block this, so I'd recommend getting it in... we can always fix any remaining issues later (without the 198 comments...)

2025-09-09 23:26 UTC, Nigel-Ecma requested changes
Changes requested:

- One comment line that needs deleting
- In §13.9.5.3 there is a discrepancy between the semantically equivalent code and the following description of what goes in the `finally` of that code.

Other comments are on language and are take or leave as you see fit!

2025-09-09 23:26 UTC, Nigel-Ecma commented on standard/attributes.md
> +- The `EnumeratorCancellation` attribute is applied to a parameter of a different type than `CancellationToken`,
Language, maybe the following?

```suggestion
- The `EnumeratorCancellation` attribute is applied to a parameter of a type other than `CancellationToken`,
```

2025-09-09 23:26 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
This uses `ToListAsync`, which looks like it wasn’t around in C# 8’s time (it is in .NET 10 and has been added to earlier versions as an add-on?), is there a more suitable choice? Using it and stating it is an extension method just seems to add noise to the example. (My own test code uses `GetAsyncEnumerator` directly along with `MoveNextAsync` & `while` – but that may not be “more suitable”!)

2025-09-09 23:26 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
The spec is to combine the tokens (as in line 1065), not “The compiler can”.

```suggestion
> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another is passed to the `ToListAsync` extension method. The cancellation token passed to `GetAsyncEnumerator` is combined with `sourceOne.Token` into a single combined token and substituted for the argument to this parameter. This combined token requests cancellation when either token has requested cancellation. The async iterator then cancels the operation based on the state of the combined token.
```

The tense seems wrong to me as well – the token is polled, using “token requests” sounds like the token itself is the actor. But I’ve no wordsmithing to offer on this one.

2025-09-09 23:26 UTC, Nigel-Ecma commented on standard/standard-library.md
> +        // optional, see below
This was a comment to TG2

```suggestion
```

2025-09-09 23:26 UTC, Nigel-Ecma commented on standard/statements.md
> +    // if the enumerator doesn't expose a dispose method
These four lines are confusing and doesn’t fully cover the cases in the explanation just below starting on line 1372. However the explanation doesn’t include the statement here that the try/finally can be completely omitted, but it does have a case where the finally is empty. These discrepancies need fixing.

Maybe the code sample could just include a comment referring to line 1372 for the expansion, and the explanation be expanded to cover the lack of a dispose method producing an empty finally?

Such a change would remove the comment here about eliding the try/finally and replace it with a statement in the explanation that the finally is empty for that case (note there is an existing empty case, the conditions for each could be combined?). I can’t see this is an issue, is not removing an empty finally a valid implementation optimisation?

2025-09-09 23:54 UTC, jnm2 commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
It was around in C# 8's time as the community library System.Linq.Async (https://www.nuget.org/packages/System.Linq.Async/4.0.0).

The library was merged into .NET 10 recently (https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/10.0/asyncenumerable).

The reason behind my suggestion of ToListAsync was to be more representative of realistic use cases than WithCancellation or GetAsyncEnumerator, but there may be good reasons to pick a less common/more "contrived" example.

2025-09-09 23:57 UTC, jnm2 commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
I share the sense that it's not the token doing the requesting.

Fwiw, it's not just polling in the standard sense. It's relatively frequently that I use CancellationToken.Register which registers a callback to handle cancellation rather than polling the token.

I'd offer "signals" instead of "requests."

2025-09-10 02:25 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
@jnm2 – Reading this from a Standard-reader perspective we have a sample which uses something not in the Standard (what does it do?), and tells us it is an extension method (wonders if that is significant?). This is of course a common challenge with examples.

FWIW this is a fragment from my, definitely contrived :-), testing code:

```csharp
CancellationTokenSource ctsA = new CancellationTokenSource();
CancellationTokenSource ctsB = new CancellationTokenSource();

IAsyncEnumerable<int> iae = GetIntsAsync(limit, ctsA.Token);
var iterator = iae.GetAsyncEnumerator(ctsB.Token);

while (await iterator.MoveNextAsync())
{
    int current = iterator.Current;
```

Now the reader might wonder why it doesn’t use a `foreach` of course, but overall doesn’t use anything other than what it or the Standard defines.

2025-09-10 02:31 UTC, Nigel-Ecma commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
@jnm2 – It is just polling in the Standard sense as `Register` is not in the Standard.

I think “signals” is an improvement here (unless the reader is used to *nix where it implies something rather stronger than “requests”! :-))

2025-09-10 19:02 UTC, BillWagner reviewed
Thanks @jnm2 @Nigel-Ecma 

I address all the remainig feedback.

2025-09-10 19:02 UTC, BillWagner commented on standard/attributes.md
> +### §enumerator-cancellation The EnumeratorCancellation attribute
Thanks Rex. Add in the final commit.

2025-09-10 19:02 UTC, BillWagner commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
I used "indicates". That seemed to flow well with the existing text.

2025-09-10 19:02 UTC, BillWagner commented on standard/attributes.md
> +> The `EnumerationCancellation` attribute indicates that the associated parameter is used for cancellation. In the following example, one token is passed to the `GetStringsAsync` method, and another
I added a definition for `ToListAsync` to the sample. That should address Nigel's concerns.

2025-09-10 19:02 UTC, BillWagner commented on standard/statements.md
> +    // if the enumerator doesn't expose a dispose method
Good catch. Coming in next commit.

2025-09-11 01:30 UTC, Nigel-Ecma commented on standard/attributes.md
>  > ```csharp
@BillWagner – This sample is not compiling for me. Adding `async` to your version of `ToListAsync()` gets that method to compile, but overall it still fails at the `await foreach`

> CS8411 Asynchronous foreach statement cannot operate on variables of type `ValueTask<List<object>>` because `ValueTask<List<object>>` does not contain a suitable public instance definition for `GetAsyncEnumerator`

VS2022 (ARM), LangVersion=8.0, .NET 8

2025-09-11 02:08 UTC, jnm2 commented on standard/attributes.md
> +>     await foreach (TSource element in source)
Importantly, ToListAsync here must use WithCancellation in order to cancel waiting for the next item. It could do this instead of directly polling the cancellation token. As written now, it will not signal the cancellation token in the async iterator method body.

2025-09-11 04:50 UTC, Nigel-Ecma commented on standard/attributes.md
> +> await foreach (string number in GetStringsAsync(sourceOne.Token).ToListAsync(sourceTwo.Token))
@BillWagner & @jnm2 – I understand Joseph's wish to show something more realistic here, but I think it is hiding what the example needs to show - the connection between the asynchronous iterator and `GetAsyncEnumerator` where the language requires the combining of `CancellationToken`’s. To do this the example needs to show `GetAsyncEnumerator` so the description can refer to it, so back to something like:

```suggestion
> await foreach (string number in GetStringsAsync(sourceOne.Token).GetAsyncEnumerator(sourceTwo.Token))
```

which directly shows the two key items - the enumerable and the enumerator. Using `ToListAsync` just detracts from the purpose and adds complexity (and pitfalls as we've seen!)

2025-09-11 15:54 UTC, BillWagner commented on standard/attributes.md
> +> await foreach (string number in GetStringsAsync(sourceOne.Token).ToListAsync(sourceTwo.Token))
@jnm2 @Nigel-Ecma Updated to use a modified version of Nigel's sample above (`await foreach` requires `IAsyncEnumerable`, not `IAsyncEnumerator`.

2025-09-11 21:36 UTC, Nigel-Ecma commented on standard/attributes.md
> +> await foreach (string number in GetStringsAsync(sourceOne.Token).ToListAsync(sourceTwo.Token))
@BillWagner – Apologies, by bad, it was late and I foolishly translated from a while/move sample in my IDE to a foreach in the comment box…

2025-09-11 21:38 UTC, Nigel-Ecma approved these changes
LGTM :-)

2025-09-11 22:00 UTC, jnm2 approved these changes

2025-09-11 22:00 UTC, jnm2 commented on standard/attributes.md
>  > }
Last nit from me. The foreach involves disposal, so when lowering `await foreach` down to a while loop, we should either use `await using` or a try...finally with explicit disposal.
```suggestion
> await using (IAsyncEnumerator<string> enumerator = GetStringsAsync(sourceOne.Token).GetAsyncEnumerator(sourceTwo.Token))
> {
>     while (await enumerator.MoveNextAsync())
>     {
>         string number = enumerator.Current;
>         if (number == "8") sourceOne.Cancel();
>         if (number == "5") sourceTwo.Cancel();
>         Console.WriteLine(number);
>     }
> }
```

2025-09-12 14:03 UTC, BillWagner commented on standard/attributes.md
> +> }
```suggestion
> await using (IAsyncEnumerator<string> enumerator = 
>     GetStringsAsync(sourceOne.Token).GetAsyncEnumerator(sourceTwo.Token));
> while (await enumerator.MoveNextAsync())
> {
>     string number = enumerator.Current;
>     if (number == "8") sourceOne.Cancel();
>     if (number == "5") sourceTwo.Cancel();
>     Console.WriteLine(number);
> }
```

2025-09-12 14:10 UTC, BillWagner commented on standard/attributes.md
> +>
```suggestion
> ```
> 
```

2025-09-12 14:17 UTC, BillWagner commented on standard/attributes.md
> +>
```suggestion
>     yield return number;
> }
> ```
>
```

2025-09-12 14:50 UTC, jnm2 approved these changes

2025-09-12 15:16 UTC, merged

2025-09-24 23:31 UTC, RikkiGibson commented on standard/statements.md
> +1. Determine whether the type `X` has an appropriate «GetEnumerator» method:
In this context, it's not clear where the type `X` comes from.

2025-09-25 00:19 UTC, jnm2 commented on standard/statements.md
> +1. Determine whether the type `X` has an appropriate «GetEnumerator» method:
Good point, but I don't think it's `C`. The ***collection type*** (`C`) is determined on like 1126 by examining `X`.

2025-09-25 00:21 UTC, jnm2 commented on standard/statements.md
> +1. Determine whether the type `X` has an appropriate «GetEnumerator» method:
The original text (original line 1126) had `If the type `X` of *expression*`. It was probably removed by mistake? @BillWagner

2025-09-25 21:52 UTC, BillWagner commented on standard/statements.md
> +1. Determine whether the type `X` has an appropriate «GetEnumerator» method:
PR is here: https://github.com/dotnet/csharpstandard/pull/1422

Thanks for pointing it out @RikkiGibson