Adding support for default interface function members
dotnet/csharpstandard pull request #681
Opened 2022-12-05 13:54 UTC by RexJaeschke

Re the [MS proposal](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/default-interface-methods.md): The main challenge when reading it was the (misleading) occurrence of the modifier `override` in numerous examples and narrative. As best as I can tell, this modifier is **not** actually permitted on any interface member. Instead, overriding is achieved via explicit implementation.

There is [one open question](https://github.com/dotnet/docs/issues/32871), which has to do with the topic "Base Interface Invocations," for which the decision "Decided on `base(N.I1<T>).M(s)`" was made. However, as far as I can tell, support for this was **not** added to the V8 compiler. Can someone please confirm (or refute) that.

BTW, I think the proposal is misnamed: it really applies to all interface function members (properties, indexers, and events as well), not just methods. (it also allows nested types.)

2022-12-06 17:15 UTC, RexJaeschke commented
Depending how [PR #680](https://github.com/dotnet/csharpstandard/pull/680) is resolved, some tweaks might be needed with this PR.

2023-09-25 20:54 UTC, BillWagner commented
rebased on the latest draft-v8 on 09-23-2023

2023-09-25 21:23 UTC, KalleOlaviNiemitalo commented
Should the references to "C# implementations targeting the CLI" be changed somehow because the ECMA standard CLI does not support default interface members?  Possible answers include:

- Remove them; C# 8 implementations cannot target "the CLI".
- Change them to say "targeting a CLI with extensions" or the like.
- Keep them; a C# implementation can still target the standard CLI, although the mapping may become complex or inefficient or have restrictions (like not supporting dynamic loading of assemblies that were not provided at build time).

2024-11-12 21:52 UTC, RexJaeschke commented
Re @KalleOlaviNiemitalo's concern about the Ecma CLI standard *not* supporting default interface function members, we previously made a related change to the draft-v8 Introduction, which in V7, said:

> ... Although Microsoft’s implementation of C# relies on CLI for library and run-time support, other implementations of C# need not, provided they support **an alternate way of getting at the minimum CLI features** required by this C# standard (see Annex C).

It now says:

> ... Although Microsoft’s implementation of C# relies on CLI for library and run-time support, other implementations of C# need not, provided they support **the features and API** required by this C# Standard (see [Annex C](standard-library.md#annex-c-standard-library)).

I think that allows us to say nothing more for this feature with regard to the CLI.

2024-12-11 00:33 UTC, gafter commented on standard/classes.md
> +Given these definitions, the complete set of types upon which a type depends is the transitive closure of the *directly depends on* relationship.
```suggestion
Given these definitions, the complete set of types upon which a type depends is the reflexive and transitive closure of the *directly depends on* relationship.
```

2024-12-11 00:34 UTC, gafter commented on standard/classes.md
> +Given these definitions, the complete set of types upon which a type depends is the transitive closure of the *directly depends on* relationship.
The suggested change is required to disallow `class A : A {}`

2024-12-11 00:43 UTC, gafter commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member among the overrides appearing in the type or its direct and indirect interfaces. The ***most specific override**
What is "an override"?

2024-12-15 01:14 UTC, gafter commented
I don't recall why this is assigned to me. Is it for general review, or to answer the question about `base(T).M()`?  If the latter, see the following:

- https://github.com/dotnet/csharplang/discussions/8870
- https://github.com/dotnet/csharplang/issues/2910
- https://github.com/dotnet/csharplang/issues/8871

In short, the `base(T).M()` syntax has not been added to the language yet.

2024-12-15 16:13 UTC, BillWagner commented
@gafter

> I don't recall why this is assigned to me. Is it for general review, or to answer the question about `base(T).M()`? 

Going from memory, but I believe as a general reviewer.

2025-05-28 15:16 UTC, RexJaeschke commented
closed and reopened to get all tests to run

2025-06-04 04:04 UTC, Nigel-Ecma commented on standard/classes.md
> +Given these definitions, the complete set of types upon which a type depends is the transitive closure of the *directly depends on* relationship.
It been a long day, but does not adding reflexive *require* “A depends on A” not disallow it?

2025-06-11 13:09 UTC, jskeet commented
@RexJaeschke and @BillWagner could you look at resolving the conflict?

I'm not sure whether we can realistically expect most members to have reviewed this before the meeting later today though. (I'll see whether I can find time, but I'm prioritizing #606.)

2025-06-11 14:07 UTC, BillWagner commented
> @RexJaeschke and @BillWagner could you look at resolving the conflict?
> 
> I'm not sure whether we can realistically expect most members to have reviewed this before the meeting later today though. (I'll see whether I can find time, but I'm prioritizing #606.)

@jskeet I did a full rebase. 

My main goal in prioritizing this for today's meeting is to get it assigned to someone for next meeting. I agree that there isn't time to get it reviewed thoroughly.

2025-06-25 08:29 UTC, jskeet commented
@BillWagner Looking again, did we get as far as assigning it during the last meeting? We spent quite a bit of time talking about prose vs grammar for constraints, but we didn't record the next step...

2025-06-25 12:18 UTC, BillWagner commented
@jskeet I have on my list to rebase this PR, and do an edit pass with notes so we have a basis for assigning at this coming meeting.

2025-06-25 21:33 UTC, Nigel-Ecma commented
@jskeet & @BillWagner – I have a note to myself to “compare grammar vs. semantic by Jul 3”, no idea whether I will make that…

2025-06-27 19:09 UTC, BillWagner reviewed
We know that there's more work coming here.  For this next meeting, I'd like to see the committee agree on some key points regarding the direction for this PR:

1. Terms used. Neal had some earlier comments, I added more on what terms to use for the new concepts in this feature.
2. The overall strategy of defining members of `class`, `struct` and `interface` declarations. Right now, we *mostly* define everything in terms of class, then deltas for interfaces and structs. But, sometimes those deltas are in the class clause, sometimes in interfaces or structs. Over the next several releases, the differences continue to shrink (static abstract members in interfaces, struct default constructors and field initializers, and so on.) I see two potential directions:
  - Continue to define interfaces and structs in terms of a delta from class types. If we follow that, I'd recommend moving all the remaining text for deltas out of the class clause into structs or interfaces (including some added in this PR)
  - Create a new "Members" clause the defines the common features of members, and then classes, interfaces, and structs can reference that with deltas. 
  
Personally, I think the former is easier because "Members" are hard to define without one of class, struct, interface. And all of class, struct, and interface are incomplete without fully specifying all the members.

2025-06-27 19:09 UTC, BillWagner commented on standard/classes.md
> +Given these definitions, the complete set of types upon which a type depends is the transitive closure of the *directly depends on* relationship.
I'll make the alternative suggestion to delete line 277. I don't think it's needed.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide ***default implementation***s for some or all of the fu
I think we should remove this phrase.  Any interface members that have a default implementation are part of the interface contract, but they have a default implementation:

```suggestion
Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide ***default implementation***s for some or all of the function members that it declares. For those members for which the interface does not provide default implementations, the interface merely specifies the members that shall be supplied by classes or structs that implement the interface.
```

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +    | field_declaration
This is incorrect. Interface can't include non-static fields. We'll need to rework the grammar in classes.md to provide a distinction between instance and static data fields.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +    | event_declaration
field-like events can't be declared in an interface. This will also require more splitting of the grammar rules for events to distinguish the two syntaxes for them.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +An interface declaration declares zero or more members. The members of an interface shall be constants, fields, methods, properties, events, indexers, operators, constructors, and types, some of whic
This needs to clarify that interfaces can't include instance data fields (including field-like events). It might be the best place to mention that interfaces use the same syntax for auto-implemented properties for an abstract property.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
Two thoughts:

1. Lines 258 - 294 should probably be non-normative. The normative language should be that an interface member must be accessed as an explicit interface member.
2. I don't like the phrasing about "not part of the contract". Instead, I'd suggest we phrase this in terms of "visibility" or even "inheritance". An interface member with a default implementation must be accessed through a reference of that interface type. It isn't visible as a member of an implementing class, or derived interface.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +- An async declaration shall have a *block* as a *method_body*.
This needs some wordsmithing. I don't think we want "block" here. Expression bodied members are legal.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +An interface method declaration that has a *block* as a *method_body* is a default implementation ([§18.1](interfaces.md#181-general)), so it is *not* part of the interface’s contract. A *method_decl
Two bits here:

Again, my concern with "part of the contract" as the terminology. And, an expression bodied member is legal, so *block* is the wrong term.

2025-06-27 19:09 UTC, BillWagner commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member among the overrides appearing in the type or its direct and indirect interfaces. The ***most specific override**
I would use the term from the feature spec "most specific implementation". The feature spec defines it as 

> The most specific implementation is a unique implementation that is more specific than every other implementation. If there is no implementation, the member itself is considered the most specific implementation.

2025-07-02 16:29 UTC, jnm2 commented on standard/classes.md
> +When an interface `IB` extends an interface `IA`, it is a compile-time error for `IA` to depend on `IB`. An interface **directly depends on** its direct base interfaces (if any) and **directly depend
Why are interfaces being mentioned here?

2025-07-02 16:35 UTC, jnm2 commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide ***default implementation***s for some or all of the fu
The grammar was strange and it also seemed to rule out having the implementations be supplied by another interface.
```suggestion
Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide ***default implementation***s for some or all of the function members that it declares, in which case, those members are *not* part of the interface contract. Members for which the interface does not provide default implementations are abstract. Their implementations are supplied by derived interfaces or by classes or structs which implement the interface.
```

2025-07-02 16:38 UTC, jnm2 commented on standard/interfaces.md
> +> *Note*: Historically, adding a new function member to an interface impacted all existing consumers of that interface type; it was a breaking change! The addition of default interface function membe
In C# 13, when ref structs are allowed to implement interfaces, ref structs can't make use of DIMs. Therefore in C# 13+, adding an interface member goes back to being a breaking change (but only for consumers who implement your interface on a `ref struct`).

2025-07-02 16:43 UTC, jnm2 commented on standard/interfaces.md
> +    | event_declaration
They may be if they are static, though. To address this through splitting of grammar rules, does that entail splitting `event_declaration` into `static_event_declaration`, `instance_custom_event_declaration`, and `instance_fieldlike_event_declaration`? Could we instead add non-grammar text which says "Event declarations in interfaces must either be static or explicitly declare accessors"?

2025-07-02 16:55 UTC, jnm2 commented on standard/interfaces.md
> +    | event_declaration
Actually, field-like events can sometimes be declared depending also on whether they are abstract or virtual/sealed.

```cs
using System;

interface I
{
    // Allowed, has a static backing field.
    public static event EventHandler StaticFieldlike;
    // Allowed, has accessors.
    public static event EventHandler StaticCustom { add { } remove { } }

    // Allowed, implicitly abstract.
    public event EventHandler InstanceFieldlikeAbstract;

    // Disallowed, asks for an instance backing field because it is not abstract.
    public virtual event EventHandler InstanceFieldlikeVirtual;
    public sealed event EventHandler InstanceFieldlikeSealed;

    // Disallowed: CS8712 event cannot use event accessor syntax
    public abstract event EventHandler InstanceCustomAbstract { add; remove; }

    // Allowed, implicitly virtual.
    public event EventHandler InstanceCustomVirtual { add { } remove { } }

    // Allowed, has accessors.
    public sealed event EventHandler InstanceCustomSealed { add { } remove { } }
}
```

2025-07-02 17:00 UTC, jnm2 commented on standard/interfaces.md
> +    | event_declaration
So all event declaration syntaxes are allowed in interfaces except for the following:
1. An instance event with the `virtual` or `sealed` modifiers *must* declare accessors.
1. An instance event with the `abstract` modifier *must not* declare accessors.

2025-07-02 17:12 UTC, jnm2 commented on standard/interfaces.md
> +    | field_declaration
Perhaps this could be addressed with text placing on restrictions, as may have to be the case for events which have many permutations. (https://github.com/dotnet/csharpstandard/pull/681/files#r2180552691)

2025-07-02 17:14 UTC, jnm2 commented on standard/interfaces.md
> +All interface members implicitly have public access; however, an explicit access modifier ([§7.5.2](basic-concepts.md#752-declared-accessibility)) is permitted.
This statement doesn't apply to static constructors which become allowed in C# 8 as part of DIMs.

2025-07-02 17:20 UTC, jnm2 commented on standard/interfaces.md
> +- The name of a method shall differ from the names of all other kinds of function members declared in the same interface. In addition, the signature ([§7.6](basic-concepts.md#76-signatures-and-overlo
Does "function members" include classes? For instance, this does not compile:
```cs
interface I
{
    void Foo();
    class Foo { }
}
```

2025-07-02 17:22 UTC, jnm2 commented on standard/interfaces.md
> +- The name of a method shall differ from the names of all other kinds of function members declared in the same interface. In addition, the signature ([§7.6](basic-concepts.md#76-signatures-and-overlo
If "function members" _does_ include classes then this line above is incorrect because a nested class may have both the `private` and `sealed` modifiers:

> A `private` or `sealed` function member of an interface shall have a body. A `private` function member shall not have the modifier `sealed`.

2025-07-02 17:28 UTC, jnm2 commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
Agreed. The real reason why you can't access `M` directly on `C` is that `C` doesn't declare a public `M`.

This is not really new with DIMs. It could also happen if C (or any of its base classes) used an explicit implementation. The only thing that's new with DIMs is that the explicit implementation can be in any of the interfaces as well as being in C or any of its base classes.

2025-07-02 17:34 UTC, jnm2 commented on standard/interfaces.md
> +As a *constant_declaration* is considered to have a default implementation ([§18.1](interfaces.md#181-general)), it is *not* part of the interface’s contract.
The "default impl means it's out of the contract" philosophy comes up here as well and in the following blocks. I'm not sure yet that I accept this philosophy. One could also say that the member is still in the contract. That is, the class is still "on the hook" to provide the whole contract, including this member- it's just that the class has chosen to fulfill that contract by deferring to the default implementation for this member.

With C# 13 and ref structs, this becomes clearer. Ref structs can't make use of default implementations, so they must implement every member explicitly. This shows that every interface member really is part of the interface contract, even when a default implementation exists for it.

2025-07-02 17:39 UTC, jnm2 commented on standard/interfaces.md
> +A *property_declaration* that has a *block* as an *accessor_body* is a default implementation ([§18.1](interfaces.md#181-general)), so it is *not* part of the interface’s contract. A *property_declar
Expression-bodied properties should be considered here. `int Prop => 42;` is a default implementation. Also echoing the concern about excluding DIMs from the "contract."

2025-07-02 17:46 UTC, jnm2 commented on standard/interfaces.md
> +An interface function member whose declaration includes a body is an implicitly `virtual` member unless the `sealed` or `private` modifier is used. The `virtual` modifier may be used on a function me
This only applies to instance members.

2025-07-02 17:52 UTC, jnm2 commented on standard/interfaces.md
> +A *property_declaration* that has a *block* as an *accessor_body* is a default implementation ([§18.1](interfaces.md#181-general)), so it is *not* part of the interface’s contract. A *property_declar
Can we also restrict this to talking about instance properties? I get confused when I enter this paragraph with `static int Prop { get; set; }` in mind, which is an auto prop.

2025-07-02 17:54 UTC, jnm2 commented on standard/interfaces.md
> +As a static *field_declaration* is considered to have a default implementation ([§18.1](interfaces.md#181-general)), it is *not* part of the interface’s contract.
Here and elsewhere: do we want to talk about fields and constants as "having implementations"? Do we even want to talk about static members as having ***default*** implementations, as though there was any "slot" being "implemented" where we selected the "default" option for the slot?

2025-07-02 18:01 UTC, jnm2 commented on standard/interfaces.md
> +> class C: I<D>
The typical style is `ClassName : InterfaceName`, so I don't love this change. Elsewhere in the file, new code has been added that similarly does not follow the typical style.

2025-07-02 18:03 UTC, jnm2 commented on standard/interfaces.md
>      ;
Why retain `interface_method_header` when `interface_method_declaration` is removed?

2025-07-02 18:04 UTC, jnm2 commented on standard/interfaces.md
> +- A static declaration that is not extern or abstract shall have a *block* as a *method_body*.
```suggestion
- A static declaration that is not extern shall have a *block* as a *method_body*.
```
Until C# 11, a static declaration cannot be abstract.

2025-07-02 18:14 UTC, jnm2 commented on standard/interfaces.md
> +> *Note*: See §interface-fields for an example that not only shows a static method with default implementation, but as that method is called `Main` and has the right return type and signature, it’s a
There are some exclamation points being added in notes on this one 😂 Is that typical?

2025-07-02 18:15 UTC, jnm2 commented on standard/interfaces.md
> +A virtual method with implementation declared in an interface may be overridden to be abstract in a derived interface. This is known as ***reabstraction***.
We're flagging the term "override/overridden" in other comment threads; so, pointing it out here as well.

2025-07-02 20:08 UTC, BillWagner commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member among the overrides appearing in the type or its direct and indirect interfaces. The ***most specific override**
We prefer `override` here. But, we must ensure that `virtual` has a correct definition for interfaces that declare `virtual` members either abstract or non-abstract. 

Also, consider how to use the language or classes but, "stretch" it as appropriate for interface declarations.

Define "most specific override" in the context of interface declarations.

2025-07-21 21:11 UTC, BillWagner commented on standard/interfaces.md
> +> *Note*: Historically, adding a new function member to an interface impacted all existing consumers of that interface type; it was a breaking change! The addition of default interface function membe
Right. At that time, we'll need to update this note.

2025-07-22 10:33 UTC, jskeet commented
@BillWagner Is "meeting: priority" still appropriate for this? I see a bunch of changes, but I'm not sure what the status of the PR is.

2025-07-22 15:20 UTC, BillWagner commented
> Is "meeting: priority" still appropriate for this? I see a bunch of changes, but I'm not sure what the status of the PR is.

@jskeet Yes, I've finished a full edit pass. If possible, I'll run one more, because I'm not happy with how "most specific override" is defined yet.

2025-07-29 14:23 UTC, jskeet reviewed
I *hope* we're getting close enough that we can get this merged with extra issues filed.

2025-07-29 14:23 UTC, jskeet commented on standard/classes.md
> +[§15.6](classes.md#156-methods) and its subclauses cover method declarations in classes. That text is augmented by information about declaring methods in structs ([§16.4](structs.md#164-class-and-str
I really like this way of describing how the material is organized.

2025-07-29 14:23 UTC, jskeet commented on standard/classes.md
> +- The declaration may include the `abstract` and `override` modifiers so that an abstract member may override a virtual member.
```suggestion
  *Note*: The declaration may include both the `abstract` and `override` modifiers so that an abstract member may override a virtual member. *end note*
```

Happy to be overruled (overridden?) on this - it just feels like it's not something that needs to be normative, as it's already covered.

2025-07-29 14:23 UTC, jskeet commented on standard/classes.md
> +- The declaration may include the `abstract` and `override` modifiers so that an abstract member may override a virtual member.
(Arguably if we're making it a note, it would be simpler to move it to after the list.)

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +    | event_declaration
I'm so glad the two of you are looking at this - my take on the topic is that if everything else is okay, I'd be happy to merge and create a follow-up issue for events which goes into all the relevant details.

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +- The name of a method shall differ from the names of all other kinds of function members declared in the same interface. In addition, the signature ([§7.6](basic-concepts.md#76-signatures-and-overlo
15.3.1 (for classes) states this as "The name of a method shall differ from the names of all other non-methods declared in the same class."

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +- The name of a non-function member shall differ from the names of all other non-function member declared in the same interface.
```suggestion
- The name of a non-function member shall differ from the names of all other non-function members declared in the same interface.
```

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
Agreed on all fronts, but I'd be happy with a "merge and raise an issue" approach for this one.

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +>     public const int constant = 100;
```suggestion
>     public const int Constant = 100;
```

(And later references.)

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +- An async declaration shall have a block body or expression body as a *method_body*.
I assume async is already "not extern" by prohibitions elsewhere?

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +> class C: I<D>
Yup, I'd prefer a space after the class name too.

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +A virtual method with implementation declared in an interface may be overridden to be abstract in a derived interface. This is known as ***reabstraction***.
Would "re-abstraction" be clearer - particularly in terms of pronunciation - than "reabstraction"?

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +For a type `T` that is a struct or a class that implements interface `I` with a member `M`, the most specific implementation of `M` is:
I think this needs a bit of work. It sort of assumes that I2 and I3 exist (otherwise the final bullet doesn't make sense) but they're only defined in the penultimate bullet. (And the penultimate bullet seems to be assuming the interfaces have default implementations of M, maybe?)

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +*property_modifier* shall not include `override`.
This feels odd for a paragraph on its own. Perhaps this should be a list, with the previous paragraph being something like:

"Interface properties are declared using *property_declaration*s ([§15.7.1](classes.md#1571-general)) with the following additional rules:"

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +A derived interface mey implement an abstract interface property declared in a base interface.
```suggestion
A derived interface may implement an abstract interface property declared in a base interface.
```

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +Interface indexers are declared using *indexer_declaration*s ([§15.9](classes.md#159-indexers)).
Same comment as before about maybe using a list.

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +An *operator_declaration* in an interface is a default implementation ([§18.1](interfaces.md#181-general)).
This doesn't sound right to me. For example, look at https://learn.microsoft.com/en-us/dotnet/api/system.numerics.iadditionoperators-3.op_addition?view=net-9.0- there's no default implementation there, is there?

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +It is a compile-time error for an interface to contain a conversion, equality, or inequality operator.
Perhaps declare instead of contain?

2025-07-29 14:23 UTC, jskeet commented on standard/interfaces.md
> +It is not possible to access an explicit interface member implementation through its qualified interface member name in a method invocation, property access, event access, or indexer access. An expli
Let's be consistent in ordering here - either "explicit interface instance member" and "explicit interface static memeber" *or* "explicit instance interface member" and "explicit static interface member". I think I'd prefer the former, to keep "explicit interface" together everywhere, but I'm happy to go with consensus.

2025-07-29 19:25 UTC, jnm2 commented on standard/interfaces.md
> +A virtual method with implementation declared in an interface may be overridden to be abstract in a derived interface. This is known as ***reabstraction***.
For me personally, I don't think the hyphen makes it any clearer despite it being a word I almost never come across. I'm not opposed though.

2025-07-29 19:37 UTC, jnm2 commented on standard/interfaces.md
> +An *operator_declaration* in an interface is a default implementation ([§18.1](interfaces.md#181-general)).
The operator you linked is a static abstract interface member, which is not possible in C# 8. Static abstract interface members don't show up in C# until version 11 (https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#generic-math-support).

However, as I commented elsewhere, "default implementation" doesn't sound right for static members because it implies that there could be more than one implementation. In C# 8, for a static interface member, there cannot.

2025-07-30 07:18 UTC, Nigel-Ecma commented on standard/interfaces.md
> +> *Note*: See §interface-fields for an example that not only shows a static method with default implementation, but as that method is called `Main` and has the right return type and signature, it’s a
Nope it is not typical, I find just two occurrences of the RE `[a-z]!<space>` in the Standard and they’re both in example code. I agree it is not Standardese and we shouldn’t in general do it.

2025-07-30 20:17 UTC, jskeet commented on standard/classes.md
> +[§15.6](classes.md#156-methods) and its subclauses cover method declarations in classes. That text is augmented by information about declaring methods in structs ([§16.4](structs.md#164-class-and-str
(Resolving.)

2025-07-30 20:22 UTC, jskeet commented on standard/classes.md
> +- The declaration may include the `abstract` and `override` modifiers so that an abstract member may override a virtual member.
Given that we think it has been prohibited at some point, I'm happy to keep it normative.

2025-07-30 20:24 UTC, jskeet commented on standard/interfaces.md
> +    | field_declaration
Agreed in the meeting that we don't need this in the grammar, but possibly emphasize "only static" in the text.

2025-07-30 20:26 UTC, jskeet commented on standard/interfaces.md
> +- The name of a method shall differ from the names of all other kinds of function members declared in the same interface. In addition, the signature ([§7.6](basic-concepts.md#76-signatures-and-overlo
Bill will run some tests on this.

2025-07-30 20:29 UTC, jskeet commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
Possibly adjust style to be less didactic? And remove contract.

2025-07-30 20:29 UTC, BillWagner commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
TODO:  Search for "not part of the contract" and update to "abstract" terminology in recent commits.

2025-07-30 20:30 UTC, jskeet commented on standard/interfaces.md
>      ;
@BillWagner to sync with @Nigel-Ecma to make sure we don't get conflicts, but we think we can remove interface_method_header.

2025-07-30 20:32 UTC, jskeet commented on standard/interfaces.md
> +A virtual method with implementation declared in an interface may be overridden to be abstract in a derived interface. This is known as ***reabstraction***.
We decided not to hyphenate.

2025-07-30 20:33 UTC, jskeet commented on standard/interfaces.md
> +For a type `T` that is a struct or a class that implements interface `I` with a member `M`, the most specific implementation of `M` is:
@BillWagner and @jskeet will look at this offline

2025-07-30 20:37 UTC, jskeet commented on standard/interfaces.md
> +An *operator_declaration* in an interface is a default implementation ([§18.1](interfaces.md#181-general)).
Definitely some more work to do; will discuss offline.

2025-08-21 18:55 UTC, BillWagner commented on standard/interfaces.md
> +*property_modifier* shall not include `override`.
Updated all sections with more than one additional rule to follow this format.

2025-08-21 20:49 UTC, BillWagner reviewed
Added comments from the latest edit.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +Every interface and class shall have a most specific implementation for every virtual member among the overrides appearing in the type or its direct and indirect interfaces. The ***most specific over
I moved this text to its own section. The most specific implementation applies to properties and other member types as well.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +For a type `T` that is a struct or a class that implements interface `I` with a member `M`, the most specific implementation of `M` is:
Wordsmithed and clarified. I think this is good now.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +Every interface and class shall have a most specific implementation for every virtual member among the overrides appearing in the type or its direct and indirect interfaces. The ***most specific over
This section now starts on line 532

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
>      ;
The next commit removes it. That rule isn't mentioned anywhere in the text.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +Consider an interface with a default implementation for a member `M`. As `M` is not part of that interface’s contract, outside that interface or any interface derived from it, that name is not visibl
wordsmithed to say "must be accessed through a reference whose compile time type is identity convertible to `IA`.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +- The name of a method shall differ from the names of all other kinds of function members declared in the same interface. In addition, the signature ([§7.6](basic-concepts.md#76-signatures-and-overlo
The rules for declarations in an interface mirror those in a class (in 15.3.1). I re-wrote this section to use the structure of later sections to minimize duplication of the rules. This now only specifies the differences. Because of those changes, the class rules on inheritance (15.3.4) and `new` (15.3.5) are specifically called out.

2025-08-21 20:49 UTC, BillWagner commented on standard/interfaces.md
> +An *operator_declaration* in an interface is a default implementation ([§18.1](interfaces.md#181-general)).
This is true for all static members, in a sense. Operators are unique because at least one operator must be the containing type, so operators declared in a derived interface have different signatures and are overloads.

For normal static methods, if a derived interface declares the same signature, the derived type must use the `new` modifier.

In all cases, I can replace "default implementation" with "implementation" and the language gets simpler:  A method with an implementation is already not abstract, so we're good. In fact, adding `abstract` to a member with an implementation is an error.

2025-08-21 20:57 UTC, BillWagner commented on standard/interfaces.md
> +    | field_declaration
Proposed edit that I'd like @Nigel-Ecma to weigh in on before I proceed:

I have removed the *interface_method_header* that was flagged in our last meeting. I think the grammar can be further simplified:  

We currently have *class_member_declaration* in 15.3.1.  This is almost exactly repeated in *interface_member_declaration* in 18.4.1. The difference is the omission of *finalizer* and *constructor* declarations.

I believe we can simplify these rules by renaming *class_member_declaration* as *member_declaration*. We already have normative text that describes the differences. and it does keep the grammar simpler (maybe?).  I don't think this is the time to remove *struct_member_declaration*. But, that feels like the right task later as we get more struct type declarations.

Let me know what you think and I'll make the additional edits.

2025-08-22 18:33 UTC, BillWagner commented on standard/interfaces.md
> +    | event_declaration
Edited based on https://github.com/dotnet/csharpstandard/pull/681#discussion_r2180562405

2025-09-01 04:40 UTC, Nigel-Ecma requested changes
There appears to be semantics missing.

I stopped reviewing after reaching Bill’s ping to me.

As indicated in a comment I am as yet undecided whether the shift to fewer grammar rules with more context semantic rules is the correct one for a reference grammar *in this case*. It can be, it’s also somewhat of an subjective blurry boundary!

One of the grammar tests is failing – this does not indicate there is a problem *per se* as the PR changes how some constructs are defined so the expected parse will change. The new parse for the test will need to be manually checked and then the expected results updated; I can assist with this before the final PR is merged.

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/classes.md
> +Structs (§16) and interfaces (§18) provide data structures that contain members similar to classes. Rules restrict the declarations for struct and interface types, and the member declarations allowed
Are interfaces now data structures? §18.1 still defines them as contracts. Also “Rules restrict…” doesn’t read correctly to me.

```suggestion
Structs (§16) and interfaces (§18) have members similar to classes but with certain restrictions. This clause defines the declarations for classes and class members. The clauses for structs and interfaces define the restrictions for those types in terms of the corresponding declarations in class types.
```

Maybe?

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/classes.md
> +A ***constant*** is a class member that represents a constant value: a value that can be computed at compile-time. A *constant_declaration* introduces one or more constants of a given type. A *consta
Line 7 says this clause contains the description for classes and the struct and interface clauses contain the restrictions relative to this clause, so why here is the point being added that constants are allowed in structs & interfaces as they are unless the respective clauses include a restriction?

I would more expect such ”allowed” statements if the class/struct/interface clauses were being collapsed into one with the differences between them noted throughout the clause. However having, or not, such statements is just a style issue.

I expect as I read through there are going to be many more of these, I won't comment on them all.

Regardless, there is a small typo:

```suggestion
A ***constant*** is a class member that represents a constant value: a value that can be computed at compile-time. A *constant_declaration* introduces one or more constants of a given type. A *constant_declaration* may appear in a class, struct, or interface declarations.
```

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/classes.md
> +An abstract method declaration introduces a new virtual method but does not provide an implementation of that method. Instead, non-abstract derived classes are required to provide their own implement
“Because…” doesn’t read right to me, I’d simplify this to:

```suggestion
An abstract method declaration introduces a new virtual method but does not provide an implementation of that method. Instead, non-abstract derived classes are required to provide their own implementation by overriding that method. The *method_body* of an abstract method simply consists of a semicolon.
```

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/classes.md
> +An abstract property declaration specifies that the accessors of the property are virtual, but does not provide an actual implementation of the accessors. Instead, non-abstract derived classes are re
Fix missing space:

```suggestion
An abstract property declaration specifies that the accessors of the property are virtual, but does not provide an actual implementation of the accessors. Instead, non-abstract derived classes are required to provide their own implementation for the accessors by overriding the property. Because an accessor for an abstract property declaration provides no actual implementation, its *accessor_body* simply consists of a semicolon. An abstract property shall not have a `private` accessor.
```

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide an implementation for some or all of the function membe
There appears to semantics missing around how the new members defined in an interface (as opposed to being simply declared) interact with the inheritance change, `base` invocation, etc. There are some *examples* further which might be attempting to fill in gaps, but the semantics need to be normative.

For example: in the contract-only model we might have `I` with a declaration for `M`, and classes `A : I` and `B : A`; with `A.M` declared `virtual`, `B.M` with `override` and `base.M` in `B` invoking `A.M`.

Say it is decided to move `A`’s definition of `M` directly into `I` marked `virtual`. The call `A.M()` is still valid, but is the `override` definition in `B` still valid? What about the `base` call?

Further does any definition of `M` in `A` have to match any `virtual`, or lack of one, used for `M` in `I`?

To add to the fun consider `A`, `B: I, A` & `C : B` with `M` in `A` & `I` and (`B` and/or `C`) – what does invoking `M` on any of the classes invoke? When are `base` calls valid?

A final one, if the contact model we might have `I`, `A : I`, `B : A` & `C : B` with `M` declared in `I`, defined as `virtual in `A`, and as `override` in `C` (so no definition in `B`). What happens if `A`’s definition is moved into `I`?

The semantics of basic set of combinations need to be defined – unless I’ve misread they appear not to be.

2025-09-01 04:40 UTC, Nigel-Ecma commented on standard/interfaces.md
> +    | field_declaration
@BillWagner – I would recommend not to make any further *optional* grammar changes at this time; both because there are other things to address, and because I don’t think it is clear the switching to more general grammar with added semantic rules for different contexts is a *simplification* in this case – it may or may not be.

(A good rule of thumb is for *reference grammar*s to be as explicit as reasonable with fewer context sensitive semantic rules; an *implementation grammar* may tend to the more lenient. But rules are aways flexible and there is often no *right* answer per se. In this case? No idea yet.)

2025-09-01 13:55 UTC, jskeet reviewed
It feels like there's at least *something* missing - or just something about non-abstract members (in terms of visibility) that I haven't spotted.

2025-09-01 13:55 UTC, jskeet commented on standard/interfaces.md
> +Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be accessed thro
The second sentence sounds it's reiterating something we already know - but I can't see where that's specified at the moment. I *believe* this is key to the `base.M()` question earlier.

2025-09-01 13:55 UTC, jskeet commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide an implementation for some or all of the function membe
I think Nigel's got a point in terms of questions that need answering - although the answers may be in this PR already (or just unchanged). I would say that it's easier to reason about those questions if they're presented as "is this code valid" (or "what does this code do") rather than in terms of changes between one version of the code and another though.

Thinking about the first scenario:

- Just for reference: base access is in section 12.8.15, in expressions.md - it looks like it hasn't changed in this PR; override methods are in 15.6.5 (classes.md)
- I don't believe either the `override` definition or `base.M()` is valid in this case. I'm assuming this is what we're talking about:

```csharp
public interface I
{
    virtual void M()
    {
        Console.WriteLine("I.M");
    }
}

public class A : I
{
}

public class B : A, I
{
    // Error: 'B.M()': no suitable method found to override
    public override void M()
    {
        // Error: 'A' does not contain a definition for 'M'
        base.M();
    }
}
```

Assuming I've interpreted Nigel's scenario correctly, the question is whether these errors are what the proposed spec would show.

I'm pretty sure the "override" error is correct as specified, as `override` only talks about searching the *class* hierarchy for virtual members.

I'm currently unclear on whether the base access "should" work under the current spec. `base.M()` is specified to be equivalent to `((A) this).M()`, which is also invalid, but I can't immediately see where - see my comment on old line 245.

2025-09-01 13:55 UTC, jskeet commented on standard/interfaces.md
> +Within the interfaces `IA` and `IB`, member `M` is accessible directly by name. However, within method `Start`, we cannot write `c.M()` or `c.P`, as those names are not visible. To find them, casts t
Where is `Start()`? Should that just be `Main()`?

2025-09-01 19:39 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide an implementation for some or all of the function membe
@jskeet – Your code is almost my first example, mine just uses `B : A` (no `, I`). I was careful not to say what any particular implementation does, both because what is important is what the design intends and because I haven’t exhuastively analysed an implementation.

C# used to be a single-inheritance (S-I) language, adding definitions into interfaces does not make it multi-inheritance M-I) in, say, the C++ sense but rather makes it some other kind of M-I. A cursory look at the current version of a certain well known implementation show it appears to have a primary ancestor (your parent class, the standard S-I model) and secondary ancestors (“uncle” interfaces, a move in the direction of M-I models) where your parent is your child’s grandparent (as in S-I), but your uncle’s are not your child’s great-uncles (as in ?) – or something like that!

2025-09-01 19:46 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be accessed thro
First “Consider an…” sounds like it is informative but it is normative text.

I’m not sure what the 2nd sentence – “As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible.” – it reads to me as the implementation is only visible from *inside* the interface or interfaces derived from it which would exclude from classes which implement the interface? Am I reading this wrong?

2025-09-02 20:19 UTC, BillWagner commented on standard/classes.md
> +A ***constant*** is a class member that represents a constant value: a value that can be computed at compile-time. A *constant_declaration* introduces one or more constants of a given type. A *consta
> Line 7 says this clause contains the description for classes and the struct and interface clauses contain the restrictions relative to this clause, so why here is the point being added that constants are allowed in structs & interfaces as they are unless the respective clauses include a restriction?

I removed this, and added a statement in interfaces. I wanted to be clear that *constant_declaration*s were allowed in interfaces without any additional restrictions or rules from classes. I made that statement in interfaces.md.

2025-09-02 21:20 UTC, BillWagner commented on standard/interfaces.md
> +Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be accessed thro
I've added some raw notes in the last commit. Here's the sample I was working from. (I'll polish the notes in the morning):

```csharp
var b1 = new DimModel.B();
b1.M();

var b = new DimModel2.B();
b.M();

var c = new DimModel2.C();
c.M();

namespace ContractModel
{
    public interface I
    {
    }

    public class A : I
    {
        public virtual void M() => Console.WriteLine("A.M");
    }

    public class B : A
    {
        public override void M() => base.M();
    }
}

namespace DimModel
{
    public interface I
    {
        public virtual void M() => Console.WriteLine("I.M");
    }

    public class A : I
    {
        //public virtual void M() => Console.WriteLine("A.M");
    }

    public class B : A
    {
        // No suitable method to override.
        // A does not contain a definition for M.
        //public override void M() => base.M();

        // Instead use:
        public void M() => (this as I).M();
        // If A has an implementation calls A.M(), otherwise calls I.M()
    }
}

namespace DimModel2
{
    public interface I
    {
        public virtual void M() => Console.WriteLine("I.M");
    }

    public class A : I
    {
        public virtual void M() => Console.WriteLine("A.M");
    }

    public class B : A, I
    {
        // No suitable method to override.
        // A does not contain a definition for M.
        //public override void M() => base.M();

        // Instead use:
        public override void M() => base.M();
        // If A has an implementation calls A.M(), otherwise calls I.M()
    }

    public class C : B
    {
    }
 }

namespace ContractModel3
{
    public interface I
    {
        void M();
    }

    public class A : I
    {
        public virtual void M() => Console.WriteLine("A.M");
    }

    public class B : A
    {
        // No suitable method to override.
        // A does not contain a definition for M.
        //public override void M() => base.M();

        // Instead use:
        // public override void M() => base.M();
        // If A has an implementation calls A.M(), otherwise calls I.M()
    }

    public class C : B
    {
        public override void M() => base.M();
    }
}

namespace DimModel3
{
    public interface I
    {
        public virtual void M() => Console.WriteLine("I.M");
    }

    public class A : I
    {
        //public virtual void M() => Console.WriteLine("A.M");
    }

    public class B : A
    {
        // No suitable method to override.
        // A does not contain a definition for M.
        //public override void M() => base.M();

        // Instead use:
//        public override void M() => base.M();
        // If A has an implementation calls A.M(), otherwise calls I.M()
    }

    public class C : B
    {
        public void M() => (this as I).M();
    }
}
```

2025-09-03 13:15 UTC, jskeet commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
I thought I'd added a comment here before, but apparently not. Where does this come from:

> As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible.

If that *is* specified somewhere, it may answer a lot of questoins, but I didn't see where it was specified.

2025-09-03 14:25 UTC, BillWagner commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
I added that to the normative language. And, it's slightly incorrect: The compile time type must be an interface type, and implicit conversions (from derived interface to base interface) are allowed.

2025-09-03 14:42 UTC, BillWagner commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
In the most recent commit, the normative language is at lines 577-586 in interfaces.md

2025-09-03 15:26 UTC, jnm2 commented on standard/interfaces.md
> +> *Note*: Historically, adding a new function member to an interface impacted all existing consumers of that interface type; it was a breaking change. The addition of interface function member implem
Side note: In C# 13, it becomes a breaking change again to add an interface member when considering that ref structs may implement interfaces, but a ref structs don't support default interface members and must manually implement every interface member regardless of whether it has a default implementation. (https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#ref-struct-interfaces)

2025-09-03 15:56 UTC, jnm2 requested changes

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +- A derived interface may override an abstract member declared in a base interface. A non-virtual instance function member may be declared using the `sealed` keyword.
(I'm used to using the term 'virtual' in the sense of 'virtual call.' If that is acceptable here, then the term 'virtual' covers abstract members as well. If not, then I guess we should mention both?)
```suggestion
- A derived interface may override a virtual member declared in a base interface. A non-virtual instance function member may be declared using the `sealed` keyword.
```
Also, I believe the only way to override is to provide an explicit implementation; otherwise, you end up declaring a new virtual member (and the `override` keyword is not supported). Should the means of overriding be clarified here?

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +- The name of a non-abstract interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an inte
(And, similar question about whether the term 'virtual' is in the sense of 'virtual call' and thus includes abstract members)
```suggestion
- The name of a non-virtual interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an interface type that is implicitly convertible to the interface where the non-abstract member is declared.
```

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +- As a static *field_declaration* has an implementation ([§18.1](interfaces.md#181-general)), it is *not* abstract.
Does the language have a concept of abstract fields at all? I didn't think so. I don't believe the metadata format supports declaring an abstract field either. If this statement is not in contrast to anything, can it go without saying?

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +Interface properties are declared using *method_declaration*s (§15.6)). The *attributes*, *return_type*, *ref_return_type*, *identifier*, and *parameter_list* of an interface method declaration have
Also, do we really need to enumerate some of the syntactic parts and say their meaning doesn't change? If so, should we include the type parameter list?
```suggestion
Interface methods are declared using *method_declaration*s (§15.6)). The *attributes*, *return_type*, *ref_return_type*, *identifier*, and *parameter_list* of an interface method declaration have the same meaning as those of a method declaration in a class. Interface methods have the following additional rules:
```

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +- A *property_declaration* that has a *block* as an *accessor_body* is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract. An instance *property_declaration* that has no
What about expression-bodied properties: `int Prop => 42;`
And does this cover expression-bodied accessors? `int Prop { get => 42; }`?

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +- An *indexer_declaration* that has a *block* as an *accessor_body* is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract.
Same question about expression-bodied properties and expression-bodied accessors.

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +A *static_constructor_declaration* that has a *block* as a *static_constructor_body* is the implementation ([§18.1](interfaces.md#181-general)).
This leaves out expression-bodied static constructors, but I don't think we even need to make this conditional. It's also on the verge of "goes without saying" for me, since being virtual is impossible given what a static constructor _is_.
```suggestion
A *static_constructor_declaration* is the implementation ([§18.1](interfaces.md#181-general)).
```

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
Maybe?
```suggestion
It is an error in a class declaration if the most specific override of some interface method is an abstract override that was declared in a class or an interface.
```

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +It is an error if a property `P` has a most specific `get` accessor in one type `T1`, and a most specific `set` accessor in another type `T2`.
How is it possible for a property `P` has a most specific `get` accessor in one type `T1`, and a most specific `set` accessor in another type `T2`? It is an error for a property to be overridden/explicitly implemented without respecifying all accessors.

2025-09-03 15:56 UTC, jnm2 commented on standard/interfaces.md
> +Interface members are accessed through member access ([§12.8.7](expressions.md#1287-member-access)) and indexer access ([§12.8.12.3](expressions.md#128123-indexer-access)) expressions of the form `I.
Perhaps?
```suggestion
Interface members are accessed through member access ([§12.8.7](expressions.md#1287-member-access)) and indexer access ([§12.8.12.3](expressions.md#128123-indexer-access)) expressions of the form `I.M` and `I[A]`, where `I` is an interface type or an expression of an interface type, `M` is a constant, field, method, property, or event of that interface type, and `A` is an indexer argument list. If `M` is non-virtual, the name `M` is visible only in the interface `I` and interfaces derived from `I`.
```

2025-09-03 18:36 UTC, Nigel-Ecma commented on standard/interfaces.md
> +- The expression `base.M()` is valid only if `B` provides a definition for `M`. The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is i
Two sentences, both starting “The expression `base.M()` is valid only if”. Is this meant to be a conjunction, or was one sentence meant to replace the other?

2025-09-03 20:13 UTC, jskeet commented on standard/interfaces.md
> +> interface IB: IA
Nit: I *think* we've become consistent in having a space before the colon here. (I know I've mentioned that recently, but I can't remember which PR. Apologies if it's repetition here.)

2025-09-03 20:19 UTC, BillWagner commented on standard/interfaces.md
> +Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be accessed thro
The latest update is incorrect if generic constraints are used. 

```csharp
public interface I { void M() {} }

public class C : I {}

public void TestThings<T>(T arg) where T : I 
{
   arg.M(); // valid
}
```

2025-09-03 20:26 UTC, jnm2 commented on standard/interfaces.md
> +- The name of a non-abstract interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an inte
I'd like to remove this condition (including where this statement is mirrored ten lines down in the note). It is not due to the abstractness or non-abstractness that the name is visible within the class. Rather, it is due to whether the class declares a matching _class_ member.

```suggestion
- The name of an interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an interface type that is implicitly convertible to the interface where the non-abstract member is declared.
```

2025-09-04 00:03 UTC, jnm2 commented on standard/expressions.md
> +- References to `const` members of class, struct, and interface types.
I'm finding dozens of hits for "class _or_ struct" in other places that should now expand to "class, struct, or interface."

2025-09-09 20:51 UTC, BillWagner commented on standard/expressions.md
> +- References to `const` members of class, struct, and interface types.
upcoming commit. I searched for all instances of "class or struct" and where appropriate replace with "class, interface, or struct". Many locations didn't require a change because of context (instance constructor, instance fields, etc)

2025-09-09 20:51 UTC, BillWagner commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§18.4](interfaces.md#184-interface-members). The interface itself may provide an implementation for some or all of the function membe
This was updated before the 9/3 meeting.

2025-09-09 20:51 UTC, BillWagner commented on standard/interfaces.md
> +- The expression `base.M()` is valid only if `B` provides a definition for `M`. The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is i
refactored a bit in next commit.

2025-09-09 20:51 UTC, BillWagner commented on standard/interfaces.md
> +It is an error if a property `P` has a most specific `get` accessor in one type `T1`, and a most specific `set` accessor in another type `T2`.
removed in next commit.

2025-09-09 21:47 UTC, BillWagner commented on standard/interfaces.md
> +- As a static *field_declaration* has an implementation ([§18.1](interfaces.md#181-general)), it is *not* abstract.
removed this line. (redundant with class rules)

2025-09-09 21:47 UTC, BillWagner commented on standard/interfaces.md
> +A *static_constructor_declaration* that has a *block* as a *static_constructor_body* is the implementation ([§18.1](interfaces.md#181-general)).
I did a bit more work here, for a few reasons:

1. static constructors can't be abstract or virtual (as in classes).
2. The static constructor defined in an interface may not be called if none of the members defined in that interface are called (meaning the interface definition is never the "most specific implementation".

2025-09-09 21:47 UTC, BillWagner commented on standard/interfaces.md
> +- A derived interface may override an abstract member declared in a base interface. A non-virtual instance function member may be declared using the `sealed` keyword.
Notes for a commit tomorrow to address all @jnm2 's comments regarding *abstract* vs. *non-virtual*, and the comments regarding the accessibility of the name.

1. An explicit interface implementation is the only way to provide an override of a member defined in an interface. Any other declaration (`virtual` or otherwise) is a new member. It doesn't *hide* the member defined in an interface because of the accessibility rules...
2. An instance interface member is `virtual` (or `abstract`) by default. To prevent implementing types or derived interfaces from providing an overriding implementation, it must be declared `sealed`.
3. A member defined in an interface is accessible only through a reference to that interface type. I'm not sure "visible" is the right term.

2025-09-10 21:26 UTC, BillWagner reviewed
Updated in the latest commit.

2025-09-10 21:26 UTC, BillWagner commented on standard/interfaces.md
> +- The name of a non-abstract interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an inte
Reworked these rules in this section.

2025-09-11 17:57 UTC, jnm2 submitted a review, later dismissed

2025-09-11 17:57 UTC, jnm2 commented on standard/interfaces.md
> +- A *property_declaration* that has a *block* or *expression-bodied-member* as an *accessor_body* is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract. An instance *prop
`int Prop => 42;` is not a property that _has_ an expression-bodied member; the property itself _is_ an expression-bodied member. I am also not sure that an accessor is called a member.

```suggestion
- A *property_declaration* that has an *expression body* or contains an accessor with a body is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract. An instance *property_declaration* that has no implementation is always considered abstract; it is *never* considered to be an automatically implemented property ([§15.7.4](classes.md#1574-automatically-implemented-properties)).
```

2025-09-11 17:57 UTC, jnm2 commented on standard/interfaces.md
> +- An *indexer_declaration* that has a *block* or *expression-bodied-member* as an *accessor_body* is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract.
(As above)
```suggestion
- An *indexer_declaration* that has an *expression body* or contains an accessor with a body is an implementation ([§18.1](interfaces.md#181-general)), so it is *not* abstract.
```

2025-09-15 17:25 UTC, BillWagner commented
Thanks to @Nigel-Ecma for the updated grammar validation.

This is ready for a 2nd review.  I'll watch for comments between now and our meeting, and address all those I can before the meeting.

I've updated the semantics on visibility and accessibility of members defined (not just declared) in an interface, along with the definition of "most specific override". Reviews should check the semantics both for correctness and clarify.

Open question for meeting discussion:  See https://github.com/dotnet/csharpstandard/pull/681/#discussion_r2312853934. Looking into our future, do we want to make the `class`, `struct` and `interface` grammar(s) more unified? If so, when? Where do we want to rely on semantic rules in text to disallow constructs that are consistent with the grammar?

2025-09-19 21:00 UTC, gafter commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member declared in all interfaces implemented by that type among the overrides appearing in the type or its direct and
This is not correct. I believe this constraint only applies to concrete types (classes and structs). See [HERE](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIBYAEBZAhgSygAoBKTAbwFgAoAXxpsOAFMwAzXAY2cwEEaq1TMMwYcpANw161RlBbsuPAEKYQfATRGisvAHTZSFGTLkKO3TAGE1G6oO1j9hsuRMNqTVhZ4ARdcow1ppCItI0QA==)

2025-09-19 23:19 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member declared in all interfaces implemented by that type among the overrides appearing in the type or its direct and
@gafter – Hmm… Is your interface `D` usable? If you change `D` to a class an error is produced, if you leave it as an interface and declare `class E : D` an error is produced.

In other words is this an implementation choosing not to report an error if `D` is not used, but doing so once it is? 

Of course if `D` can be used without generating an error then the statement is indeed incorrect.

2025-09-23 14:24 UTC, jskeet commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
Hmm... was it "The name of a non-abstract interface member is only visible in that interface and interfaces derived from it. That member can be accessed only through a reference whose compile-time type is an interface type that is implicitly convertible to the interface where the non-abstract member is declared."

That was removed in https://github.com/dotnet/csharpstandard/pull/681/commits/28e33919f38b49d86b49537a19e74a1c839b9e14

... I don't see any equivalent now.

2025-09-23 14:54 UTC, jskeet reviewed
A few comments - these are all I could actively find as new points of concern, but I have weak confidence in my own reviewing capability of this PR.

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
Is this a counterexample? (This code compiles.)

```csharp
interface IF
{
  void M();
}

abstract class F : IF
{
    public abstract void M();
}
```

In `F`, the most specific override of `IF.M()` is `F.M()`, which is an abstract override declared in a class, isn't it?

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +- The expression `base.M()` is valid only if `B` provides a definition for `M`. The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is i
```suggestion
- The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is in a class type. To access the most specific implementation if it was defined in an interface, use the cast expression `(this as I).M()` to refer to the most specific implementation (§most-specific-implementation) of `M` in `I` or an interface derived from `I`.
```

(Or possibly some other change, but at the moment it's a bit odd.)

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +### §most-specific-implementation Most specific override
Rename the section to "Most specific implementation"? At the moment we appear to have both terms ("most specific implementation" and "most specific override") in use - I *hope* we can just use one.

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +- Before the Main method is called for an interface containing the Main method ([§7.1](basic-concepts.md#71-application-startup)) in which execution begins.
```suggestion
- Before the `Main` method is called for an interface containing the `Main` method ([§7.1](basic-concepts.md#71-application-startup)) in which execution begins.
```

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +- The implementation for a member defined in the interface is accessed as the most specific implementation (§most-specific-implementation) for that member.
I can't quite tell whether this is about "The implementation for (a member defined in the interface)" or "(The implementation for a member defined in the interface)". 

For example:

```csharp
interface I
{
    static I()
    {
        Console.WriteLine("static I()");
    }
    
    void M();
}

class C : I
{
    public void M()
    {
    }
}
```

... then in Main:

```csharp
I i = new C();
i.M();
```

Is the static constructor called or not? It looks like not... I suspect this is really about where the implementation lives. That's already one way of reading it of course, but I think it could be clearer.

Would "The interface provides an implementation for a member, and that implementation is accessed as the most specific implementation (§most-specific-implementation) for that member" work? (Or am I just splitting hairs? Happy to leave it if everyone else things it's already clear enough.)

2025-09-23 14:54 UTC, jskeet commented on standard/interfaces.md
> +- If `B` contains a method `M` with a different parameter list, that method `M` is a distinct overload of `M`.
Do we need to be more specific than "different" here? Is a parameter list of `(object x)` "different" to a parameter list of `(dynamic x)`? (Hopefully there's another section we can refer to here.)

2025-09-24 18:55 UTC, BillWagner commented on standard/interfaces.md
> +Every interface and class shall have a most specific override for every virtual member declared in all interfaces implemented by that type among the overrides appearing in the type or its direct and
`D` can be used as follows:

```csharp
interface A
{
    void M();
}

interface B : A
{
    void A.M() { }
}

interface C : A
{
    void A.M() { }
}

interface D : B, C
{

}

public class Concrete : D
{
    void A.M() { }
}
```

I'll make an update soon.

2025-09-24 19:01 UTC, BillWagner commented on standard/interfaces.md
> +- The implementation for a member defined in the interface is accessed as the most specific implementation (§most-specific-implementation) for that member.
This needs clarification. 

In the following, the static constructor *is* called:

```csharp
interface I
{
    static I()
    {
        Console.WriteLine("static I()");
    }

    void M() { }
}

class C2 : I
{
}
```

In the following, the static constructor *isn't* called:

```csharp
interface I
{
    static I()
    {
        Console.WriteLine("static I()");
    }

    void M() { }
}

class C2 : I
{
    void I.M()
    {
    }
}
```

(Note the implementation of `I.M()` in `C2`.

2025-09-24 19:20 UTC, jskeet commented
In the meeting, we weren't sure of the behavior of this:

```csharp
class Program
{
    static void Main()
    {
        C c = new C();
        I i = c;

        c.M();
        i.M();
    }
}

interface I
{
    void M() => Console.WriteLine("I.M()");
}

class C : I
{
    public void M() => Console.WriteLine("C.M()");
}
```

It compiles, and prints `C.M()` twice. So it's fine for a class to implement an interface and "override" the default implementation, and it still uses the "override" however it's accessed.

2025-09-24 19:23 UTC, jskeet commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
@BillWagner to consider whether this example is useful or not. (The explanation is not helpful at the moment.)

If not, let's delete it - and the markdownlint-disable following it.

2025-09-24 19:27 UTC, jskeet commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
Maybe just make it "in a concrete class declaration"? But we need to still require the abstract implementation in the class, even when the class is abstract. (Deleting `public abstract void M();` makes the above code fail to compile.)

2025-09-24 19:28 UTC, jskeet commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
Discussion in the meeting - this line is relevant in the following case:

```csharp
interface IF
{
    void M() => Console.WriteLine("I.M()");
}

abstract class AF : IF
{
    public abstract void M();
}

class CF : AF
{
    // This doesn't compile
}
```

2025-09-24 19:30 UTC, BillWagner reviewed
adding comments

2025-09-24 19:30 UTC, BillWagner commented on standard/interfaces.md
> +The inherited members of an interface are specifically not part of the declaration space of the interface. The rules for inheritance in classes (§15.3.4) do not apply to interfaces. The `new` modifie
This should add that members declared in an interface are not inherited by classes implementing that interface.

2025-09-24 19:30 UTC, BillWagner commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
Here's the condition it's trying to cover:

```csharp
interface A
{
    void M() {}
}

public abstract class C : A
{
    public abstract void M();
}

public class D : C, A
{
    // Most specific implementation (C.M) is abstract even though there is an implementation (A.M)
}
```

2025-09-24 19:33 UTC, jskeet commented on standard/interfaces.md
> +### §most-specific-implementation Most specific override
Meeting resolution: most specific implementation is better.

2025-09-24 19:35 UTC, jskeet commented on standard/interfaces.md
> +    | field_declaration
@RexJaeschke to file a follow-on issue - we may want to come back to this, but we're happy to merge this PR as-is without addressing it.

2025-09-24 19:37 UTC, jskeet commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
@BillWagner will consider deleting this sentence entirely, or converting it to a note.

2025-09-24 19:37 UTC, jnm2 commented on standard/interfaces.md
> +The static constructor for a closed interface executes at most once in a given application domain. The execution of a static constructor is triggered by the first of the following actions to occur wi
Where is the term "closed interface" defined? I'm slightly concerned that this language will conflict with the "closed hierarchies" proposal.

2025-09-24 19:38 UTC, jskeet commented on standard/interfaces.md
> +- If `B` contains a method `M` with a different parameter list, that method `M` is a distinct overload of `M`.
@BillWagner will look for appropriate wording.

2025-09-25 21:36 UTC, BillWagner reviewed
I addressed all comments from the 9/25 meeting. I'll resolve relevant conversations.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +> *Note*: Historically, adding a new function member to an interface impacted all existing consumers of that interface type; it was a breaking change. The addition of interface function member implem
I added an HTML comment on this note so our future selves can find it quickly.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +The inherited members of an interface are specifically not part of the declaration space of the interface. The rules for inheritance in classes (§15.3.4) do not apply to interfaces. The `new` modifie
Reverted this paragraph to the existing text. It's all still valid.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M`. As `M` is not abstract, outside that interface or any interface derived from it, that name is not visible. It must be
I updated the explanation to explain the lookup rules.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +The static constructor for a closed interface executes at most once in a given application domain. The execution of a static constructor is triggered by the first of the following actions to occur wi
Added an xref to §8.4.3. In this use, it's meant to mean a type that's not a open type. (`IEnumerable<int>` is a closed type, `IEnumerable<T>` is an open type.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +- Before the Main method is called for an interface containing the Main method ([§7.1](basic-concepts.md#71-application-startup)) in which execution begins.
coming in next commit.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +- The implementation for a member defined in the interface is accessed as the most specific implementation (§most-specific-implementation) for that member.
Updated in next commit. I used Jon's language, after verifying that the static constructor is only called for the interface where the member implementation is. Not for base interfaces nor derived interfaces.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +### §most-specific-implementation Most specific override
coming in next commit.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +It is an error if in a class declaration the most specific override of some interface method is an abstract override that was declared in a class or an interface.
I deleted this sentence and the following example.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +- The expression `base.M()` is valid only if `B` provides a definition for `M`. The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is i
I took Jon's wording in the next commit.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +- The expression `base.M()` is valid only if `B` provides a definition for `M`. The expression `base.M()` is valid only if the most specific implementation (§most-specific-implementation) of `M` is i
I simplified this rule in its entirety.

2025-09-25 21:36 UTC, BillWagner commented on standard/interfaces.md
> +- If `B` contains a method `M` with a different parameter list, that method `M` is a distinct overload of `M`.
I reworded to remove the odd wording requirement.

2025-09-26 02:13 UTC, Nigel-Ecma requested changes, later dismissed
(@BillWagner – you were making updates in parallel so some of my comments may have been preemptively dealt with.)

I will admit I ran out of steam going through all the semantic restrictions on the grammar in `interfaces.md`.

I haven’t checked the grammar does what is expected, or written any tests to add to the grammar checking phase – I will leave both till after this is merged.

I think this is close :-)

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +- An indexer introduced in a class, interface, or struct hides all base class indexers with the same signature ([§7.6](basic-concepts.md#76-signatures-and-overloading)) .
The changes here give interfaces a *base class*. §12.5.2 *Base types* defines the *base types* of an interface as the base interfaces and the class type `object`. Is *base class* for an interface defined somewhere else or are we assuming this covers it?

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/basic-concepts.md
>    - Otherwise, if the *namespace_or_type_name* appears within the body of the type declaration, and `T` or any of its base types contain a nested accessible type having name `I` and `x` type paramete
Can there now not be “more than one such type” yet neither is ”more derived”, so the result is ambiguous? Is this already covered somewhere as there has always been “multiple inheritance” via interfaces?

Scenario:

```csharp
interface A
{
    public class NestedClass { public static void Hello() => …; }
}
interface B
{
    public class NestedClass { public static void Hello() => …; }
}
interface C: A, B
{
    public class Nested
    {
        public void Test() { NestedClass.Hello(); }
    }
}
```

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +- Otherwise, if `Rₚ` refers to a (possibly constructed) class, struct, or interface type and `Rₚ` or any of its base classes contain a nested accessible type having name `I` and `x` type parameters,
See comments on lines 786 & 918 – here we have base classes & most derived

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/classes.md
> +- A nested type that is declared in a class or interface can have any of the permitted kinds of declared accessibility and, like other class members, defaults to `private` declared accessibility.
A class nested in an interface defaults to public, §19.4.1 says all kinds do.

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/basic-concepts.md
>  - Each method declaration, property declaration, property accessor declaration, indexer declaration, indexer accessor declaration, operator declaration, instance constructor declaration, anonymous fu
Comment for lines 271 & 405 – closest I can get with Github…

`protected` is discussed in terms of classes, it is applicable to interfaces and appears to mean accessible in derived interfaces. I haven't consider other accessibilities which might now be allowed.

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§19.4](interfaces.md#194-interface-members). The interface itself may provide an implementation for some or all of the function membe
This does not appear to be quite correct in a well-known implementation:

```csharp
interface A { public string Name { get; } }

interface B : A { pubic string Name { get => "asda"; } }
```

produces a warning re hiding and the use of `new`; of course it works if `B` is a class.

Change the implementation in `B` to be explicit (`string A.Name`) and all is good, so is this just this para not being explicit about being explicit as in line 133?

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/interfaces.md
> +Some declarations, such as *constant_declaration* (§15.4) have no restrictions in interfaces.
This feels a little superfluous as everything that is different is listed, but I also guess its harmless…

2025-09-26 02:13 UTC, Nigel-Ecma commented on standard/interfaces.md
> +- An *indexer_declaration* that has an *expression body* or contains an accessor with a body is `virtual`; the `virtual` modifier is not required, but is allowed.
Maybe:

```suggestion
- An *indexer_declaration* that has an expression body or contains an accessor with a block body is `virtual`; the `virtual` modifier is not required, but is allowed.
```

in other clauses here expression body is not emphasised and block body is used.

2025-09-26 17:20 UTC, BillWagner reviewed
Comments from edits base on Nigel's latest review

2025-09-26 17:20 UTC, BillWagner commented on standard/basic-concepts.md
>  - Each method declaration, property declaration, property accessor declaration, indexer declaration, indexer accessor declaration, operator declaration, instance constructor declaration, anonymous fu
Good catch. Note on the comment: an interface member with `protected` access can be overridden in a class or struct implementing that interface. But, not accessed.

Derived interfaces can access protected members defined in the base interface.

static protected members defined in an interface can be accessed by derived interfaces and implementing classes and structs.

2025-09-26 17:20 UTC, BillWagner commented on standard/basic-concepts.md
>    - Otherwise, if the *namespace_or_type_name* appears within the body of the type declaration, and `T` or any of its base types contain a nested accessible type having name `I` and `x` type paramete
Updated to say this is an error

2025-09-26 17:20 UTC, BillWagner commented on standard/basic-concepts.md
> +- Otherwise, if `Rₚ` refers to a (possibly constructed) class, struct, or interface type and `Rₚ` or any of its base classes contain a nested accessible type having name `I` and `x` type parameters,
Updated in both intstances.

2025-09-26 17:20 UTC, BillWagner commented on standard/classes.md
> +- A nested type that is declared in a class or interface can have any of the permitted kinds of declared accessibility and, like other class members, defaults to `private` declared accessibility.
Removed interface here.

2025-09-26 17:20 UTC, BillWagner commented on standard/interfaces.md
> +Interfaces may contain various kinds of members, as described in [§19.4](interfaces.md#194-interface-members). The interface itself may provide an implementation for some or all of the function membe
Slight word change that helps.

2025-09-26 17:20 UTC, BillWagner commented on standard/interfaces.md
> +    | field_declaration
See #1423

2025-09-26 17:20 UTC, BillWagner commented on standard/interfaces.md
> +Some declarations, such as *constant_declaration* (§15.4) have no restrictions in interfaces.
I don't have strong feelings. I added this so that readers that compare class members with interface members and might think it was an omission.

2025-09-26 17:20 UTC, BillWagner commented on standard/interfaces.md
> +- An *indexer_declaration* that has an *expression body* or contains an accessor with a body is `virtual`; the `virtual` modifier is not required, but is allowed.
This is the one comment where we crossed. They are all consistent now. You can resolve this is you're satisfied with the change.

2025-09-27 17:51 UTC, jnm2 commented on standard/interfaces.md
> +> *Example*: Consider an interface `IA` with an implementation for a member `M` and a property `P`. An implementing type `C` doesn't provide an implementation for either `M` or `P`. They must be acce
```suggestion
> *Example*: Consider an interface `IA` with an implementation for a member `M` and a property `P`. An implementing type `C` doesn't provide an implementation for either `M` or `P`. They must be accessed through a reference whose compile-time type is an interface that is implicitly convertible to `IA` or `IB`. These members aren't found through member lookup on a variable of type `C`.
```

2025-09-27 17:54 UTC, jnm2 commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
Interesting. I intuitively refer to the presence of the semicolon as "having no body." Does the spec have an opinion yet on whether methods with semicolons have "semicolon bodies" or "no bodies"?

2025-09-27 17:55 UTC, jnm2 commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
One nice thing about referring to this as "having no body" is that we can then just say "has a body" instead of saying "has a block body or expression body."

2025-09-27 18:02 UTC, jnm2 commented on standard/interfaces.md
> +- An *indexer_declaration* whose accessors are semi-colons (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
I would say that the accessor is `get;`, not that the accessor is `;`. The accessor has a semi-colon. Per the previous comment, could we adopt the lingo here of "whose accessors have no bodies"?

2025-09-27 18:06 UTC, jnm2 commented on standard/interfaces.md
> +Every class and struct shall have a most specific implementation for every virtual member declared in all interfaces implemented by that type among the overrides appearing in the type or its direct a
I'm finding it confusing to bring in the topic of overrides at all. Do we need to?
```suggestion
Every class and struct shall have a most specific implementation for every virtual member declared in all interfaces implemented by that type among the implementations appearing in the type or its direct and indirect interfaces. The ***most specific implementation*** is a unique implementation that is more specific than every other implementation.
```

2025-09-27 18:08 UTC, jnm2 commented on standard/interfaces.md
> +In a class `D`, with direct or indirect base class `B`, where `B` directly or indirectly implements interface `I` and `I` defines a method `M()`, the expression `base.M()` is valid only if the most s
It's much clearer to say that the validity of `base.M()` depends entirely on whether some base class defines _its own_ member `M()`. Whether or not its own member `M()` is an implementation of some `I.M()` does not affect the validity of `base.M()` one way or another.

2025-09-27 18:11 UTC, jnm2 commented on standard/interfaces.md
> +In a class `D`, with direct or indirect base class `B`, where `B` directly or indirectly implements interface `I` and `I` defines a method `M()`, the expression `base.M()` is valid only if the most s
This is again another case of: interface member names do not appear on classes and structs. An interface member is never available for lookup on a class- or struct-typed expression. A member is available for lookup on a class- or struct-typed expression if, and only if, the class or struct manually declares such a member of its own, accessibly. It may or may not be implementing an interface member in doing so.

2025-09-27 18:16 UTC, jnm2 commented on standard/interfaces.md
> +In a class `D`, with direct or indirect base class `B`, where `B` directly or indirectly implements interface `I` and `I` defines a method `M()`, the expression `base.M()` is valid only if the most s
Also, Here's an example where the expression base.M() is valid, but the most specific implementation of `I.M()` is not in a class type:
```cs
interface I 
{ 
    void M() => Console.WriteLine("impl");
}

class B : I
{
    public Action M => () => Console.WriteLine("Unrelated impl via a property");
}

class D : B
{
    void Example() => base.M(); // This is not I.M();
}
```

2025-09-29 05:16 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
If the last sentence is to be part of the Standard, and not an artefact of some implementation that has crept in, I think it needs elaboration – the class/struct can override but not invoke? So who is being effected given this isn't an inheritance relationship?

2025-09-29 05:18 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +- Protected, which is selected by including a `protected` modifier in the member declaration. The intuitive meaning of `protected` is “access limited to the containing type or types derived from the
Is there a reason to use type rather than class/interface? (As structs are types and are not derived from)

2025-09-29 05:22 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +  - Otherwise, if the *namespace_or_type_name* appears within the body of the type declaration, and `T` or any of its base types contain a nested accessible type having name `I` and `x` type paramete
The “, as in the case if nested types declared in multiple interfaces” doesn’t make sense as is – it has to be types with the same name, and is an example so I think should be marked as such.

2025-09-29 05:23 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +- Otherwise, if `Rₚ` refers to a (possibly constructed) class, struct, or interface type and `Rₚ` or any of its base types contain a nested accessible type having name `I` and `x` type parameters, th
See comment on line 918

2025-09-29 05:45 UTC, Nigel-Ecma commented on standard/interfaces.md
> +- An *indexer_declaration* that has an *expression body* or contains an accessor with a body is `virtual`; the `virtual` modifier is not required, but is allowed.
@BillWagner I’m not seeing changes on this line or similar ones on the other clauses so they remain inconsistent. I've reloaded the page etc. so has GitHub messed up?

2025-09-29 05:56 UTC, Nigel-Ecma commented on standard/interfaces.md
> +- An *indexer_declaration* whose accessors are semi-colons (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
@jnm2 – I understand where you’re coming from here, and most people probably think of a semicolon as “no body”. It would be great if indeed there was no body, but for syntax reasons there is – a semicolon.

To change I think wherever there is a semicolon body in the grammar it would need to change to something stating that this is referred to as having no body, and in other places state that having a block or expression is referred to as having a body, etc. 

it is a bit ugly as is, but it is precise, is it worth changing?

If you do decide to do a PR (post 8/pre 9?) I’ll agree to review, and I'll reserve my answer to whether it is worth it till then ;-)

2025-09-29 12:16 UTC, jnm2 commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
The class/struct can't invoke directly, i.e. the interface member name is not available for lookup in the class/struct scope, and the class/struct can't simply cast `this` to the interface type and call the protected member because protected names arent available for lookup there either.

But if the class/struct itself, or anyone else, casts the class/struct to an interface type and calls a public interface member which has a DIM, that DIM may call the protected member, and this may invoke the class/struct implementation of the protected interface member.

2025-09-29 22:55 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
@jnm2 – Bravo, taking a wrong turn along that route would be easy! 😉

Seriously, this surely modifies the C# protection model – where else can you override a member you cannot access?

To save us, a possibly fruitless, search for the design and/or use case documentation for this feature can you provide a link or two?

We need to know this is “by design”, and probably include an example as a reader thinking along the lines of the usual C# protection model might think they’ve misread this.

Or am I missing something obvious?

2025-09-30 03:20 UTC, Nigel-Ecma commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
Due to timezones most of you are asleep and I’m filling in the end of the day… so I grabbed a few docs:

1. [default interface methods](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/default-interface-methods.md) – the proposal
2. [Issues in Default Interface Methods](https://github.com/dotnet/csharplang/issues/406) – open issues referenced by (1), since all closed
3. [default interface methods](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods) – public version of (1) dated 8 Dec 2022 (so fairly recent)

(1) & (3) have 7 open issues, including:

> ***Open Issue:*** We need to specify the precise meaning of the access modifiers such as `protected` and `internal`, and which declarations do and do not override them (in a derived interface) or implement them (in a class that implements the interface).

They both also have an *Unresolved questions* section, including:

> The detailed specification must describe the resolution mechanism used at runtime to select the precise method to be invoked.

Finally they both have an *Overriding non-public interface members* section, including:

> You can only implement non-public interface members explicitly. (With ref to [LDM](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-04-18.md#dim-implementing-a-non-public-interface-member-not-in-list))

The added sentence above does nor mention explicitly.

This quick scan has left me with more questions, like are all the open issues resolved in this draft, and a hope someone has checked & resolved all this. Standards don’t have unresolved issues such as these.

2025-09-30 21:08 UTC, BillWagner reviewed
Updated for most review comments.
I did some investigation for https://github.com/dotnet/csharpstandard/pull/681/files#r2386725345

My notes are the last comment in that thread.

2025-09-30 21:08 UTC, BillWagner commented on standard/basic-concepts.md
> +- Protected, which is selected by including a `protected` modifier in the member declaration. The intuitive meaning of `protected` is “access limited to the containing type or types derived from the
I started with "class or interface", but then ended up with this hard to parse text. Happy for any wordsmithing that improves accuracy is doesn't have nested "or" lists.

```suggestion
- Protected, which is selected by including a `protected` modifier in the member declaration. The intuitive meaning of `protected` is “access limited to the containing class or interface, or classes or interfaces derived from the containing type”.
```

2025-09-30 21:08 UTC, BillWagner commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
@Nigel-Ecma  What do you think of turning Joseph's comment into an example? Would that satisfy your concerns?

2025-09-30 21:08 UTC, BillWagner commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
I like this. 

I think this phrasing is throughout the spec because in the dawn of time, every body was a "block body". Now that there are both expression bodies and block bodies, it might worth making an issue to define "a body" as either a "block body" or an "expression body" and then use that term.

I don't think this should block C# 8, but is a good future fix.

Thoughts from the committee as a whole?

2025-09-30 21:08 UTC, BillWagner commented on standard/interfaces.md
> +- An *indexer_declaration* that has an *expression body* or contains an accessor with a body is `virtual`; the `virtual` modifier is not required, but is allowed.
Updated. Again, this is one of those places where we need both "block body" and "expression body" here.

See https://github.com/dotnet/csharpstandard/pull/681/files#r2384262560 and replies.

2025-09-30 21:08 UTC, BillWagner commented on standard/interfaces.md
> +- An *indexer_declaration* whose accessors are semi-colons (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
For this PR, I did update the text to say "whose accessor bodies are `;`" rather than "whose accessors are `;`"

2025-09-30 21:08 UTC, BillWagner commented on standard/interfaces.md
> +In a class `D`, with direct or indirect base class `B`, where `B` directly or indirectly implements interface `I` and `I` defines a method `M()`, the expression `base.M()` is valid only if the most s
Changed to reference binding, and specify that it binds to a class member.

2025-09-30 21:08 UTC, BillWagner commented on standard/basic-concepts.md
> +  - Otherwise, if the *namespace_or_type_name* appears within the body of the type declaration, and `T` or any of its base types contain a nested accessible type having name `I` and `x` type paramete
Removed that phrase, and added an example.

2025-09-30 21:08 UTC, BillWagner commented on standard/basic-concepts.md
> +- Otherwise, if `Rₚ` refers to a (possibly constructed) class, struct, or interface type and `Rₚ` or any of its base types contain a nested accessible type having name `I` and `x` type parameters, th
Same fix as line 918.

2025-09-30 21:08 UTC, BillWagner commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
I did more initial digging today. I think this has gone off the rails in part because we've been thinking of this in terms of deltas from what was allowed. It might be better to treat this with a holistic look at classes, interfaces, and structs:

First a correction:  Our recent discussions have added notes that a class can use implicit interface implementation for non-public interface methods. That's only true in C# 10 and later! I'll be making updates for that, and adding an HTML comment so we remember.

I think I can rework the rules along the following lines:

First, in member lookup (12.5). (Not standard language yet):

> If the receiver is a class or struct type, public members implemented by an implemented interface by not implicitly implemented by the class or base class are removed from the set.
> This rule includes `this`, meaning that the body of a class can't access members of an interface that are explicitly implemented. (Note that this is true prior to C# 8, but it's meaning now also includes all non-public interface members.

Next, as far as a class or struct implementing an interface member (updates to 19.6): (Yes, this also needs wordsmithing)

- A concrete class or struct must provide or inherit all members of all interfaces it implements (already a rule)
- `public` members of an interface may be implicitly or explicitly implemented by a class.
- A class, struct, or interface, may override any accessible member declared in an interface in inherits or implements.
- A non-public member of an interface must be explicitly implemented by a class or struct. (This restriction needs to be added in 19.6.3).
- A matching member that isn't an explicit implementation introduces a `new` method.

2025-10-02 15:16 UTC, BillWagner commented
@Nigel-Ecma @jnm2 

The changes in the latest commit address the concepts in https://github.com/dotnet/csharpstandard/pull/681#discussion_r2392837875

The significant changes in the last commit:

- In 19.6.1, Lines 721 - 724:  Add rules for interface member implementation on public, non-public, and non-accessible interface members.
- In 19.6.2, Lines 795-796:  Add requirement that non-public interface members can only be overridden using explicit interface members.
- I didn't update 12.5.1 (lookup rules) because I think lines 377-378 already does what we need:
> - If `M` is a constant, field, property, event, enumeration member, or type declaration, then all members declared in an interface declaration are removed from the set.
> - If `M` is a method, then all non-method members declared in an interface declaration are removed from the set, and all methods with the same signature as `M` declared in an interface declaration are removed from the set.

2025-10-12 14:58 UTC, KalleOlaviNiemitalo commented on standard/interfaces.md
> +It is an error to declare a class type, struct type, or enum type within the scope of a type parameter that was declared with a *variance_annotation* ([§19.2.3.1](interfaces.md#19231-general)).
This may require changing the wording in §7.7.1 (Scopes / General).  In the following, the outer `T` is hidden by the inner `T`.

```csharp
interface IOuter<out T>
{
    interface IInner<T>
    {
        class C { }
    }
}
```

§7.7.1 currently says:

> The ***scope*** of a name is the region of program text within which it is possible to refer to the entity declared by the name without qualification of the name. Scopes can be *nested*, and an inner scope may redeclare the meaning of a name from an outer scope. (This does not, however, remove the restriction imposed by §7.3 that within a nested block it is not possible to declare a local variable or local constant with the same name as a local variable or local constant in an enclosing block.) The name from the outer scope is then said to be ***hidden*** in the region of program text covered by the inner scope, and access to the outer name is only possible by qualifying the name.

Within the definition of `interface IInner<T>` , it is not possible to refer to the `T` type parameter of `IOuter`.  According to this wording then, the definition of `class C` is not in the scope of the outer `T`.

2025-10-12 15:03 UTC, KalleOlaviNiemitalo commented on standard/interfaces.md
> +It is an error to declare a class type, struct type, or enum type within the scope of a type parameter that was declared with a *variance_annotation* ([§19.2.3.1](interfaces.md#19231-general)).
Alternatively, this might be solved by adding "including any nested scopes" to the restriction here.

2025-10-20 00:40 UTC, Nigel-Ecma commented on standard/interfaces.md
> +A class or struct `C` that implements an interface `I` must provide or inherit an implementation for every member declared in `I`. Public members of `I` may be defined in public members of `C`. Non-p
This starts off with “must provide or inherit an implementation for *every* member declared in `I`” (emphasis added), then says how some of these members may be given implementations, and ends with “Non-accessible members, such as `private` members of `I` can't be defined in `C`” – should this last statement say something along the lines that in this case an implementation must be inherited (or something else)?

2025-10-20 13:47 UTC, jskeet reviewed
I've reviewed the changes as best I can, one commit at a time... but it's getting really tricky. (Things I've noticed in one commit have been fixed in a later one.)

I think we should aim to merge the PR as-is by the end of the upcoming meeting, with comments for things that still need resolving - it'll make it *much* easier to review. The downside is it'll be harder to see "the totality of changes for this feature" of course.

2025-10-20 13:47 UTC, jskeet commented on standard/interfaces.md
> +If a `new` modifier is included in a declaration that doesn’t hide an inherited member, a warning is issued to that effect. This warning is suppressed by removing the `new` modifier.
Perhaps "resolved" rather than "suppressed"? (Possibly the same a couple of lines ago.)

I tend to think that "suppressing" a warning is a matter of "I know there's something that the compiler thinks is wrong, but I know better" - whereas here it's really a matter of the whether the declarations are clear and "correct". (Not a great way of putting it, but I hope folks see where I'm coming from.)

2025-10-20 13:47 UTC, jskeet commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
I like it (@jnm2's perspective), myself.

2025-10-20 13:47 UTC, jskeet commented on standard/interfaces.md
> +> The most specific implementation rule ensures that a conflict (i.e., an ambiguity arising from diamond inheritance) is resolved explicitly by the programmer at the point where the conflict arises.
Is a conflict *always* due to diamond inheritance?

2025-10-20 13:47 UTC, jskeet commented on standard/basic-concepts.md
> +- Protected, which is selected by including a `protected` modifier in the member declaration. The intuitive meaning of `protected` is “access limited to the containing type or types derived from the
I'd personally prefer to stick to type here because it's simpler. Yes, you can't derive from a struct - but you can't derive from a sealed class either. Basically I think it all *works* with "containing type" so let's stick to the minimal number of concepts and let other bits of the spec deal with whether there can be a type derived from the containing type.

What's *not* clear from here is that it's the *program text* of the containing type - so if I have a nested type within the containing type, I get access to protected members. I don't think that's clear without being called out. (I thought we already had it, but apparently not...)

2025-10-20 19:53 UTC, Nigel-Ecma commented
I agree with @jskeet:

> I've reviewed the changes as best I can, one commit at a time... but it's getting really tricky. (Things I've noticed in one commit have been fixed in a later one.)
> 
> I think we should aim to merge the PR as-is by the end of the upcoming meeting, with comments for things that still need resolving - it'll make it _much_ easier to review. The downside is it'll be harder to see "the totality of changes for this feature" of course.

@BillWagner – could you please tag the draft-v8 branch before & after you merge this so we can check out the two commits locally & diff them to see "the totality of changes for this feature"? Of course we can do such diffs anyway, the tags just save locating the commit UUIDs.

2025-10-21 14:00 UTC, BillWagner commented on standard/interfaces.md
> +A class or struct `C` that implements an interface `I` must provide or inherit an implementation for every member declared in `I`. Public members of `I` may be defined in public members of `C`. Non-p
This might be better handled in another PR.  The rules in this PR state that an interface that declares a private member must provide a definition for that member. It's inaccessible to any derived interface or class, or struct that implements the interface.

It might be that this can just remove removed. Otherwise, it should relate to those rules as well.

2025-10-21 14:01 UTC, BillWagner commented on standard/interfaces.md
> +> The most specific implementation rule ensures that a conflict (i.e., an ambiguity arising from diamond inheritance) is resolved explicitly by the programmer at the point where the conflict arises.
It would be some configuration that has two different paths through implemented interfaces where some base interface is included twice. So, yes, if we believe a diamond isn't strictly 4 vertices. 

Given that this is informative, I think it's fine.

2025-10-21 20:06 UTC, Nigel-Ecma commented on standard/interfaces.md
> +A class or struct `C` that implements an interface `I` must provide or inherit an implementation for every member declared in `I`. Public members of `I` may be defined in public members of `C`. Non-p
@BillWagner – Maybe:

```suggestion
A class or struct `C` that implements an interface `I` must provide or inherit an implementation for every member declared in `I` that `C` can access. Public members of `I` may be defined in public members of `C`. Non-public members declared in `I` that are accessible in `C` may be defined in `C` using explicit interface implementation (§19.6.2).
```

or something like that? (Fixed a typo as well that I just spotted.)

2025-10-22 19:10 UTC, jskeet commented on standard/interfaces.md
> +> The most specific implementation rule ensures that a conflict (i.e., an ambiguity arising from diamond inheritance) is resolved explicitly by the programmer at the point where the conflict arises.
Fine by me.

2025-10-22 19:12 UTC, BillWagner commented on standard/interfaces.md
>  If a `new` modifier is included in a declaration that doesn’t hide an inherited member, a warning is issued to that effect. This warning is suppressed by removing the `new` modifier.
```suggestion
If a `new` modifier is included in a declaration that doesn’t hide an inherited member, a warning is issued to that effect.
```

2025-10-22 19:13 UTC, jskeet commented on standard/interfaces.md
>  If a `new` modifier is included in a declaration that doesn’t hide an inherited member, a warning is issued to that effect. This warning is suppressed by removing the `new` modifier.
```suggestion
If a `new` modifier is included in a declaration that doesn’t hide an inherited member, a warning is issued to that effect.
```

2025-10-22 19:13 UTC, jskeet commented on standard/interfaces.md
> +The inherited members of an interface are specifically not part of the declaration space of the interface. Thus, an interface is allowed to declare a member with the same name or signature as an inhe
```suggestion
The inherited members of an interface are specifically not part of the declaration space of the interface. Thus, an interface is allowed to declare a member with the same name or signature as an inherited member. When this occurs, the derived interface member is said to *hide* the base interface member. Hiding an inherited member is not considered an error, but it does result in a warning (§7.7.2.3).
```

2025-10-22 19:22 UTC, jnm2 commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
I see the term `override` showing up here again.

2025-10-22 19:25 UTC, BillWagner commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
```suggestion
When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outside the program text of the program in which it is declared, the access shall take place within a class declaration that derives from the class in which it is declared. Furthermore, the access is required to take place *through* an instance of that derived class type or a class type constructed from it. This restriction prevents one derived class from accessing protected members of other derived classes, even when the members are inherited from the same base class. Instance interface members defined with `protected` or `private protected` access cannot be accessed from a `class` or `struct` that implements that interface; these can be accessed only from derived interfaces. However, `class` and `struct` types can define overridden `protected` instance members declared in an interface it implements.
```

2025-10-22 19:27 UTC, jskeet approved these changes

2025-10-22 19:27 UTC, merged

2025-10-22 19:48 UTC, jnm2 commented on standard/interfaces.md
> +- An *indexer_declaration* whose accessors are semi-colons (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
Opened https://github.com/dotnet/csharpstandard/issues/1430 to track this suggestion further.

2025-10-22 19:49 UTC, jnm2 commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
Opened https://github.com/dotnet/csharpstandard/issues/1430 to track this suggestion further.

2025-10-23 01:59 UTC, jnm2 commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
@BillWagner I think this is "**can implement** protected instance members declared in an interface" instead of "**can define overridden**" since we're not using the word "override" to describe providing a more specific implementation.

2025-10-23 02:05 UTC, jnm2 commented on standard/basic-concepts.md
> +When a `protected` or `private protected` instance member is accessed outside the program text of the class in which it is declared, and when a `protected internal` instance member is accessed outsid
It's probably also worth not just saying "can implement," but more precisely "can explicitly implement"; implicit implementation of nonpublic interface members is not allowed until C# 10.

2025-10-23 16:11 UTC, BillWagner commented on standard/interfaces.md
> +- A method whose body is a semi-colon (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
Logged as #1434

2025-10-23 16:12 UTC, BillWagner commented on standard/interfaces.md
> +- An *indexer_declaration* whose accessors are semi-colons (`;`) is `abstract`; the `abstract` modifier is not required, but is allowed.
See #1434