specify the result of identity conversions for tuples and dynamic
dotnet/csharpstandard pull request #821
Opened 2023-06-22 19:29 UTC by BillWagner

Identity conversions exist between `object` and `dynamic`. Also, an identity conversion exists between tuple types of the same arity with the same element types in the same ordinal locations. Specify that `dynamic` is preferred for type inference between `dynamic` and `object`. Specify that optional element names are carried only when both source tuple types contain the same optional element names.

Fixes #803

2023-06-22 19:30 UTC, BillWagner commented
Tagging all committee members for review. I'd hope we can review this and merge before or at the next meeting.

2023-06-23 04:06 UTC, Nigel-Ecma requested changes
Minor typo, otherwise LGTM

2023-06-23 04:06 UTC, Nigel-Ecma commented on standard/statements.md
> +In the context of a local variable declaration, the identifier `var` acts as a contextual keyword ([§6.4.4](lexical-structure.md#644-keywords)).When the *local_variable_type* is specified as `var` an
Just a missing space…

```suggestion
In the context of a local variable declaration, the identifier `var` acts as a contextual keyword ([§6.4.4](lexical-structure.md#644-keywords)). When the *local_variable_type* is specified as `var` and no type named `var` is in scope, the declaration is an ***implicitly typed local variable declaration***, whose type is inferred from the type of the associated initializer expression. When the initializer expression is a tuple type (§8.3.11), type inference includes any optional element names. Implicitly typed local variable declarations are subject to the following restrictions:
```

2023-06-25 09:45 UTC, Nigel-Ecma approved these changes
LGTM

2023-06-27 08:03 UTC, jskeet approved these changes
Generally fine - one nitpick.

2023-06-27 08:03 UTC, jskeet commented on standard/statements.md
> +In the context of a local variable declaration, the identifier `var` acts as a contextual keyword ([§6.4.4](lexical-structure.md#644-keywords)). When the *local_variable_type* is specified as `var` a
Should this be "when the type of the initializer expression is a tuple type"? Or possibly just "when the inferred type is a tuple type, type inference includes any optional element names"?

2023-06-27 10:49 UTC, Nigel-Ecma commented on standard/statements.md
> +In the context of a local variable declaration, the identifier `var` acts as a contextual keyword ([§6.4.4](lexical-structure.md#644-keywords)). When the *local_variable_type* is specified as `var` a
Good point, the expression “is a tuple” or “has a tuple type”, it is not “a tuple type”. To add to @jskeet’s I’ll offer the smallest fix – change “is” to ”has” – but smallest doesn’t mean better, take your pick.

2023-07-12 20:24 UTC, jskeet commented on standard/statements.md
> +In the context of a local variable declaration, the identifier `var` acts as a contextual keyword ([§6.4.4](lexical-structure.md#644-keywords)). When the *local_variable_type* is specified as `var` a
After discussion, we think that this file change can be reverted entirely - it flows from the element names being part of the type.

2023-07-13 15:36 UTC, BillWagner reviewed
Adding notes from 7/13 meeting.

2023-07-13 15:36 UTC, BillWagner commented on standard/expressions.md
> +  - If an identity conversion exists between `X` and `Y`, then the result can be either type. If either type is `dynamic`, type inference prefers `dynamic` ([§8.7](types.md#87-the-dynamic-type)). If
This needs to be updated to perform recursive "best common type" on each member of tuple type or a constructed type. It may be that best common type already supports this for tuples and constructed types and could be referenced.

2023-07-13 15:36 UTC, BillWagner commented on standard/expressions.md
> +  - If an identity conversion exists between `X` and `Y`, then the result can be either type. If either type is `dynamic`, type inference prefers `dynamic` ([§8.7](types.md#87-the-dynamic-type)). If
Notes on what needs to change here:

Line 4734 needs to change as follows:

```suggestion
  - If an identity conversion exists between `X` and `Y`, then the result is the best common type of a set of expressions (§12.6.3.15).  If either type is `dynamic`, type inference prefers `dynamic` ([§8.7](types.md#87-the-dynamic-type)). If either type is a tuple type (§8.3.11), type inference includes the element names when the element names in the same ordinal position match in both tuples.
```

However, there's more:

[8.7](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/types.md#87-the-dynamic-type) states that if both `dynamic` and `object` are candidates, type inference prefers `dynamic`. Can that sentence be deleted here? Or should it be a note?

[12.6.3.15](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions) relies on [12.6.3.7](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#12637-output-type-inferences) (output type inference) and then [12.3.6.10](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#126310-lower-bound-inferences) (lower bound inference) and finally [12.3.6.9](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#12639-exact-inferences) (exact inferences) to find the best common type.  None of those mention tuple types.

Therefore, I think 12.3.6.9 should be edited to include a new nested bullet point as follows:

> - `V` is a tuple type and `U` is a tuple type of the same arity and an identity conversion exists between each corresponding element type. 

/cc @MadsTorgersen @jcouv

2023-08-07 15:26 UTC, jskeet commented
Can this now be merged?

2023-08-07 18:35 UTC, BillWagner commented
> Can this now be merged?

I think so. I'd made the requested updates after our July meeting. Worth a quick look at to make sure I didn't miss anything though.

2023-08-08 07:28 UTC, jskeet commented
Looks good - merging now.

2023-08-08 07:29 UTC, merged