Restrict usage of stack allocation expression
dotnet/csharpstandard pull request #840
Opened 2023-07-08 15:48 UTC by RexJaeschke

V7 restricts the contexts in which a *stackalloc_expression* may appear. However, these restrictions were inadvertently lost during the review of that feature's PR.

**As it happens, V8 removes those restrictions.**

In order for V7 to actually track the V7 implementation, this PR adds those restrictions. The committee can decide if it wishes to do this or to abandon this PR.

2023-07-11 08:45 UTC, jskeet approved these changes
I haven't validated the changes against any other spec, but they seem reasonable. Will look forward to the reversion PR when we've shipped v7 :)

2023-07-12 17:51 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
Can you show a valid program in which a *stackalloc_expression*  is the right operand of an *assignment_operator*?

```csharp
using System;
class C {
    void M() {
        Span<int> span1 = stackalloc int[1]; // OK, but that's not an *assignment_operator*.

        Span<int> span2;
        span2 = stackalloc int[1]; // error CS8353: A result of a stackalloc expression of type 'Span<int>' cannot be used in this context because it may be exposed outside of the containing method
    }
}
```

2023-07-12 17:53 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
Older discussion about `stackalloc` near <https://github.com/dotnet/csharpstandard/pull/238#discussion_r775168419>, but this error CS8353 thing should be addressed first.

2023-07-12 17:57 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
Assignment doesn't work with a pointer, either:

```csharp
unsafe class C {
    void M() {
        int* ptr1 = stackalloc int[1]; // OK, but that's not an *assignment_operator*.

        int* ptr2;
        ptr2 = stackalloc int[1]; // error CS8346: Conversion of a stackalloc expression of type 'int' to type 'int*' is not possible.
    }
}
```

2023-07-12 18:05 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
Perhaps the rule should be something like this:

> A *stackalloc_expression* shall be used in the following contexts only:
>
> - As the initializer of a local variable.
> - As the second and/or third operand of a *conditional_expression* that is in a context where *stackalloc_expression* would be permitted.

2023-08-04 17:15 UTC, RexJaeschke commented
@Bill, can you please look at Kalle's feedback?

2023-08-04 19:06 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
The above would not allow `Span<int> span = (Span<int>)stackalloc int[1];`, which should be allowed.  However, if one just added a third allowed context:

> * As the operand of a *cast_expression* that is in a context where *stackalloc_expression* would be permitted.

then that might also allow `int* ptr = (int*)stackalloc int[1];`, which should not be allowed.  I write "might" because I have not checked whether the draft already includes some other text that disallows this.

The impression I get is that a `stackalloc_expression` preferentially converts to `Span<T>`, and the conversion to `T*` is only available in an initializer of a variable of type `T*`.

2023-08-04 19:19 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
> a valid program in which a _stackalloc_expression_ is the right operand of an _assignment_operator_

Perhaps like this... although I'm not sure whether this is valid in C# 7 or only C# 8

```csharp
using System;
public class C {
    public void M() {
        C c;
        c = stackalloc int[1];
    }
    
    public static implicit operator C(Span<int> span) => null;
}
```

2023-08-04 19:51 UTC, BillWagner commented
@RexJaeschke @KalleOlaviNiemitalo 

I looked at this, and I wonder if the answer could be simpler if we leverage the grammar.

In the current v7 spec, a *stackalloc_initializer* is one of the productions allowed in a *primary_no_array_creation_expression*.  

In earlier versions, the *stackalloc_initializer* is one of productions allowed in a *local_variable_initializer*. 

That's the main change in the [feature spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/nested-stackalloc.md) for the v8 feature. (Note that the feature spec relies on the v6 spec, where stackalloc is only allowed in the *local_variable_initializer_unsafe* production. Otherwise, the change is the same.

Would the same change work here?

/cc @Nigel-Ecma for a check of my grammar analysis.

Background:  While trying some constructs, the following is legal C# 8, but not legal C# 7.3:

```csharp
internal class Program
{
    private static void Main(string[] args)
    {
        M(stackalloc int[5]); // error stackalloc not allowed in nested expressions.
    }

    private static void M(Span<int> span)
    {
    }
}
```

2023-08-05 08:29 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
> +- The right operand of an *assignment_operator* that is not embedded in some larger expression.
Again not sure about C# 7 vs 8:

```csharp

unsafe struct C {
    static void M() {
        C c1 = stackalloc int[1]; // OK
        C c2 = (C)stackalloc int[1]; // error CS8346
        C c3 = (stackalloc int[1]); // error CS8346
    }
    
    public static implicit operator C(void* ptr) => default;
}
```

2023-08-07 15:31 UTC, jskeet commented
@BillWagner: Could you take a look at @KalleOlaviNiemitalo's comments? This area is one I find confusing.

2023-08-07 15:52 UTC, KalleOlaviNiemitalo commented on standard/expressions.md
>  A stack allocation initializer of the form `stackalloc T[E]` requires `T` to be an *unmanaged_type* and `E` to be an expression implicitly convertible to type `int`. The operator allocates `E * sizeo
Does anything specify the Length of the resulting Span\<T\>?    The T\* does not have that information.

It might be better to specify stackalloc this way

1. the result of the stackalloc expression is a Span\<T\> whose length is exactly E or the number of expressions in the stackalloc element initialiser list, and which describes newly allocated memory (the actual allocation might be larger than  this span, e.g. for stack alignment)
1. If there is an initialiser list, then the expressions are evaluated and the results stored to elements of the span
1. If the stackalloc expression is an initialiser of a local variable and there is syntactically nothing else in the initialiser (not even parentheses), then the span can be converted to a T* that points to the first element.  (Does this require `unsafe` context at the variable declaration even if the variable does not have pointer type?)

2023-08-10 04:37 UTC, Nigel-Ecma requested changes
As others have discussed, the restrictions in 7.3 seem a little more involved. I also noted there was some (not always agreeing) duplication, due I expect to mixing text from the unsafe code section. At this point Github beat me and I couldn’t add the changes as comments so I’ve made PR #885 to address 7.3 and do some de-duplication – it's opening comment is my "review". Continue here or switch to #885 as folk decide.

2023-08-14 19:41 UTC, BillWagner commented
closed in favor of #885

2023-08-14 19:41 UTC, closed without merging

2023-08-14 20:40 UTC, Nigel-Ecma commented on standard/expressions.md
>  A stack allocation initializer of the form `stackalloc T[E]` requires `T` to be an *unmanaged_type* and `E` to be an expression implicitly convertible to type `int`. The operator allocates `E * sizeo
@KalleOlaviNiemitalo – That error probably came from copying text for the unsafe section. Fixed in PR #888. Thanks for spotting this.