Add support for new pattern kinds
dotnet/csharpstandard pull request #873
Opened 2023-08-04 17:54 UTC by RexJaeschke

**This PR is 99% incomplete. Once V7 has been completed and the branch draft-v8 has been rebased to the final V7, I will add the edits to the patterns, expressions, and statements chapters.**

Prior to V8, we have a term “switch expression” defined as the *expression* inside parens in a `switch` statement.

Now, we’re introducing a switch as an expression, and we have a new grammar rule called *switch_expression*. The difference between “switch expression” (without a \*…\* fence or separating underscore) and \*switch_expression\* likely is too subtle. So, how to differentiate them?

Although C calls such a switch expression a “controlling expression” (and uses that term as well for `if`, `while`, `for`, and `do` statements), we already state, “The ***governing type*** of a `switch` statement is established by the switch expression.” As such, I have replaced all occurrences of “switch expression” (which exist only in the statements chapter) with “switch’s governing expression.”

2023-09-25 14:16 UTC, BillWagner commented
Successfully rebased on the updated `draft-v8` branch on 09/25/2023

2023-10-27 10:01 UTC, Nigel-Ecma requested changes
I haven't managed to work my way through all of this yet but am submitting what I have so far. Overall this seems to have carried over too much non-Standardese from the original proposals and some issues repeating/rewording stuff already in the Standard.. There are also grammar issues that may break expression parsing…

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Something has gone wrong here:

1. *range_expression* does not appear to be defined anywhere
2. it appears the intention is to slot *switch_expression* between *multiplicative_expression* & *unary_expression* in the expression hierarchy, if this is the case then *switch_expression* needs to include *unary_expression* so as not to break the grammar layering

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/expressions.md
> +    | multiplicative_expression '%' switch_expression
Something has gone wrong here, see comment on line 3565 above

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` involved `is`; either might be a valid parse of a qualified identifier. In such a case, only
The preceding note on line 4085 needs work and is covered under issue #935. This note also needs work (style, “first thing found”, etc.) and is related so maybe should be covered under #935 as well; i.e. remove it here and add a comment to #935.

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/expressions.md
> +Every *identifier* of the pattern introduces a new local variable that is definitely assigned once the corresponding *relational_expression* tests `true`.
“…assigned *if* the…” maybe? "Once" sounds like it is a temporal thing waiting on the relational expression to become true.

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *positional_pattern* checks that the input value is not `null`, invokes an appropriate `Deconstruct` method ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on th
This feels like it is repeating stuff which is (or should be, e.g. `System.ITuple` is not in §12.7 at present) in §12.7 Deconstruction and this here should be something like:

> A *positional_pattern* checks that the input value is not `null`, performs a deconstruction ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on the resulting values.

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/patterns.md
> +> *Note*: The ordering of the grammar rules in *simple_designation* is important. By putting *discard_designation” first, the source token `_` is recognized as a discard rather than as a named identi
We have not previously specified that the alternatives in a C# grammar rule are ordered, even though we use ANTLR as a notation. Rather we have specified a disambiguation rule, and sometimes a note saying ANTLR semantics give an implementer a free implementation of the rule; e.g. in §12.19.1 we have:

> When recognising an *anonymous_function_body* if both the *null_conditional_invocation_expression* and *expression* alternatives are applicable then the former shall be chosen.
>
> *Note*: The overlapping of, and priority between, alternatives here is solely for descriptive convenience; the grammar rules could be elaborated to remove the overlap. ANTLR, and other grammar systems, adopt the same convenience and so *anonymous_function_body* has the specified semantics automatically. *end note*

This note here should either be re-written in our current style or we should re-consider how we describe overlapping/ambiguous alternatives and re-write them all to consistent to whatever we decide.

2023-10-27 10:01 UTC, Nigel-Ecma commented on standard/patterns.md
> +With regard to the order of evaluation of operations and side effects during pattern-matching, an implementation is permitted to reorder calls to `Deconstruct`, property accesses, and invocations of
Line 192 below says the order is not specified, so an implementation cannot “reorder” – it just picks an order. What the Standard needs to say is that the order of operations, and any resulting side effects, is implementation defined/specified or unspecified (whichever term from the collection is appropriate here).

The last sentence (“The implementation should not invoke functions that cannot affect the result”) is either redundant or should be a Note.

2023-10-29 16:01 UTC, RexJaeschke commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
*range_expression* is defined by the V8 PR #605, "Add Support for Indexers and Ranges," which has not yet been merged.

2023-10-29 22:23 UTC, Nigel-Ecma commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Thanks @RexJaeschke. From #605 we have:

> ```ANTLR
> range_expression
>     : unary_expression
>     | range_expression? '..' range_expression?
>     ;
> ```

This does connect to *unary_expression* but the grammar is still broken. The *switch_expression* grammar allows for empty braces,`switch { }`, which doesn’t seem right, was the intended grammar:

```ANTLR
switch_expression
    : range_expression ( 'switch' '{' (switch_expression_arms ','? '}' )?
    ;
```

I haven't checked that all fits (see next para) but it makes a bit more logical sense and should at least fix the layering issue.

Also how is `e switch { ... } switch { ... }` to be handled, if at all? I.e. using one switch to provide the value to switch on for a second (third, …) one? Something like:

```ANTLR
switch_expression
    : range_expression
    | switch_expression ( 'switch' '{' (switch_expression_arms ','? '}' )?
    ;
```

might be wanted, but that is left-recursive… Requiring parentheses (`(e switch { ... }) switch { ... }` is another option.

2024-07-10 04:45 UTC, Nigel-Ecma commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Fix to my own comment of Oct 30, 2023: It doesn’t matter if the rule is left recursive *per se*. While we avoid it when not required, left/right recursion is the way left/right associativity is represented.

So the question here is how should `switch { … } switch { … } switch { … }` associate, if it is supported?

Probably right associative surely?

Once supported/associtivity is decided the grammar will follow≥ (famous last words ;-))

(I haven’t checked what any implementation does)

2024-12-16 22:04 UTC, gafter requested changes

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +With regard to the order of evaluation of operations and side effects during pattern-matching, an implementation is permitted to reorder calls to `Deconstruct`, property accesses, and invocations of
In code such as
```csharp
var x = e switch {
    A(1, 2) => 1
    _       => 1
}
```
Is the compiler allowed to get the properties and test the values of `A`, or is that not allowed because it does not affect the 'result'?

How normative is a 'should' and what is a 'result'?

2024-12-16 22:04 UTC, gafter commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` involved `is`; either might be a valid parse of a qualified identifier. In such a case, only
```suggestion
> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` on the right-hand-side of `is`; either might be a valid parse of a qualified identifier. In such a case, only if it fails to bind as a type (for compatibility with previous versions of the language), is it resolved to be the first thing found (which must be either a constant or a type). This ambiguity is only present on the right-hand side of such an expression.
```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
```suggestion
A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-statement)), and in a *switch_expression* (§switch-expression-new-clause) to express the shape of data against which incoming data is to be compared. Patterns may be recursive, so that parts of the data may be matched against ***sub-patterns***.

A pattern is tested against a value in a number of contexts:
- In a switch statement, the *pattern* of a case label is tested against the *expression* of the switch statement.
- In an *is-pattern* operator, the *pattern* on the right-hand-side is tested against the expression on the left.
- In a switch expression, the *pattern* of a *switch_expression_arm* is tested against the expression on the switch-expression's left-hand-side.
- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.

The value against which a pattern is tested is called the ***pattern input value*** for the pattern.
```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +> *Note*: The ordering of the grammar rules in *simple_designation* is important. By putting *discard_designation” first, the source token `_` is recognized as a discard rather than as a named identi
I think the note should say that a *single_variable_designation* cannot be the identifier `_`, which is taken as a *discard_designation*.

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
>  The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.12.12.1](expressions.md#1212121-the-is-type-operator)). If the t
The constraint

>  It is a compile-time error if the *type* is a nullable value type

Appears both here and a couple of paragraphs below.

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +- If *type* is omitted and the input value's type is a tuple type, then the number of subpatterns shall to be the same as the cardinality of the tuple. Each tuple element is matched against the corre
```suggestion
- If *type* is omitted and the input value's type is a tuple type, then the number of subpatterns shall be the same as the cardinality of the tuple. Each tuple element is matched against the corresponding *subpattern*, and the match succeeds if all of these succeed. If any *subpattern* has an *identifier*, then that shall name a tuple element at the corresponding position in the tuple type.
```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +If *type* is omitted, the type is assumed to be the static type of the input value.
This is not right, as an input value of type `object` can be matched against the pattern `(1, 2)`, but `object(1, 2)` is an error. I think this sentence can be removed.

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +Given a match of an expression *e* to the pattern *type* `{` *property_pattern_list* `}`, it is a compile-time error if the expression *e* is not pattern-compatible with the type *T* designated by *t
```suggestion
Given a match of an expression *e* to the pattern *type* `{` *property_pattern_list* `}`, it is a compile-time error if the expression *e* is not pattern-compatible with the type *T* designated by *type*. If the type is absent, the type is assumed to be the static type of *e*. Each of the identifiers appearing on the left-hand-side of its *property_pattern_list* shall designate an accessible readable property or field of *T*. If the *simple_designation* of the *property_pattern* is present, it declares a pattern variable of type *T*.
```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is
```suggestion
At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is read, and its value matched against its corresponding pattern. The result of the whole match is `false` only if the result of any of these is `false`. The order in which subpatterns are matched is not specified, and a failed match may not test all subpatterns at runtime. If the match succeeds and the *simple_designation* of the *property_pattern* is a *single_variable_designation*, the variable declared by its *identifier* is assigned the matched value.
```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +
```suggestion
It is a compile-time error to use a discard pattern in a *relational_expression* of the form *relational_expression* `is` *pattern* or as the pattern of a *switch_label*.

```

2024-12-16 22:04 UTC, gafter commented on standard/patterns.md
> +### §discard-pattern-new-clause Discard pattern
The subsumption and exhaustiveness subsections need to be revised to account for these new pattern forms.

2024-12-16 22:04 UTC, gafter commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Since the switch expression has only one value operand, there is no associativity issue. There is only one way it could possibly associate. According to the compiler, the following precedence levels are from looser to tighter:
```
            Multiplicative,
            Switch,
            Range,
            Unary,
```

A switch expression may indeed have a switch expression as its left operand.

2024-12-16 22:04 UTC, gafter commented on standard/expressions.md
> +    ;
```suggestion
switch_expression
    : switch_expression 'switch' '{' (switch_expression_arms ','?)? '}'
    | range_expression
    ;
```

2024-12-16 22:04 UTC, gafter commented on standard/expressions.md
> +The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the
```suggestion
The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the `=>` tokens of the *switch_expression_arm*s. It is an error if no such type exists. The expression in every arm of the switch expression is implicitly converted (§switch-expression-conversion) to that type.
```

2024-12-16 22:17 UTC, gafter commented on standard/expressions.md
> +Every *identifier* of the pattern introduces a new local variable that is definitely assigned once the corresponding *relational_expression* tests `true`.
The section on definite assignment is in `variables.md` and needs to be extended to cover the is-pattern operator.

2025-02-16 21:07 UTC, Nigel-Ecma commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
👍’ed the above but a minor grammar question: should the first  comma of each bullet be a semi-colon?

2025-02-16 21:33 UTC, Nigel-Ecma commented on standard/expressions.md
> +    ;
@gafter above changed the order of the alternatives but also allowed there to be no arms as per the original, however that is invalid as the switch must cover all possible values – that gives us:

```suggestion
switch_expression
    : switch_expression 'switch' '{' switch_expression_arms ','? '}'
    | range_expression
    ;
```

2025-02-16 21:51 UTC, Nigel-Ecma commented on standard/expressions.md
> +The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the
I think the “expressions appearing to the right of the `=>` tokens of the *switch_expression_arm*s” of the original might be a case for introducing an extra rule to the grammar so simply the language. First replace the *switch_expression_arm* rule (lines 3573-5) with:

```
switch_expression_arm
    : pattern case_guard? '=>' switch_expression_arm_expression
    ;
    
switch_expression_arm_expression
    : expression
    ;
```

And then modify @gafter’s suggestion to match:

```suggestion
The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s. It is an error if no such type exists. The expression in every arm of the switch expression is implicitly converted (§switch-expression-conversion) to that type.
```

2025-02-16 21:56 UTC, Nigel-Ecma commented on standard/expressions.md
> +    | multiplicative_expression '%' switch_expression
This should be resolved if suggestions above are adopted.

2025-02-16 22:27 UTC, Nigel-Ecma commented on standard/patterns.md
> +> *Note*: The ordering of the grammar rules in *simple_designation* is important. By putting *discard_designation” first, the source token `_` is recognized as a discard rather than as a named identi
OK, my suggestion following the pattern of §12.19.1:

```suggestion
When recognising an *simple_designation* if both the *discard_designation* and *single_variable_designation* alternatives are applicable then the former shall be chosen.

> *Note*: Using ANTLR *simple_designation* will have the required semantics automatically, as ANTLR adopts the convenience of selecting the first alternative when multiple alternatives are applicable. *end note*
```

Possible wording for @gafter’s follows, 👍 which you prefer…

2025-02-16 22:34 UTC, Nigel-Ecma commented on standard/patterns.md
> +> *Note*: The ordering of the grammar rules in *simple_designation* is important. By putting *discard_designation” first, the source token `_` is recognized as a discard rather than as a named identi
And possible wording for @gafter’s suggestion:

```suggestion
The *identifier* of a *single_variable_designation* may not be “_”.

> Note: This restriction exists to avoid an ambiguity in *simple_designation*.
```

(@gafter – feel free to reword!)

👍 your pick…

2025-02-16 23:00 UTC, Nigel-Ecma commented on standard/patterns.md
> +At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is
I don’t think identifiers themselves declare things, declarations do, so following @gafter maybe:

```suggestion
At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is read, and its value matched against its corresponding pattern. The result of the whole match is `false` only if the result of any of these is `false`. The order in which subpatterns are matched is not specified, and a failed match may not test all subpatterns at runtime. If the match succeeds and the *simple_designation* of the *property_pattern* is a *single_variable_designation*, the declared variable is assigned the matched value.
```

2025-02-16 23:17 UTC, Nigel-Ecma commented on standard/patterns.md
> +
At least one compiler disagrees:

```
class _ { ... }
...
_ p = new _();
if (p is _)
```

Produces a warning that `_` refers to the type and not the discard pattern.

This is (unfortunately, blame history) probably the required semantics.

2025-02-18 12:06 UTC, jskeet commented on standard/expressions.md
> +A *switch_expression* may not be used as an *expression_statement*.
As always, I find "may not" to be somewhat ambiguous. Could we use "shall not" here?

2025-02-18 12:06 UTC, jskeet commented on standard/expressions.md
> +The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the
Do we actually need it to be an error for there to be no best common type? I'd only expect that to be a problem if we need the switch expression to *have* a type, e.g. for assignment to `var`. If we're just trying to convert the switch expression to a known type, it should be fine. 

Example:

```csharp
var now = DateTime.UtcNow;
// Valid: every arm is implicitly convertible to string?
string? x = now.Month switch { _ => null };
// Invalid: no best type
var y = now.Month switch { _ => null };
```

2025-02-18 12:06 UTC, jskeet commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if some arm of the switch expression handles every value of its input.  The compiler shall produce a warning if a switch expression is not exhaustive.
```suggestion
A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not exhaustive.
```

Or something like that - currently I read the proposal as "if there's some arm X such that X handles every value".

2025-02-18 12:06 UTC, jskeet commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
Possibly reinforce that this last part can only happen if the switch expression is not exhaustive? (Or if there's a compiler bug that makes it *think* it's exhaustive when it isn't really...)

2025-02-18 12:06 UTC, jskeet commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` involved `is`; either might be a valid parse of a qualified identifier. In such a case, only
(Agree with involved => involving, but also that we need to tighten up the language.)

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value
```suggestion
Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value of *e* is not bound to anything. (Although a declared variable with the name `_` may be in scope at that point, that named variable is not seen in this context.) Otherwise, if the *simple_designation* is *single_variable_designation*, a local variable ([§9.2.9](variables.md#929-local-variables)) of the given type named by the given identifier is introduced. That local variable is assigned the value of the pattern input value when the pattern *matches* the value.
```

(Just for consistency between the two checks.)

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if *designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value of *e* is n
This time we've got "if *designation*" twice - we could make both of these match "if the *designation*" from line 82, or remove "the" from line 82.

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +If *designation* is a *tuple_designation*, the pattern is equivalent to a *positional_pattern* (§positional-pattern-new-clause) of the form `(var` *designation*, ... `)` where the *designation*s are
And again...

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +If *designation* is a *tuple_designation*, the pattern is equivalent to a *positional_pattern* (§positional-pattern-new-clause) of the form `(var` *designation*, ... `)` where the *designation*s are
(I suspect we should just remove "the" from line 82 instead...)

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +- If *type* is omitted and the input value's type is a tuple type, then the number of subpatterns shall to be the same as the cardinality of the tuple. Each tuple element is matched against the corre
Is "input value's type" here the compile-time type or the execution-time type? I assume it's compile-time, but it may be worth us clarifying.

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +- Otherwise, if *type* is omitted, and the input value is of type `object`, `System.ITuple`, or some type that can be converted to `System.ITuple` by an implicit reference conversion, and no *identif
```suggestion
- Otherwise, if *type* is omitted, and the input value is of type `object` or some type that can be converted to `System.ITuple` by an implicit reference conversion, and no *identifier* appears among the subpatterns, then the match uses `System.ITuple`.
```

(Basically this relies on the identity conversion from `ITuple` to `ITuple` which is, I believe, an implicit reference conversion.)

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +- Otherwise, the pattern is a compile-time error.
"results in" or something similar, rather than saying the pattern *is* an error? (Or perhaps "the pattern is invalid and a compile-time error shall be issued" or similar?

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +> if (s is {}) ...
It may be worth noting the difference between:

```csharp
if (s is {} x2)
```

and

```csharp
if (s is var x3)
```

... the latter only matches on non-null values, whereas `var` would match on null (and the type of `x3` is `string?` instead of `string` in a nullable context). I only mention this as a reader might wonder why `{} x2` is useful when `var` exists.

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +    : type? property_subpattern simple_designation?
I believe that `type` here can't be a nullable reference type or nullable value type. I suspect we need to state that.

2025-02-18 12:06 UTC, jskeet commented on standard/patterns.md
> +Every expression matches the discard pattern, which results in the value of the expression being discarded.
Should we have this in italics or bold? We're defining a term, right?

2025-07-02 19:40 UTC, BillWagner commented
See #579 for useful references.

2025-07-02 19:48 UTC, jskeet commented
We should make sure we get the precedence right, as per #300.

2025-07-02 21:01 UTC, gafter commented
@gafter will try to summarize where we are on this PR.

2025-07-14 23:38 UTC, Nigel-Ecma commented
> Prior to V8, we have a term “switch expression” defined as the _expression_ inside parens in a `switch` statement.
> 
> Now, we’re introducing a switch as an expression, and we have a new grammar rule called _switch_expression_. The difference between “switch expression” (without a *…* fence or separating underscore) and *switch_expression* likely is too subtle. So, how to differentiate them?
> 
> Although C calls such a switch expression a “controlling expression” (and uses that term as well for `if`, `while`, `for`, and `do` statements), we already state, “The _**governing type**_ of a `switch` statement is established by the switch expression.”
> 
> **As such, I have replaced all occurrences of “switch expression” (which exist only in the statements chapter) with “switch’s governing expression.”**
> 
> Fixes #576. Fixes #300.

Instead of “governing expression” I’ll offer “selector expression”, which is used by at least Java & Pascal.

2025-07-29 09:33 UTC, jskeet commented
> Instead of “governing expression” I’ll offer “selector expression”, which is used by at least Java & Pascal.

Selector expression works for me. Should we change to "selector type" as well, instead of "governing type"?

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Syntactically, a switch expression's block may be empty. Because of the target-typing rule, there are legal programs that contain no switch expression arms, such as this statement: `int x = 1 switch {};` (which will always throw an exception and produces a warning that "The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '_' is not covered.").

However, without a target type it is expected to be a semantic error, because there is no common type among the switch arms.

The (left) operand to a switch expression may be a switch expression:

```antlr
switch_expression
    : range_expression
    | switch_expression 'switch' '{' ( switch_expression_arms ','? )? '}'
    ;
```

I suppose we ought to reorganize this to avoid left recursion:

```antlr
switch_expression
    | range_expression ( 'switch' '{' ( switch_expression_arms ','? )? '}' )*
    ;
```

There is no issue of precedence of a switch expression because it has no right-hand expression operand. There is only one possible way to interpret `a switch { b => c } switch { d => e }`.

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +    ;
No. When there is a target type it is possible for there to be no switch expression arms.
https://sharplab.io/#v2:CYLg1APgAgzABFATHAwnA3gWAFBzwxZLXfUgSwDsAXOADzgF44BGOAZwHcyqBjACwwBfANw5SgnIKA==

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +A *switch_expression* may not be used as an *expression_statement*.
Perhaps better: "is not", since it is simply not in the yield of the grammar of *expression_statement*.

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the
This specification does not describe target-typed switch expressions. See
https://github.com/dotnet/csharplang/issues/2389
https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/patterns.md

The type of the switch_expression is the best common type ([§12.6.3.15](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the => tokens of the switch_expression_arms if such a type exists and the expression in every arm of the switch expression can be implicitly converted to that type. In addition, we add a new switch expression conversion, which is a predefined implicit conversion from a switch expression to every type T for which there exists an implicit conversion from each arm's expression to T.

We have to be careful defining when the common type must exist (when there is no target type) and when it doesn't (the switch is target-typed). The spec must say that when there is no target type, it is an error if there is no common type.

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
No. It turns out it can happen due to nulls too.

https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAJgEsDOamAsAFAACAzFuQExYDCWA3mVuzdeQIwBsNAFiwBZZLhgAKcQBcA/FgAeAShZsO6mVgCeWALyKs+AO65pAYwAWLLJoBeegHxZ6AXwDca9i7IugA===

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +> *Note*: Lookup for the right operand of the `is` operator must first test as a *type*, then as an *expression* which may span multiple tokens. In the case where the operand is an *expreesion*, the
```suggestion
> *Note*: Lookup for the right operand of the `is` operator must first test as a *type*, then as an *expression* which may span multiple tokens. In the case where the operand is an *expression*, the pattern expression must have precedence at least as high as *shift_expression*. *end note*
```

2025-07-29 23:29 UTC, gafter commented on standard/expressions.md
> +Every *identifier* of the pattern introduces a new local variable that is definitely assigned once the corresponding *relational_expression* tests `true`.
```suggestion
Every *identifier* of the pattern introduces a new local variable that is definitely assigned where the corresponding *relational_expression* tests `true`.
```

2025-07-29 23:40 UTC, Nigel-Ecma commented
> > Instead of “governing expression” I’ll offer “selector expression”, which is used by at least Java & Pascal.
> 
> Selector expression works for me. Should we change to "selector type" as well, instead of "governing type"?

I’m going to say no, the different names here makes sense to me, I think ;-)

2025-07-30 01:47 UTC, jnm2 reviewed
(More later)

2025-07-30 01:47 UTC, jnm2 commented on standard/statements.md
> +    : 'when' null_coalescing_expression
What is the reason to specify null coalescing expressions for `when` clauses? If it is to block invalid expressions, I noticed that `null_coalescing_expression` would directly allow `throw_expression`. (https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1215-the-null-coalescing-operator) Throw expressions are not permitted by the current Roslyn compiler with any language version. Is this later language on line 737 sufficient to disallow throw expressions?

> its expression shall be implicitly convertible to the type `bool` and that expression is evaluated as an additional condition for the case to be considered satisfied

And again so I can follow along, what is the reason to use `null_coalescing_expression` in particular?

2025-07-30 01:47 UTC, jnm2 commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
> In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.

When we get to C# 9 with parenthesized patterns and logical patterns, we might want to remember to come back if we don't generalize this statement now, since `and` takes two subpatterns that do not retrieve new values to test against.

2025-07-30 07:32 UTC, Nigel-Ecma commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
@gafter – There is no need to remove self left-recursion in this sort of case, it occurs a lot in the grammar – stick with the first grammar which follows the pattern of many rules in the expression stack.

I must admit I’ve just jumped into this but “there are legal programs that contain no switch expression arms” followed an example that always throws an exception is, lets say, curious. Is there a no-arm example which doesn’t always throw? (Would not a better warning include that fact that it will throw?)

Whatever the answer the semantics need to be clearly defined in the Standard, and this comment suggests to me they are not.

2025-07-30 16:53 UTC, jnm2 commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
```suggestion
At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* matches the *switch_expression_arm*'s pattern, and for which the *case_guard* of the *switch_expression_arm*, if present, evaluates to `true`. If there is no such *switch_expression_arm*, the *switch_expression* throws an instance of the exception `System.Runtime.CompilerServices.SwitchExpressionException` if this type is defined in the compilation or references at compile time, or an instance of `System.InvalidOperationException` otherwise.
```

2025-07-30 16:53 UTC, jnm2 commented on standard/patterns.md
> +- Otherwise, the pattern is a compile-time error.
Patterns (including property patterns and positional patterns) implicitly unwrap `System.Nullable<T>`, as part of their "checks that the input value is not `null`". Do we need to say something to this effect here?

Example:

```cs
class C
{
    void M(Point? p)
    {
        if (p is (var x, var y)) // True
        {
        }
    }
}

struct Point
{
    public int X, Y;
    public void Deconstruct(out int x, out int y) { x = X; y = Y; }
}
```

2025-07-30 18:14 UTC, Nigel-Ecma commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
This change does not seem right for the Standard, is it not adding an exception which a particular compiler uses when using an older version of its runtime? As such it is down to the implementation to document how it behaves in such a situation, while C# v8 specifies `SwitchExpressionException`. Or am I missing something?

2025-07-30 18:18 UTC, Nigel-Ecma commented on standard/patterns.md
> +- Otherwise, the pattern is a compile-time error.
Nothing needs to be said, that's how checking whether a `Nullable<T>` is `null` works, which is defined elsewhere in the Standard.

2025-07-30 18:50 UTC, Nigel-Ecma commented on standard/statements.md
> +    : 'when' null_coalescing_expression
Under `expression` there is a whole stack (with some branches) of rules/productions which controls how subexpressions are group, i.e. the precedence. Part way down is  *null_coalescing_expression* and down at the bottom is *parenthesized_expression*.

What this change is doing is changing what can directly occur after a `when` *without* being in parenthesis. A common reason for doing this is to avoid parsing ambiguities that would occur is something is not wrapped in parenthesis and I guess that is why this change was made here – something between *expression* and *null_coalescing_expression* would cause a parsing ambiguity if it was not wrapped.

The important thing is this change is not changing what constructs are valid here, just which ones must be wrapped to be valid – which isn’t a semantic change *per se*. So `throw` is there either way, and if it is indeed invalid then there is, or should be, a semantic rule specifying that.

2025-07-30 19:13 UTC, jnm2 commented on standard/patterns.md
> +    ;
(In future versions of C#, there will be other kinds of subpatterns besides property subpatterns and positional subpatterns, such as `<subpattern> and <subpattern>` in C# 9, or `is [<subpattern, <subpattern>]` later on. At that point, calling this definition `subpattern` will seem overly broad.)

2025-07-30 19:22 UTC, jskeet commented
We'll go with selector expression, but keep governing type.

@gafter will attempt to get this ready for review for the September meeting.

2025-09-12 16:56 UTC, BillWagner commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if some arm of the switch expression handles every value of its input.  The compiler shall produce a warning if a switch expression is not exhaustive.
I like Jon's rewording.

2025-09-12 16:56 UTC, BillWagner commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
I don't know if it's necessary, except as a *Note*. The compiler emits a warning for a non-exhaustive switch expression, so it's a valid program for a non-exhaustive switch expression.

2025-09-13 23:00 UTC, gafter commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
A switch expression with no arms always throws.

2025-09-13 23:40 UTC, gafter commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
I'm not going to take the suggested change.

2025-09-14 00:39 UTC, gafter commented on standard/patterns.md
> +At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is
A simple_designation does indeed define a variable. I reject your suggested change because the variable is defined whether or not it succeeds.

2025-09-14 00:49 UTC, gafter commented on standard/patterns.md
> +
In this case, for compatibility it isn't a discard pattern. I will work on specifying that or add an issue for it.

2025-09-14 00:52 UTC, gafter commented on standard/statements.md
> +    : 'when' null_coalescing_expression
This is done to avoid an ambiguity with the `=>` of a lambda expression.

2025-09-14 01:47 UTC, gafter commented
I think this is now ready for re-review.

2025-09-15 21:42 UTC, BillWagner reviewed
Nice. A few clarifying comments, and some formatting suggestions.

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +> |  [§12.11](expressions.md#1210-arithmetic-operators)              | Multiplicative                   | `*` `/` `%` |
probably a merge issue:

```suggestion
> |  [§12.11](expressions.md#1211-arithmetic-operators)              | Multiplicative                   | `*` `/` `%` |
```

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +> |  [§12.22](expressions.md#1222-assignment-operators) and [§12.20](expressions.md#1220-anonymous-function-expressions)  | Assignment and lambda expression | `=` `= ref` `*=` `/=` `%=` `+=` `-=` `<<
I think this was dropped by mistake in the merge:

```suggestion
> |  [§12.22](expressions.md#1222-assignment-operators) and [§12.20](expressions.md#1220-anonymous-function-expressions)  | Assignment and lambda expression | `=` `= ref` `*=` `/=` `%=` `+=` `-=` `<<=` `>>=` `&=` `^=` `\|=` `=>`   `??=` |
```

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
style question, do we need "said to be"?, or is this the definition?

```suggestion
A switch expression is *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not exhaustive.
```

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +    1. Otherwise, `D` is `R`.
Needs one more indent space:

```suggestion
     1. If `R` is a nullable value type, `D` is the underlying type of `R`.
     1. Otherwise, `D` is `R`.
```

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +    1. Otherwise, the result is `false`.
similar:

```suggestion
     1. If `T` is a reference type, the result is `true` if:
         - an identity conversion exists between `D` and `T`, or
         - `D` is a reference type and an implicit reference conversion from `D` to `T` exists, or
         - `D` is a value type and a boxing conversion from `D` to `T` exists.
     1. If `T` is a nullable value type, the result is `true` if `D` is the underlying type of `T`.
     1. If `T` is a non-nullable value type, the result is `true` if `D` and `T` are the same type.
     1. Otherwise, the result is `false`.
```

2025-09-15 21:42 UTC, BillWagner commented on standard/expressions.md
> +
let's remove the extra blank line:

```suggestion
```

2025-09-15 21:42 UTC, BillWagner commented on standard/patterns.md
this drove me nuts at first. When we have repeated example / note blocks, we need to disable a markdown lint warning:

```suggestion
<!-- markdownlint-disable MD028 -->

<!-- markdownlint-enable MD028 -->
```

2025-09-16 18:39 UTC, Nigel-Ecma requested changes
Not a review *per se* (that will come) but a bunch of typos causing the word & grammar checkers to trip up. @BillWagner has spotted some typos as well. Somebody other than us two like to push these through the pipeline?

2025-09-16 18:39 UTC, Nigel-Ecma commented on standard/patterns.md
> +- In a switch statement, the *pattern* of a case label is tested against the *expression* of the switch statement.
Fix mdlint error

```suggestion
A pattern is tested against a value in a number of contexts:

- In a switch statement, the *pattern* of a case label is tested against the *expression* of the switch statement.  
```

2025-09-16 18:39 UTC, Nigel-Ecma commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
Fix xref:

```suggestion
A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.13.12](expressions.md#121312-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-statement)), and in a *switch_expression* (§switch-expression-new-clause) to express the shape of data against which incoming data is to be compared. Patterns may be recursive, so that parts of the data may be matched against ***sub-patterns***.  
```

2025-09-16 18:39 UTC, Nigel-Ecma commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value
Fix xref:

```suggestion
Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.2](variables.md#9292-discards)), and the value of *e* is not bound to anything. (Although a declared variable with the name `_` may be in scope at that point, that named variable is not seen in this context.) Otherwise, if the *simple_designation* is *single_variable_designation*, a local variable ([§9.2.9](variables.md#929-local-variables)) of the given type named by the given identifier is introduced. That local variable is assigned the value of the pattern input value when the pattern *matches* the value.  
```

2025-09-16 18:39 UTC, Nigel-Ecma commented on standard/expressions.md
> +- The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of t
Fix xref:

```suggestion
- The type of the *switch_expression* is the best common type [§12.6.3.16](expressions.md#126316-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of the *switch_expression_arm*s if such a type exists and each *switch_expression_arm_expression* can be implicitly converted to that type.
```

2025-09-16 18:39 UTC, Nigel-Ecma commented on standard/statements.md
> +    | 'switch' selector_expression switch_block
Fix rule syntax:

```suggestion
    : 'switch' selector_expression switch_block
```

2025-09-18 02:54 UTC, Nigel-Ecma commented
This only deals with one issue and how it might be fixed. In particular only the ability to pass the current grammar tests has been considered, the newly added grammar has been examined only as far as needed to diagnose the problem.

> ***Take this as a change request, it isn’t as it is not attached to a line (the change is in a file not yet altered by this PR)***

Unfortunately the introduced grammar for patterns containing discards breaks the overall grammar, e.g. both:

> ```csharp
> _ = some expression discarding result
> (var _, var x) = some tuple-valued expression
> ```

no longer *parse*. It call comes down to the question what is an “_”? In V7 it is an *identifier*, in this PR it is not but probably is intended to be, at least *sometimes* – which should sound familiar… contextual keywords.

Following the approach to contextual keywords the following change to *identifier* in §6.4.3 may be sufficient to address the issue:

> ```ANTLR
> identifier
>     : Simple_Identifier
>     | contextual_keyword
>     | discard_token
>     ;
> 
> discard_token
>     : '_'
>     ;
> ```

With this change all *existing* grammar checks parse as expected (though the automatic grammar checking run will fail until some reference files are updated).

I think this is the intended behaviour of “_” – it is special only when included literally in the syntactic grammar, just like a contextual keyword, and otherwise it is an *identifier*. If I’m wrong speak up!

Below I’ve included an explanation for why the grammar breaks, this is optional reading!

---

In V7 we have in §6.4.3 *Identifiers*:

> ```ANTLR
> identifier
>     : Simple_Identifier
>     | contextual_keyword
>     ;
> 
> Simple_Identifier
>     : Available_Identifier
>     | Escaped_Identifier
>     ;
> 
> fragment Available_Identifier
>     // excluding keywords or contextual keywords, see note below
>     : Basic_Identifier
>     ;
> ```

note that *Simple_Identifier* is a lexical rule, *context_keyword* is a parser rule, they don’t work the same. This stems from programming languages typically using regular/type-3 grammars for the lexical grammar & context-free/type-2 grammars for the syntactical grammar) and the “note below” covers the impact of this:

>   - Keywords and contextual keywords occur in the grammar as literal strings.
>   - ANTLR creates implicit lexical token rules for these literal strings.
>   - ANTLR considers these implicit rules before the explicit lexical rules in the grammar.
>   - Therefore fragment *Available_Identifier* will not match keywords or contextual keywords as the lexical rules for those precede it.

> *Example*: The contextual keyword `get` occurs in the grammar as a literal string where it is acting as a keyword, just like any other keyword, e.g.
>
>> ```ANTLR
>> get_accessor_declaration
>>     : attributes? accessor_modifier? 'get' accessor_body
>>     ;
>> ```
>
> The resultant lexical grammar looks something like:
>
>> ```ANTLR
>> …
>> KW_GET : 'get' ;
>> …
>> Simple_Identifier : … ;
>> ```
>
> and *get_accessor_declaration* is effectively:
>
>> ```ANTLR
>> get_accessor_declaration
>>     : attributes? accessor_modifier? KW_GET accessor_body
>>     ;
>> ```
>
> When the lexer tokenizes the input it stops at the first rule which matches the input, so “get” is tokenized as *KW_GET* and not as *Simple_Identifier*, so when used as a contextual keyword, as in *get_accessor_declaration*, it is recognised by the syntactic grammar.
>
> When “get” is used as an *identifier* the resolution goes: *KW_GET* -> *contextual_keyword* -> *identifier*.
>
> *end exmaple*

Also in V7 we have in §9.2.9.2 *Discards*:

> A ***discard*** is a local variable that has no name. A discard is introduced by a declaration expression ([§12.18](expressions.md#1218-declaration-expressions)) with the identifier `_`; and is either implicitly typed (`_` or `var _`) or explicitly typed (`T _`).
> 
> > *Note*: `_` is a valid identifier in many forms of declarations. *end note*

So in V7 “`_`” is an *identifier* and is recognised as a *Simple_Identifier*. The examples given right at the start are based on syntactic rules which include *identifier* when the “discards” are and so are recognised correctly.

---

This PR introduces the syntactic rules:

> ```ANTLR
> // §11.2.2 Declaration pattern
> discard_designation
>     : '_'
>     ;
>
> // §discard-pattern-new-clause Discard pattern
> discard_pattern
>     : '_'
>     ;
> ```

These:

- add `'_'` as a literal string to the syntactic grammar,
- which in turn means a lexical rule is generated, say *TK_UNDERSCORE*,
- which means an “_” is no longer tokenized as a *Simple_Identifier*
- and hence not recognised as an *identifier*,
- and the samples at the start fail to parse…

2025-09-19 01:46 UTC, Nigel-Ecma commented on standard/expressions.md
> +> |  §switch-expression-new-clause                                   | Switch                           | `switch { … }` |
Two part change (blame github).

I believe Switch should be *between* Range & Multiplicative

```suggestion
```

next changes adds it back in…

2025-09-19 01:48 UTC, Nigel-Ecma commented on standard/expressions.md
> +> |  [§12.11](expressions.md#1210-arithmetic-operators)              | Multiplicative                   | `*` `/` `%` |
Combing @BillWagner’s change & my part 2 (part 1 on line 152):

```suggestion
> |  §switch-expression-new-clause                                   | Switch                           | `switch { … }` |
> |  [§12.11](expressions.md#1211-arithmetic-operators)              | Multiplicative                   | `*` `/` `%` |
```

2025-09-19 01:54 UTC, Nigel-Ecma commented on standard/expressions.md
>      | multiplicative_expression '%' range_expression
To add this I had to delete @BillWagner’s comment:

> This needs more work (see other comments on grammar). I added this as a placeholder to remember it while addressing merge conflicts.

I believe the intended grammar is:

```suggestion
    : switch_expression
    | multiplicative_expression '*' switch_expression
    | multiplicative_expression '/' switch_expression
    | multiplicative_expression '%' switch_expression
```

2025-09-19 01:59 UTC, Nigel-Ecma commented on standard/expressions.md
> +    ;
Simplify/flatten grammar, add space between rules:

```suggestion
switch_expression
    : range_expression
    | switch_expression 'switch' '{' switch_expression_arms? '}'
    ;

switch_expression_arms
    : switch_expression_arm (',' switch_expression_arm)* ','?
    ;

switch_expression_arm
    : pattern case_guard? '=>' switch_expression_arm_expression
    ;

switch_expression_arm_expression
    : expression
    ;
```

2025-09-19 02:36 UTC, Nigel-Ecma commented on standard/expressions.md
> +A *switch_expression* is not an *expression_statement*.
The valid *statement_expression* kinds are given in §13.7; *switch_expression*, and plenty of other expressions, are not listed there and the corresponding descriptions don't include the same negative assertion.

Is there some reason to include this here, or can it be deleted?

Possible deletion:

```suggestion
```

2025-09-19 03:09 UTC, Nigel-Ecma commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
Is it not that some previous arm will always match but that the sum of all the previous arms match the whole domain, i.e. an arm is *subsumed* (§11.3) as with the switch statement (§13.8.3)?

Or is this not subsumption as it includes the guards?

Or does pattern subsumption (§11.3) need to be expanded to include guards?

Even if it is not subsumption I think it needs to be clear that it is the sum of *all* preceding arms.

2025-09-19 03:17 UTC, Nigel-Ecma commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
An addition to @BillWagner’s change – remove the compiler, also add blank line at end to break para. (Includes Bill’s suggestion):

```suggestion
A switch expression is *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  A warning shall be issued if a switch expression is not exhaustive.

```

2025-09-19 03:23 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Example*: The following converts values of an enum representing visual directions in an online map to the corresponding cardinal directions:
in -> on?

```suggestion
> *Example*: The following converts values of an enum representing visual directions on an online map to the corresponding cardinal directions:
```

(And why “online”, is the conversion different for physical maps? ;-))

2025-09-19 03:53 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Note*: Lookup for the right operand of the `is` operator must first test as a *type*, then as an *expression* which may span multiple tokens. In the case where the operand is an *expression*, the
The first sentence is a *requirement* and so not an informative note. Both options may span multiple tokens and isn’t something the Standard usually talks about outside of the lexical description. For an example (the style is used in multiple places) of a similar situation look at §12.20.1 which contains the normative statement:

> When recognising an *anonymous_function_body* if both the *null_conditional_invocation_expression* and *expression* alternatives are applicable then the former shall be chosen.

The second sentence seems a bit odd/awkward, might it confuse more than elucidate? We have parenthesised expressions to indicate how items should be grouped if required – and that is not often highlighted. Is there something unique or particularly unexpected here? If anything is to be said I think it is informative so should stay as a Note, unike the first sentence.

2025-09-19 04:06 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` on the right-hand-side of `is`; either might be a valid parse of a qualified identifier. In s
As above how the ambiguity should be resolved is normative so not a Note.

Maybe its been a long day but I’m struggling with “first thing found (which must be either a constant or a type)” – thing? not sure that a good word choice – must? is this "will” or “resolved to first constant or type found by lookup, if any” or something else?

2025-09-19 04:13 UTC, Nigel-Ecma commented on standard/expressions.md
> +An expression of the form `E is _`, where the right-hand-side is the identifier `_` and designates a type, is an *is-type operator*. To reduce confusion with the discard pattern, an implementation sh
I'm tempted to suggest that if someone has named a type “_” then the last thing they’re aiming for is to reduce confusion!

Seriously, should this be a requirement in the Standard, or just left to the sort of helpful informative message an implementation might choose to issue?

2025-09-19 04:29 UTC, Nigel-Ecma commented on standard/expressions.md
> +    1. Otherwise, `D` is `R`.
I think it needs more than one as the preceding lines are also being barfed at, isn’t MD “fun”!

2025-09-19 04:38 UTC, Nigel-Ecma commented on standard/expressions.md
> +Every *single_variable_designation* of the pattern introduces a new local variable that is *definitely assigned* ([§9.4](variables.md#94-definite-assignment)) when the corresponding *relational_expre
Is text required somewhere in §9.4 for it to remain complete?

2025-09-19 19:24 UTC, Nigel-Ecma commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
“is a syntactic form” is rather redundant
“express the shape” -> “describe the shape”?
“recursive” -> “nested”?

```suggestion
A ***pattern*** may be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-statement)), and in a *switch_expression* (§switch-expression-new-clause) to describe the shape of data against which incoming data is to be compared. Patterns may be nested, with parts of the data being matched against ***sub-patterns***.  
```

2025-09-19 19:44 UTC, Nigel-Ecma commented on standard/patterns.md
> +A pattern is tested against a value in a number of contexts:
Fix MDlint error – space before list.

```suggestion
A pattern is tested against a value in a number of contexts:

```

2025-09-19 20:04 UTC, Nigel-Ecma commented on standard/patterns.md
> +- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.
The first bullet names its construct “switch statement”, the second uses the rule name, “*is-pattern*”, while the third does both, “switch expression” & ”*switch-expression*”. Maybe  use one style consistently? Given the second bullet I might go with the rule names:

```suggestion
- In a *switch_statement*, the *pattern* of a *switch_label* is tested against the *selector_expression* of the *switch_statement*.  
- With an *is-pattern* operator, the *pattern* on the right-hand-side is tested against the expression on the left.  
- In a *switch_expression*, the *pattern* of a *switch_expression_arm* is tested against the expression on the *switch_expression*’s left-hand-side.  
- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.  
```

Yes, I left two occurrences of “expression” as in both cases *expression* is technically wrong but the actual rule name would I think be unhelpful.

Feel free to wordsmith better options!

2025-09-19 20:36 UTC, Nigel-Ecma commented on standard/patterns.md
>  ## 11.1 General
Is a value matched/tested against a pattern, or is a pattern matched/tested against a value?

My unscientific guess is value against pattern is the more common usage (including dare I mention in MS web pages), the Standard often goes with pattern against value – though not consistently, the edit below to line 5 changes from “pattern is tested against” to “data … matched against [patterns]”, while line 7 goes with “pattern is tested against”.

Which should the Standard use, or can it be happily inconsistent (variety is after all the spice of life :-))

I will leave you to muse, during review I have so far intentionally not suggested any changes from one to the other, or for consistency – but apologies if my resolve fails! ;-)

Addendum: The term “*pattern* input value” (emphasis added) is related to this – it is currently defined and used 12 times after in the Standard. Other languages tend to use terms which don’t imply that the value is going “into” the pattern (in the sense an argument value goes into a method). For example F#, a sibling language to C#, has a match expression, similar to C#’s switch expression, and talks about the input to the match, not the input to the pattern.

2025-09-19 22:46 UTC, Nigel-Ecma commented on standard/patterns.md
> +The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the t
A reordering, so the errors come after the reason, and minor reword:

```suggestion
The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the test succeeds, the pattern *matches* that value. This pattern form does not match a `null` value. It is a compile-time error if the *type* is a nullable value type ([§8.3.12](types.md#8312-nullable-value-types)) or a nullable reference type ([§8.9.3](types.md#893-nullable-reference-types)).
```

2025-09-19 23:08 UTC, Nigel-Ecma commented on standard/patterns.md
>  Certain combinations of static type of the pattern input value and the given type are considered incompatible and result in a compile-time error. A value of static type `E` is said to be ***pattern c
There is no “considered incompatible” but ”are incompatible”.

Further “Certain combinations” seems wrong to me, I think the order is: define pattern compatible, define applicable to (though why are two terms required?), state that if the type of the declaration pattern is not compatible with/applicable to the static type of the input value then a compile time error shall be thrown.

Apologies, no wordsmithing suggestion right now, maybe I’ll come up with one when I resume reviewing later…

2025-09-21 20:41 UTC, Nigel-Ecma commented on standard/patterns.md
> +The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the t
This states the match follows the rules of `is` (§12.13.12.1), then goes on to “If the test succeeds”.

That test works for nullable value types, but here a following sentence makes that a compile time error.

That test returns false for a null value, this is re-iterated in the last sentence here.

That test never considers user-defined conversions, that is not re-iterated here.

The description of that test carries a *Note* (informative) that as the test is performed at runtime there are no open types, line 92 below says open types are allowed…

This section and §12.13.12.1 need to be aligned, the tests for the two are currently documented to be different but also stated to be the same.

2025-09-21 21:12 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *declaration_pattern* is used to test that a value has a given type and, if the test succeeds, to optionally provide the value in a variable of that type.
I think there probably needs to be some syncing up between here and §9.2.9 *Local variables*, $9.4 *Definite assignment*, including the lifetime & scope of the variable – hardly anything is stated about these here:

- Line 90 below states the variable is assigned on a match
- **Informatively** line 121 states for the example that after the `if` the variable is in scope but not definitely assigned, there is no `else` in the example so the definite assignment status there is not covered.

2025-09-21 21:13 UTC, Nigel-Ecma commented on standard/patterns.md
> +> The condition of the `if` statement is `true` at runtime and the variable `v` holds the value `3` of type `int` inside the block. After the block the variable `v` is in scope, but not definitely as
See comment on line 66

2025-09-21 21:35 UTC, Nigel-Ecma commented on standard/patterns.md
> +    | designations ',' designation
Grammar tidy up:

```suggestion
tuple_designation
    : '(' designations? ')'
    ;
designations
    : designation (',' designation)*
```

A tuple in C# has ≥2 members, however a *tuple_designation* as ≥0 members due to *positional_pattern* (for which this is a shorthand) supporting `ITuple` (≥0 elements, despite its name) and `Deconstruct` (probably ≥0 as well?) as well as tuples. This suggests a different name to *tuple_designation* might be better.

2025-09-22 19:46 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *simple_designation* with the token `_` shall be considered a *discard_designation* rather than a *single_variable_designation*.
Following the comment on [line 4419 of expressions.md](https://github.com/dotnet/csharpstandard/pull/873/files#r2361681490):

```suggestion
When recognising a *simple_designation* if both the *discard_designation* and *single_variable_designation* alternatives are applicable then the former shall be chosen.
```

2025-09-22 20:22 UTC, Nigel-Ecma commented on standard/patterns.md
>  It is an error if the name `var` would bind to a type where a *var_pattern* is used.
### Dealing with “var x” – Part 2

There is an ambiguity in patterns, the input “var x” could be recognised as a *declaration_pattern* or as a *var_pattern*. As is this PR only deals with the latter, on line 191 below, and says nothing about the former.

I think the intended semantics are:

- In *declaration_pattern* the *type* cannot be the *identifier* `var`; i.e. if it starts with `var` then *var_pattern* is considered.
- A *var_pattern* is invalid (not considered as a valid parse) if a type called `var` is in scope.

This is tackled with two suggestions:

1. One on line 83 covering *declaration_pattern* ([Part 1](url))
2. Reword the original statement on line 191

```suggestion
A *var_pattern* cannot be used when a type named `var` is in scope.
```


> Note: I would have moved line 191 to the start of this clause but GitHub will not allow that, that would give:
>
> >### 11.2.4 Var pattern
> >A *var_pattern* *matches* every value. That is, a pattern-matching operation with a *var_pattern* always succeeds.
> >
> > A *var_pattern* is *applicable to* every type.
> >
> > A *var_pattern* cannot be used when a type named `var` is in scope.
>
> This seems to me to flow better, take your pick.

2025-09-22 20:23 UTC, Nigel-Ecma commented on standard/patterns.md
### Dealing with “var x” – Part 1

There is an ambiguity in patterns, the input “var x” could be recognised as a *declaration_pattern* or as a *var_pattern*. As is this PR only deals with the latter, on line 191 below, and says nothing about the former.

I think the intended semantics are:

- In *declaration_pattern* the *type* cannot be the *identifier* `var`; i.e. if it starts with `var` then *var_pattern* is considered.
- A *var_pattern* is invalid (not considered as a valid parse) if a type called `var` is in scope.

This is tackled with two suggestions:

1. This one, covering *declaration_pattern*
2. Reword the original statement on line 191 ([Part 2](https://github.com/dotnet/csharpstandard/pull/873/files#r2370216978))

```suggestion

The *type* of a *declaration_pattern* cannot be the *identifier* `var`.

> *Note:* In such a case the input may be recognisable as a *var_pattern* (§11.2.4).

```

2025-09-22 20:32 UTC, Nigel-Ecma commented on standard/patterns.md
> +    ;
Just a little grammar improvement:

```suggestion
subpatterns
    : subpattern (',' subpattern)*
    ;
```

2025-09-22 20:35 UTC, Nigel-Ecma commented on standard/patterns.md
> +    ;
@jnm2 – I think we need more than renaming a rule…

2025-09-22 20:48 UTC, Nigel-Ecma commented on standard/patterns.md
> +- Otherwise, if a suitable `Deconstruct` exists as a member of *type*, it is a compile-time error if the type of the input value is not pattern-compatible with *type*. At runtime the input value is t
This is a low-level implementation description, there should be no talk of “compiler-generated variables” – that is an *implementation* detail.

We need to re-think how `Deconstruct` is woven into the description of pattern matching – as an approximation pattern matching may be performed on single (simple or compound) values, tuples of values (or types which implement `ITuple`?), and on compound values that offer to present themselves as “tuple-like“ (pick a suitable term) by providing `Deconstruct`.

If we can get this covered upfront the descriptions of the different patterns forms should be a lot simpler/clearer.

2025-09-22 21:06 UTC, Nigel-Ecma commented on standard/patterns.md
> +> }
This seems a poor example as it is longhand for:

```csharp
var (sum, count) = SumAndCount(numbers);
Console.WriteLine($"Sum of [{string.Join(" ", numbers)}] is {sum}");
```

and introduces an `if` suggesting that the match might fail.

2025-09-22 21:30 UTC, Nigel-Ecma commented on standard/statements.md
> +> *Note*: For convenience, the parentheses in *switch_statement* can be omitted when the *selector_expression* is a *tuple_expression*. For example, `switch ((a, b)) …` can be written as `switch (a,
This reads to me as though this is an additional allowance and not part of the grammar – it’s line 720 above. Maybe reword?

2025-09-22 23:24 UTC, Nigel-Ecma requested changes, later dismissed
I’ve sprinkled a “few” ;-) comments and suggestions across the files, this is a wrap up to those.

Overall I think the presentation order of the material is quite confusing and/or overly complex, which has led to errors creeping in; leading to the view that a refactor is needed.

A couple of examples: grammar & semantic grouping; handling tuple-like things.

---

**Grammar & semantic grouping**

Consider *local_variable_declaration*, it is split into *explicitly_typed_local_variable_declaration* and *implicitly_typed_local_variable_declaration* (we ignore *ref_local_variable_declaration* as patterns have no corollary). The description covers the similarities and differences between the two.

Now consider *declaration_pattern* and part of *var_pattern*:

```ANTLR
declaration_pattern
    : type simple_designation
    ;
    
var_pattern
    : 'var' simple_designation // ignoring *tuple_designtation for now - see below
    ;
```

The first of these defines explicitly typed value matches, the second implicitly typed, both of which introduce a variable (including the discard one `_`) – the correlation with local variable declaration is clear. Rather than describe these two together they are split into separate non-adjacent clauses. This may have led to the errors in describing how a user-defined `var` type is handled, an issue with local variables as well (though a different resolution is used for patterns).

A triple of *declaration_pattern*, *explicitly_typed_declaration_pattern* and *implicitly_typed_declaration_pattern* describing the similarities, differences, and how a user-type `var` is handled might be more understandable/clear – aided by it following the same approach as for local variable declarations (the ones not in patterns, these patterns also declare local variables!)

But what of the part of *var_pattern* this does not cover?

```ANTLR
var_pattern
    : 'var' tuple_designation
    ;
```

This is a shorthand for a *positional_pattern*, described *before* positional patterns themselves are introduced. Would not describing the long form first be better? So this part of *var_pattern* could move to after *positional_pattern*.

So the current *var_pattern* is a melding of two only slightly related things, a refactor could separate then and associate each part to what they are more closely related to.

Coming to *positional_pattern* we see it is a rule with 4 non-terminals, *all optional*, and two terminals, open & close parentheses. Such a structure suggests its doing a lot of things, but that might be due to our next example.

---

**Handling tuple-like things**

The *syntax** of declaration, var, constant and positional patterns suggest that these C# patterns match:

1. Single constants
2. Single values, which could be of simple or complex types
3. Tuples of any combination of 1-3 (so including tuples of tuples)

However the *semantics* has (3) matching:

- Tuples
- Types with a `Deconstruct` method which provides a representation of the type as an ordered sequence of values – like a tuple does.
- Types which implement `ITuple` – through which they present themselves as tuples

It might help the description if this was refactored out under some heading, I used tuple-like as a placeholder above but leave the choice open, which could simply the description of positional patterns (and others?)

The positional pattern grammar might benefit from losing some of the optionals and list the valid combinations as alternatives.

---

**TL;DR**

I recommend a refactor & grammar re-org.

2025-09-23 16:00 UTC, jskeet reviewed
More to come, but it'll be tomorrow.

2025-09-23 16:00 UTC, jskeet commented on standard/expressions.md
> +There is a *switch expression conversion* (§switch-expression-conversion) from a switch expression to a type `T`
This is a direct restatement of the clause in conversions.md. Might we skip this paragraph and just link to the clause from line 3905?

2025-09-23 16:00 UTC, jskeet commented on standard/expressions.md
> +- The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of t
I'd be tempted to remove the list-ness of this. Just:

> If a switch expression is not subject to a *switch expression conversion*, then the type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of the *switch_expression_arm*s if such a type exists and each *switch_expression_arm_expression* can be implicitly converted to that type. It is an error if no such type exists.

(Quite possibly with commas and different targets, as per Nigel's change above.)

2025-09-23 16:00 UTC, jskeet commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
Potentially relevant case (unless I'm mistaken):

```csharp
object x = 10;
bool b = false;

int y = x switch
{
    int i when !b => 0,
    int i when b => 1,
    int i => 2,
    _ => 3
};
```

This compiles with no errors or warnings.

2025-09-23 21:49 UTC, Nigel-Ecma commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
@jskeet’s example shows that guards cannot in general be evaluated at compile time, so no coverage errors directly based on them. For the arms in the example, 1 & 2 match some subset of the pattern – but those subsets are not known in general at compile time, 3 matches anything 1 & 2 didn’t, and 4 matches everything that’s not `int`. So no arm is unreachable.

However if `x` was `int` then arm 4 is unreachable. Or alternatively if arms 2 & 3 are swapped the now 3rd arm with a guard is unreachable.

I think roughly:

- the definition cannot ignore guards (or else here arms 2 & 3 would be errors)
- a pattern with a guard cannot appear after the same pattern without a guard
- in general the order of arms with the same pattern but different guards cannot be checked to determine if any are unreachable.
- if a pattern occurs multiple times but only with guards then it must be assumed that coverage is not complete. E.g. after considering arms 1 & 2 (coverage is built up sequentially) we know all ints are covered, but arm 3 must be allowed as in general the full coverage of 1 & 2 cannot be ascertained at compile time.

I’ll leave trying to wordsmith that into a concise precise definition right now…

2025-09-23 22:18 UTC, Nigel-Ecma commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
Line 3910 requires an error if an arm is unreachable

Line 3912 requires a warning if the switch expression is not exhaustive

Was the first being a warning and the second an error the intention? Or both being an error?

A switch expression produces a value, to only warn that it might not and hence allow something unspecified to happen at runtime, seems possibly more consequential than unreachable arms.

2025-09-24 07:40 UTC, jskeet reviewed
Just a few more comments.

There's a lot to go through in our meeting. I think it might be worth @Nigel-Ecma picking two or three key aspects to discuss (e.g. handling `var`, and maybe the organization of the material) rather than focusing on the small details of wording which can be discussed in comments more easily than those larger aspects.

2025-09-24 07:40 UTC, jskeet commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` on the right-hand-side of `is`; either might be a valid parse of a qualified identifier. In s
If it fails to bind to a type, how can the "first thing found" by a type? I think I'm missing something - an example (not necessarily in the standard) might help me understand what we're talking about here. I agree with Nigel's dislike of "first thing found" but can't suggest anything better until I understand the intent in more detail.

2025-09-24 07:40 UTC, jskeet commented on standard/expressions.md
> +  1. Let `D` be derived from `R` as follows:
If we can figure out an alternative word to "derived" I think that would help. I assumed it was a derived type as in subclass etc to start with. (Would "inferred" still work? I think "derived" is the most precise word here - it just may not be the most helpful one...)

2025-09-24 07:40 UTC, jskeet commented on standard/patterns.md
> +- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.
Is the change from "In" to "With" in the second bullet deliberate to avoid the slight stutter of "In an is"? Or am I missing something more subtle?

2025-09-24 07:40 UTC, jskeet commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value
(I've updated Nigel's suggestion to remove trailing spaces.)

2025-09-24 09:08 UTC, Nigel-Ecma commented on standard/patterns.md
> +- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.
@jskeet – Me subtle? ;-) Bullets 1, 3, 4 relate to being in a statement/expression/nested context – all items with multiple parts; for bullet 2 it didn't read right to me to be “in” an operator (sounds like you’re in the code for an operator, similar to being in a method), so I used with an operator.

2025-09-24 09:18 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` on the right-hand-side of `is`; either might be a valid parse of a qualified identifier. In s
@jskeet – Good point, I missed that one! I think this one needs to follow the common pattern used else where for ambiguity (“if both A & B are valid derivations, A will be chosen” type of thing), but currently is in the “to be wordsmithed” task pile.

2025-09-24 09:34 UTC, Nigel-Ecma commented on standard/expressions.md
> +  1. Let `D` be derived from `R` as follows:
@jskeet – Following the pattern of line 259 would give:

> 1. Determine the type `D`. If `R` is a nullable value type, `D` is its underlying type; otherwise, `D is equal to `R`.

which removes derives and 2-sub bullets. There are other similar situations with wordings that are similar to this.

2025-09-24 19:45 UTC, jskeet commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
Note: this exception type is not yet in the annexes. We already have an issue for it: https://github.com/dotnet/csharpstandard/issues/1021

2025-09-24 19:46 UTC, jnm2 commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
```suggestion
At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* matches the *switch_expression_arm*'s pattern, and for which the *case_guard* of the *switch_expression_arm*, if present, evaluates to `true`. If there is no such *switch_expression_arm*, the *switch_expression* throws an instance of the exception `System.Runtime.CompilerServices.SwitchExpressionException` if this exception type is accessible within the compilation at this point, or else the exception `System.InvalidOperationException`.
```

2025-09-24 19:58 UTC, jskeet commented on standard/expressions.md
> +There is a *switch expression conversion* (§switch-expression-conversion) from a switch expression to a type `T`
Agreed in the meeting to do this.

2025-09-24 19:58 UTC, jskeet commented on standard/expressions.md
> +A *switch_expression* is not an *expression_statement*.
Agreed in the meeting to do this (deletion).

2025-09-24 20:01 UTC, jskeet commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
In meeting: if the guard is a constant expression with a value of true, that guard is effectively discarded, e.g.

```csharp
object x = 10;

int y = x switch
{
    int i when true => 1,
    int i => 2, // Invalid
    _ => 3
};
```

So maybe something like:

"because some previous pattern with no guard, or a pattern with a guard whose value is a constant expression with the value `true`, will always match"

2025-09-24 20:02 UTC, jskeet commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
Or introduce the "a pattern with a guard with a constant expression of value true is equivalent to a pattern without a guard" aspect when we introduce guards.

2025-09-24 20:09 UTC, jskeet commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
Meeting determined: no change required.

2025-09-24 20:12 UTC, jskeet commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
Let's change "shall be" to "may be" which also gives us wiggle room around nullable types and exhaustiveness.

2025-09-24 20:14 UTC, jskeet commented on standard/expressions.md
> +At runtime, the result of the *switch_expression* is the value of the *expression* of the first *switch_expression_arm* for which the expression on the left-hand-side of the *switch_expression* match
Let's make it "System.InvalidOperationException or a type derived from that". In that case we don't need the specific exception type in the annex either :) (But we do need InvalidOperationException.)

2025-09-24 20:20 UTC, jskeet commented on standard/expressions.md
> +> *Note*: Lookup for the right operand of the `is` operator must first test as a *type*, then as an *expression* which may span multiple tokens. In the case where the operand is an *expression*, the
@gafter will enumerate the situations in normative text.

2025-09-24 20:25 UTC, jskeet commented on standard/expressions.md
> +An expression of the form `E is _`, where the right-hand-side is the identifier `_` and designates a type, is an *is-type operator*. To reduce confusion with the discard pattern, an implementation sh
Agreed in meeting to delete.

2025-09-24 20:29 UTC, jnm2 commented on standard/patterns.md
> +The value against which a pattern is tested is called the ***pattern input value*** for the pattern.
Wordsmithing idea
```suggestion
The value against which a pattern is tested is called the ***pattern input value***.
```

2025-09-24 20:31 UTC, gafter commented on standard/expressions.md
> +Every *single_variable_designation* of the pattern introduces a new local variable that is *definitely assigned* ([§9.4](variables.md#94-definite-assignment)) when the corresponding *relational_expre
xref to

#### 9.4.4.34 is-pattern expressions

2025-09-24 20:32 UTC, jskeet commented on standard/patterns.md
>  ## 11.1 General
Leaving for folks to think about - please add comments, everyone.

2025-09-24 20:33 UTC, jskeet commented on standard/patterns.md
>  ## 11.1 General
In fact, let's deem this non-blocking, but @RexJaeschke will create a new issue to capture it.

2025-09-24 20:44 UTC, gafter commented on standard/patterns.md
If a type `var` is in scope, neither the var pattern nor the declaration pattern with that type is valid.

2025-09-24 20:48 UTC, jnm2 commented on standard/patterns.md
> +The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the t
An example of `is Xyz` and `is Xyz d` behaving differently is that `is dynamic` compiles, and `is dynamic d` does not.

2025-09-24 20:49 UTC, jskeet commented on standard/patterns.md
> +    | designations ',' designation
`if (x is var ())` compiles, somewhat shockingly... so the original grammar in the PR is probably right.

2025-09-24 20:51 UTC, jskeet commented on standard/patterns.md
> +    | designations ',' designation
(Nigel will still suggest an edited change, but it'll be stylistic rather than semantic.)

2025-09-24 20:55 UTC, jskeet commented on standard/patterns.md
> +A *positional_pattern* checks that the input value is not `null`, invokes an appropriate `Deconstruct` method ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on th
Not sure that ITuple *should* be mentioned in 12.7, as I *think* it's only used in positional patterns, not more general deconstruction. It's possible we should centralise its use within patterns though.

2025-09-24 20:58 UTC, jskeet commented on standard/patterns.md
> +A *positional_pattern* checks that the input value is not `null`, invokes an appropriate `Deconstruct` method ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on th
Do we need to say what the compiler invokes on `ITuple`? (And we need it to be in the relevant annex.) Or just "in order for the pattern to match, the number of subpatterns in the positional pattern must be the same as the number of items in the ITuple, and (something about conversions)"?

2025-09-25 07:05 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *positional_pattern* checks that the input value is not `null`, invokes an appropriate `Deconstruct` method ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on th
(My summary & thoughts post meeting)

The cases this covers:

- if the input value is a tuple type: the number of subpatterns must statically match the tuple arity, subpatterns & tuple elements are matched pairwise, order not specified, match can fail without checking all subpatterns.
- if the input value has a `Deconstruct` method whose number out parameters match the number of subpatterns, and the types of each parameter is compatible with the corresponding subpatterns matched pairwise then the values from invoking `Deconstruct` are matched pairwise, order not specified, match can fail without checking all subpatterns.
- if the input value implements `ITuple` then the number of elements in the `ITuple` value is checked at runtime to be equal to the number of subpatterns. Then the elements of the `ITuple` value are matched pairwise… etc.

I’ve listed these cases in the probable order of priority, i.e. if the input value is a tuple the first case is picked even though tuples implement `ITuple` (if that is added to the Standard) and `Deconstruct` (if that is added to the Standard); next if the type of the input value implements a suitable `Deconstruct` then case 2 is chosen; finally, if applicable, case 3 with dynamic arity check is chosen, and a compile time error occurs if it is not applicable.

Is this ordering correct, note it does not match the current text?

Whatever the ordering it needs to be clearly specified.

2025-09-26 11:59 UTC, RexJaeschke commented on standard/patterns.md
>  ## 11.1 General
See Issue https://github.com/dotnet/csharpstandard/issues/1424.

2025-10-19 19:23 UTC, Nigel-Ecma commented on standard/patterns.md
@gafter – Agree, that is why line 86 in the above change says “may be”. See [Part 2](https://github.com/dotnet/csharpstandard/pull/873/files#r2370216978) where a wording & position change proposal for the definition of this restriction is made.

2025-10-20 13:18 UTC, jskeet commented on standard/patterns.md
> +The value against which a pattern is tested is called the ***pattern input value*** for the pattern.
Looks good to me.

2025-10-20 17:49 UTC, BillWagner commented on standard/expressions.md
> +- The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of t
In other language elements, we describe this as an expression that doesn't have a type, but can be converted to a type. Would it be more consistent for a switch expression to not have a type, but be convertible to any common type of the switch_expression_arm_expression types?

2025-10-22 17:46 UTC, gafter commented on standard/expressions.md
> +- The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the *switch_expression_arm_expression*s of t
No, because it may have a type, just like `1` has a type but also can be converted to `byte`.

2025-10-22 17:55 UTC, gafter commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
This should probably be restated in terms of subsumption. case expression arms with guards are only considered if the guard is a constant expression equal to true (if it's equal to false, it doesn't subsume).

2025-10-22 17:56 UTC, gafter commented on standard/expressions.md
> +> *Example*: The following converts values of an enum representing visual directions in an online map to the corresponding cardinal directions:
For flavor.

2025-10-22 17:59 UTC, gafter commented on standard/expressions.md
> +> *Note*: Lookup for the right operand of the `is` operator must first test as a *type*, then as an *expression* which may span multiple tokens. In the case where the operand is an *expression*, the
I've done so in https://github.com/dotnet/csharpstandard/issues/1428 which still needs to be applied, either in this PR or separately.

2025-10-22 18:04 UTC, gafter commented on standard/expressions.md
> +    1. Otherwise, `D` is `R`.
Yes

2025-10-22 18:10 UTC, gafter commented on standard/patterns.md
> +The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the t
It is the testing of the value against the type that uses the same rules. There are additional constraints for a declaration pattern.

2025-10-22 18:11 UTC, gafter commented on standard/patterns.md
> +> The condition of the `if` statement is `true` at runtime and the variable `v` holds the value `3` of type `int` inside the block. After the block the variable `v` is in scope, but not definitely as
I don't see a comment on line 66. Please repeat the comment.

2025-10-22 18:13 UTC, gafter commented on standard/patterns.md
> +A *simple_designation* with the token `_` shall be considered a *discard_designation* rather than a *single_variable_designation*.
Is the suggestion really more clear?

2025-10-22 18:18 UTC, gafter commented on standard/patterns.md
> +Every expression matches the discard pattern, which results in the value of the expression being discarded.
If we intend it to be a definition, we should reword it, perhaps something like

> The **_discard pattern_** matches every expression.

2025-10-22 18:21 UTC, gafter commented on standard/statements.md
> +> *Note*: For convenience, the parentheses in *switch_statement* can be omitted when the *selector_expression* is a *tuple_expression*. For example, `switch ((a, b)) …` can be written as `switch (a,
Well, it is a note. Isn't this what notes are for?

2025-10-22 18:21 UTC, gafter commented
See also https://github.com/dotnet/csharpstandard/issues/1428

2025-10-22 18:29 UTC, Nigel-Ecma commented on standard/patterns.md
> +> The condition of the `if` statement is `true` at runtime and the variable `v` holds the value `3` of type `int` inside the block. After the block the variable `v` is in scope, but not definitely as
@gafter – https://github.com/dotnet/csharpstandard/pull/873#discussion_r2366395973

2025-10-22 18:33 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *simple_designation* with the token `_` shall be considered a *discard_designation* rather than a *single_variable_designation*.
@gafter – It is just the wording pattern that we’ve been using elsewhere, so it is a consistency suggestion which I guess helps clarity? (I think the link I included is no longer valid)

2025-10-22 19:33 UTC, gafter commented on standard/expressions.md
> +> |  [§12.22](expressions.md#1222-assignment-operators) and [§12.20](expressions.md#1220-anonymous-function-expressions)  | Assignment and lambda expression | `=` `= ref` `*=` `/=` `%=` `+=` `-=` `<<
```suggestion
> |  [§12.22](expressions.md#1222-assignment-operators) and [§12.20](expressions.md#1220-anonymous-function-expressions)  | Assignment and lambda expression | `=` `= ref` `*=` `/=` `%=` `+=` `-=` `<<=` `>>=` `&=` `^=` `\|=` `=>`  `??=` |
```

2025-10-22 19:34 UTC, gafter commented on standard/expressions.md
> +> |  [§12.9](expressions.md#129-unary-operators)              | Unary                            | `+` `-` `!` `~` `++x` `--x` `(T)x` `await x` |
```suggestion
> |  [§12.8](expressions.md#128-primary-expressions)              | Primary                          | `x.y` `x?.y` `f(x)` `a[x]` `a?[x]` `x++` `x--` `x!` `new` `typeof` `default` `checked` `unchecked` `delegate` `stackalloc`  |
> |  [§12.9](expressions.md#129-unary-operators)              | Unary                            | `+` `-` `!` `~` `^` `++x` `--x` `(T)x` `await x` |
```

2025-10-22 20:08 UTC, BillWagner commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value
This suggestion will fix the Word converter (the discard link):

```suggestion
Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.2](variables.md#9292-discards)), and the value of *e* is not bound to anything. (Although a declared variable with the name `_` may be in scope at that point, that named variable is not seen in this context.) Otherwise, if the *simple_designation* is *single_variable_designation*, a local variable ([§9.2.9](variables.md#929-local-variables)) of the given type named by the given identifier is introduced. That local variable is assigned the value of the pattern input value when the pattern *matches* the value.  
```

2025-10-22 20:10 UTC, jskeet approved these changes

2025-10-22 20:11 UTC, gafter approved these changes
Approved, but with additional items to be addressed later.

2025-10-29 02:49 UTC, Nigel-Ecma commented on standard/patterns.md
> +At runtime, the expression is tested against *T*. If this fails then the property pattern match fails, and the result is `false`. If it succeeds, then each *property_subpattern* field or property is
@gafter – I’m confused, I didn’t change what variable is defined/declared just the wording of your change suggestion above to (attempt to) make the *single_variable_designation* the actor rather than the *identifier*. That said its just a language change over your own suggestion and you should take your own if mine makes no sense to you!

2025-10-30 14:26 UTC, BillWagner commented
@gafter Is this now ready for me to merge? Or do you want to do more before we accept this?

2025-10-31 13:42 UTC, merged

2026-05-04 20:35 UTC, Nigel-Ecma commented on standard/expressions.md
> +    : range_expression 'switch' '{' (switch_expression_arms ','?)? '}'
Added to #1432

2026-05-04 20:43 UTC, Nigel-Ecma commented on standard/expressions.md
> +    | multiplicative_expression '%' switch_expression
Suggestions above were adopted, this is resolved.

2026-05-04 21:54 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *positional_pattern* checks that the input value is not `null`, invokes an appropriate `Deconstruct` method ([§12.7](expressions.md#127-deconstruction)), and performs further pattern matching on th
Added to #1432

2026-05-05 05:45 UTC, Nigel-Ecma commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
Previous comment from @jnm2 spun off as #1648

2026-05-05 06:00 UTC, Nigel-Ecma commented on standard/patterns.md
> +
Added to #1432

2026-05-05 06:05 UTC, Nigel-Ecma commented on standard/patterns.md
> +### §discard-pattern-new-clause Discard pattern
Added to #1432

2026-05-05 06:16 UTC, Nigel-Ecma commented on standard/expressions.md
> +The type of the *switch_expression* is the best common type [§12.6.3.15](expressions.md#126315-finding-the-best-common-type-of-a-set-of-expressions)) of the expressions appearing to the right of the
Added previous comment to #1432

2026-05-05 06:31 UTC, Nigel-Ecma commented on standard/patterns.md
> +- Otherwise, the pattern is a compile-time error.
Previous comment added to #1432

2026-05-05 06:35 UTC, Nigel-Ecma commented on standard/patterns.md
> +> if (s is {}) ...
Added to #1432

2026-05-05 08:10 UTC, Nigel-Ecma commented on standard/expressions.md
> +A switch expression is said to be *exhaustive* if every value of its input is handled by at least one arm of the switch expression.  The compiler shall produce a warning if a switch expression is not
Added to #1432

2026-05-05 08:23 UTC, Nigel-Ecma commented on standard/expressions.md
> +
Overtaken by #1285

2026-05-05 08:38 UTC, Nigel-Ecma commented on standard/patterns.md
> +Given a pattern input value ([§11.1](patterns.md#111-general)) *e*, if the *simple_designation* is *discard_designation*, it denotes a discard ([§9.2.9.1](variables.md#9291-discards)), and the value
Added to #1432

2026-05-05 09:07 UTC, Nigel-Ecma commented on standard/expressions.md
> +It is an error if some *switch_expression_arm*'s pattern cannot affect the result because some previous pattern and guard will always match.
Added to #1432

2026-05-05 09:10 UTC, Nigel-Ecma commented on standard/expressions.md
> +> *Note*: There is a grammar ambiguity between *type* and *constant_pattern* in a `relational_expression` on the right-hand-side of `is`; either might be a valid parse of a qualified identifier. In s
Overtaken by #1285

2026-05-05 09:18 UTC, Nigel-Ecma commented on standard/expressions.md
> +Every *single_variable_designation* of the pattern introduces a new local variable that is *definitely assigned* ([§9.4](variables.md#94-definite-assignment)) when the corresponding *relational_expre
Added to #1432

2026-05-05 09:24 UTC, Nigel-Ecma commented on standard/patterns.md
> +A ***pattern*** is a syntactic form that can be used with the `is` operator ([§12.12.12](expressions.md#121212-the-is-operator)), in a *switch_statement* ([§13.8.3](statements.md#1383-the-switch-stat
Added to #1432

2026-05-05 09:32 UTC, Nigel-Ecma commented on standard/patterns.md
> +- In nested contexts, the *sub-pattern* is tested against values retrieved from properties, fields, or indexed from other input values, depending on the pattern form.
Added to #1432

2026-05-05 09:43 UTC, Nigel-Ecma commented on standard/patterns.md
>  Certain combinations of static type of the pattern input value and the given type are considered incompatible and result in a compile-time error. A value of static type `E` is said to be ***pattern c
Added to #1432

2026-05-05 09:50 UTC, Nigel-Ecma commented on standard/patterns.md
> +The runtime type of the value is tested against the *type* in the pattern using the same rules specified in the is-type operator ([§12.13.12.1](expressions.md#1213121-the-is-type-operator)). If the t
Added to #1432

2026-05-05 10:02 UTC, Nigel-Ecma commented on standard/patterns.md
> +A *declaration_pattern* is used to test that a value has a given type and, if the test succeeds, to optionally provide the value in a variable of that type.
Added to #1432

2026-05-05 10:05 UTC, Nigel-Ecma commented on standard/patterns.md
> +> The condition of the `if` statement is `true` at runtime and the variable `v` holds the value `3` of type `int` inside the block. After the block the variable `v` is in scope, but not definitely as
Added to #1432 as part of #1662

2026-05-05 10:19 UTC, Nigel-Ecma commented on standard/patterns.md
>  It is an error if the name `var` would bind to a type where a *var_pattern* is used.
Added to #1432

2026-05-05 10:27 UTC, Nigel-Ecma commented on standard/patterns.md
Added to #1432

2026-05-05 10:40 UTC, Nigel-Ecma commented on standard/patterns.md
> +- Otherwise, if a suitable `Deconstruct` exists as a member of *type*, it is a compile-time error if the type of the input value is not pattern-compatible with *type*. At runtime the input value is t
Added to #1432

2026-05-05 10:43 UTC, Nigel-Ecma commented on standard/patterns.md
> +> }
Added to #1432

2026-05-05 11:24 UTC, Nigel-Ecma commented on standard/expressions.md
> +  1. Let `D` be derived from `R` as follows:
Added to #1432