Specify the mapping between tuple types and ValueTuple normatively.
dotnet/csharpstandard pull request #876
Opened 2023-08-07 14:29 UTC by jskeet

Alternative to #798.

2023-08-07 14:54 UTC, KalleOlaviNiemitalo requested changes

2023-08-07 14:54 UTC, KalleOlaviNiemitalo commented on standard/types.md
> +Tuple types with an arity of more than seven are constructed There does not need to exist a `System.ValueTuple<...>` declaration that directly matches the arity of any tuple type with a corresponding
The first sentence of that line ends strangely.  "are constructed There does not"

2023-08-07 14:57 UTC, KalleOlaviNiemitalo requested changes

2023-08-07 14:57 UTC, KalleOlaviNiemitalo commented on standard/types.md
> +Tuple types with an arity of more than seven are constructed There does not need to exist a `System.ValueTuple<...>` declaration that directly matches the arity of any tuple type with a corresponding
Remove the `I1` etc. from each `T1 I1` type argument of System.ValueTuple.

2023-08-07 14:59 UTC, jskeet commented on standard/types.md
> +Tuple types with an arity of more than seven are constructed There does not need to exist a `System.ValueTuple<...>` declaration that directly matches the arity of any tuple type with a corresponding
Done.

2023-08-07 14:59 UTC, jskeet commented on standard/types.md
> +Tuple types with an arity of more than seven are constructed There does not need to exist a `System.ValueTuple<...>` declaration that directly matches the arity of any tuple type with a corresponding
Whoops, thanks. Abortive edit. Have pushed another commit to fix that and improve the wording a little more.

2023-08-07 15:29 UTC, KalleOlaviNiemitalo commented
The "shorthand" term feels a bit wrong because these types have identity conversions between them but are not the same type.  It's not the same situation as with `int` vs. `global::System.Int32`.  The distinction is explained in more detail later though so it could be ok.

2023-08-10 04:52 UTC, Nigel-Ecma approved these changes
Nice, clear, straightforward.

2023-08-14 17:31 UTC, BillWagner approved these changes
This is a clear concise explanation. Thanks @jskeet 

Let's :shipit:

2023-08-14 17:38 UTC, jskeet commented
Right, merging - we can go over it retrospectively, but I want to clear the decks as far as possible.

2023-08-14 17:39 UTC, merged