Reverse some V7 edits w.r.t Indexers
dotnet/csharpstandard pull request #970
Opened 2023-10-25 15:29 UTC by RexJaeschke

During the final integration of the ref-related feature text into draft-v7, 15.9, "Indexers" was broken into 15.9.1, "General" and 15.9.2 "Indexer and Property Differences," and some of the previous content was moved around, deleted, and/or edited.

A. The following para was deleted from 15.9.1:

> The modifiers `virtual`, `override`, and `abstract` are mutually exclusive except in one case. The `abstract` and `override` modifiers may be used together so that an abstract indexer can override a virtual one.

When I discussed this privately with Bill, he thought this might be true for *all* member functions, not just indexers. However, I couldn't find any such text under Methods. (And we don't have a general "member-function" section to state such things anyway.) So, I restored this para.

B. The following para was duplicated, and I removed the first occurrence:

> The *formal_parameter_list* specifies the parameters of the indexer. The formal parameter list of an indexer corresponds to that of a method ([§15.6.2](classes.md#1562-method-parameters)), except that at least one parameter shall be specified, and that the `this`, `ref`, and `out` parameter modifiers are not permitted.

C. V6 contained the following:

> Based on the presence or absence of get and set accessors, an indexer is classified as follows:

> - An indexer that includes both a get accessor and a set accessor is said to be a ***read-write indexer***.
> - An indexer that has only a get accessor is said to be a ***read-only indexer***. It is a compile-time error for a read-only indexer to be the target of an assignment.
> - An indexer that has only a set accessor is said to be a ***write-only indexer***. Except as the target of an assignment, it is a compile-time error to reference a write-only indexer in an expression.

This was removed and summarized in a Note in the (new) 15.9.1, as follows:

> *Note*: This replacing of property/properties with indexer/indexers when reading [§15.7.3](classes.md#1573-accessors), [§15.7.5](classes.md#1575-accessibility) and [§15.7.6](classes.md#1576-virtual-sealed-override-and-abstract-accessors) applies to defined terms as well. For example *read-write property* becomes *read-write-indexer*. *end note*

This introduced several problems: It made this informative, and it removed three term definitions (which we use throughout), while suggesting that a series of new-parallel terms existed, without normatively enumerating them.

After discussing this with Bill, I propose replacing that Note with the following normative text:

> This replacing of property/properties with indexer/indexers when reading [§15.7.3](classes.md#1573-accessors), [§15.7.5](classes.md#1575-accessibility) and [§15.7.6](classes.md#1576-virtual-sealed-override-and-abstract-accessors) applies to defined terms as well. Specifically, *read-write property* becomes ***read-write indexer***, *read-only property* becomes ***read-only indexer***, and *write-only property* becomes ***write-only indexer***.

FYI, the reason I stumbled on this was while writing the spec for init accessors in V9. This requires the addition of a 3rd flavor of terms:  ***read-init property/indexer*** and ***init-only property/indexer***.

2023-10-25 18:39 UTC, BillWagner approved these changes
This LGTM @RexJaeschke

2023-10-25 20:23 UTC, Nigel-Ecma requested changes
I've suggested the undoing of the first change and the possible adding of text to §15.6.1. This avoids duplication of the material, as already occurs for properties.

If the duplication is felt warranted then it should also occur in properties and if the abstract virtual remark is kept it should be added to §15.6.1

2023-10-25 20:23 UTC, Nigel-Ecma commented on standard/classes.md
> +The modifiers `virtual`, `override`, and `abstract` are mutually exclusive except in one case. The `abstract` and `override` modifiers may be used together so that an abstract indexer can override a
This was omitted here, and similarly in §15.7.1 for properties, as it is in §15.6.1 referenced in the preceding para (as §15.6 both here and in properties) – bullets 3 & 5 of the list describing the valid combinations.

What isn’t remarked on in §15.6.1 is that `abstract` and `override` used together allow an abstract *member* to override a virtual one. If that remark needs to be made it should be made in §15.6.1 and not just here.

So I suggest removing this added para here and, if felt remark-worthy, adding to ¢15.6.1 that abstract members can override virtual ones – it falls out of the bulleted list but may not be obvious.

2023-10-25 20:23 UTC, Nigel-Ecma commented on standard/classes.md
> +This replacing of property/properties with indexer/indexers when reading [§15.7.3](classes.md#1573-accessors), [§15.7.5](classes.md#1575-accessibility) and [§15.7.6](classes.md#1576-virtual-sealed-ov
Good catch! Mea culpa as I made this a note and not just a para.

2023-11-01 20:34 UTC, jskeet approved these changes
We have agreed to remove the paragraph at 4191 in classes.md; after that, Rex can merge.

2023-11-01 20:34 UTC, jskeet commented on standard/classes.md
> +The modifiers `virtual`, `override`, and `abstract` are mutually exclusive except in one case. The `abstract` and `override` modifiers may be used together so that an abstract indexer can override a
```suggestion
```

2023-11-01 20:34 UTC, jskeet commented on standard/classes.md
> +
```suggestion
```

2023-11-01 20:36 UTC, Nigel-Ecma approved these changes

2023-11-01 20:39 UTC, merged